### ISSUE TITLE
Curio backend needs to be updated to support Curio 1.0

### ISSUE THREAD

**Issue by ntamas** [agronholm/anyio#101]
Curio 1.0 has been released a few days ago with lots of breaking changes; for instance, the `report_crash=...` keyword argument of `curio.spawn()` [has been removed](https://github.com/dabeaz/curio/blob/master/CHANGES#L203), which breaks Anyio when used with Curio 1.0. Most of the unit tests also fail on my machine because of this. I'm not experienced in Curio myself so I'd rather not attempt fixing it on my own.

**Comment by agronholm** [comment]
Thanks for letting me know. I will speed up the development of AnyIO 2.0 which also fixes asyncio on proactor event loops.

**Comment by agronholm** [comment]
Fixing `report_crash=False` was easy. Fixing the signal handling code won't be.

**Comment by agronholm** [comment]
@ntamas would you kindly review my PR that addresses this?
