### ISSUE TITLE
Missing functionality in socket I/O

### ISSUE THREAD

**Issue by tzickel** [agronholm/anyio#102]
I've thought about trying to use AnyIO in a library but notice this must-have APIs are missing:

1. An shutdown option for TCP sockets (i.e. close one half of the socket while keeping the other one alive). Such as asyncio.StreamWriter.write_eof()

2. An option to get the peername of the TCP socket, such as asyncio.StreamWriter.get_extra_info('peername')

Also nice to have (saw there are open issues on 3:

3. The raw socket for setting TCP keepalive (and maybe send/recv buffers, nodelay, etc..) like asyncio.StreamWriter.get_extra_info('socket')

4. asyncio also has asyncio.StreamWriter.drain() which actually handles backpressure in case you are trying to write too fast, not sure how and if it's handled in AnyIO.

**Comment by smurfix** [comment]
(4) Unlike asyncio. in anyio `socket.sendall` does not buffer, thus you don't need `drain`.

**Comment by tzickel** [comment]
Hmm... I wonder if there is any performance downside to that. Most async frameworks enable TCP_NODELAY by default. If there is no buffering:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_MRG/1.2/html/Realtime_Tuning_Guide/sect-Realtime_Tuning_Guide-Application_Tuning_and_Deployment-TCP_NODELAY_and_Small_Buffer_Writes.html

**Comment by smurfix** [comment]
If you have a high-throughput requirements you can use implement your own buffering reasonably easily.
asyncio on the other hand doesn't even have back pressure, its write buffer can grow without bounds. :-(

**Comment by tzickel** [comment]
https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.drain

**Comment by agronholm** [comment]
AnyIO also sets `TCP_NODELAY` for all TCP sockets.

**Comment by tzickel** [comment]
I need the first 2 functions for (and the third one will be nice too)::
https://github.com/tzickel/justredis/blob/master/justredis/justredis.py

Not having a buffer will also require putting a new lock over all of this function:
https://github.com/tzickel/justredis/blob/master/justredis/justredis.py#L382 (or writing my own buffering code).

**Comment by agronholm** [comment]
I'll take a look at this soon.

**Comment by agronholm** [comment]
For #3, if you like you can re-enable `TCP_NODELAY` using `setsockopt()`.

But as for getting the peer name, it's awkwardly missing from AnyIO's public API. I wasn't sure design-wise where to put it. But rest assured I will fix that in v2.0. In the meantime you can use the `_raw_socket` private member. I won't remove that in v1.x.

**Comment by agronholm** [comment]
@tzickel would you like to review #104?

**Comment by agronholm** [comment]
@tzickel one thing about `send_eof()`: can you show me or describe to me how you plan to use it?

**Comment by agronholm** [comment]
I just released v1.3 which contains the new `peer_address` SocketStream property.

**Comment by tzickel** [comment]
why not wait for send_eof..

Let's think I have one (or more) coroutine sending the server commands, and another (one) coroutine waiting for the results and processing them.

At one point I plan on signaling the server that I don't plan on sending any more commands, so I can send shutdown on the write part of the socket (shutdown).

A request/reply server when encountering that the reading socket is closed, should when finish processing all requests and then closing the sending part (which should only then trigger EOF on the client side).

**Comment by agronholm** [comment]
Are you aware that `send_eof()` does not work with TLS encrypted connections? How will your code work then?

**Comment by agronholm** [comment]
Most protocols have a way of indicating that the client wishes to end the session, without relying on transport level shenanigans. For Redis, that would be the `QUIT` command.

**Comment by tzickel** [comment]
Not sure if it exists, but a way to know the family of a socket ?

https://github.com/tzickel/jr/blob/0fff30400c93458b947dfca563b71b3a163bad76/justredis/justredis.py#L238

(if it's a unix domain for example, you can't do that).

**Comment by agronholm** [comment]
The pain point here is that, although trio and curio offer an "async socket" abstraction, asyncio does not and is only partially capable of it (missing things like `sock_sendto` and `sock_sendmsg`). So the question remains: what level of abstraction should AnyIO offer, and should it give users direct access to the socket object? Ticket #93 exists for that discussion.

**Comment by agronholm** [comment]
A workaround for this is checking the address type (unix sockets have `str`, tcp sockets have a tuple of (int, str)).

**Comment by tzickel** [comment]
Yep, that was my workaround for now...
https://github.com/tzickel/justredis/blob/master/justredis/nonsync/environments/anyio.py#L92

**Comment by agronholm** [comment]
I've implemented `send_eof()` and the `family` attribute. Note that this API may yet change before v2.0 final.
