### ISSUE TITLE
New event loop is created across different runs in asyncio

### ISSUE THREAD

**Issue by fantix** [agronholm/anyio#107]
I think this is not intentional - the implication is that setting new event loop policies will possibly lose the current event loop:

https://github.com/agronholm/anyio/blob/14daa2bad967bf6dd0f96d04ecffe8e383985195/anyio/_backends/_asyncio.py#L71-L86

This causes the pytest plugin to have different event loops across fixtures and tests:

```python
import asyncio

import pytest


@pytest.fixture
async def loop():
    return asyncio.get_event_loop()


@pytest.mark.anyio
async def test(loop):
    assert loop is asyncio.get_event_loop()  # fails here
```

In many cases, the fixture should share the same loop as the test, for example:

```python
import asyncpg

import pytest


@pytest.fixture
async def conn():
    return await asyncpg.connect("postgresql:///")


@pytest.mark.anyio
async def test(conn):
    assert await conn.fetchval("SELECT 123") == 123
```

```
E   RuntimeError: Task <Task pending name='Task-5' coro=<run.<locals>.wrapper() running at .../anyio/_backends/_asyncio.py:67> cb=[run_until_complete.<locals>.<lambda>()]> got Future <Future pending cb=[Protocol._on_waiter_completed()]> attached to a different loop
```

One possible solution is to cache all policy instances under different setups, and switch to use the right one. I'll create a PR with a more complete test.

**Comment by fantix** [comment]
Hmm, looking at the implementation of pytest-trio, I think we shouldn't use separate runs for fixtures, or within fixtures:

https://github.com/agronholm/anyio/blob/14daa2bad967bf6dd0f96d04ecffe8e383985195/anyio/pytest_plugin.py#L33-L50

**Comment by agronholm** [comment]
You do know that `asyncio.run()` does this as well? AnyIO is just following its example.

**Comment by agronholm** [comment]
Ok, so you're proposing that we defer the setup and teardown of async fixtures to the actual run stage of the test itself? I'm not totally opposed to the idea, but it's going to be quite a lot of work. Plus, the plugin will have to give a proper error on fixtures with scopes other than `function`.

I'd really like the ability to set up async service fixtures in other scopes than `function`, but I'm not sure if the other backends can support this. All in all, it feels like this problem should be solved in upstream pytest.

**Comment by fantix** [comment]
> You do know that `asyncio.run()` does this as well?

Oh my!!! I didn't know this, no wonder why it behaved differently for me all the time. Thanks for the info! That explains a lot.

> you're proposing that we defer the setup and teardown of async fixtures to the actual run stage of the test itself?

Yeah, it looks like this might be one of the very limited options. But it's completely up to you on how to put this. I mean, the idea of anyio is great and I really liked it - however this asyncio loop issue in its pytest support is a major blocker for me, I'll have to live with the alternatives until it's fixed.

#108 is not a proper fix, but the unit test is valid, covering 2 issues:
* The issue mentioned previously that the fixture yields a different loop
* `use_uvloop=False` is not working as expected (not setting the event loop policy back to default `None`)

I'll leave both the PR and this issue open and please feel free to modify or close. When time - not likely recently - I'll try to create a PR for the pytest/loop issue.

Thanks for looking into this!

**Comment by agronholm** [comment]
Would your tests work correctly with pytest-trio or curio's pytest plugin?

**Comment by fantix** [comment]
Yes - I didn't try curio, but pytest-trio works (with some annoying fixes to stop pytest-asyncio from being in the way, that's also why I'm looking up to anyio).

**Comment by agronholm** [comment]
Getting this to work right will probably require some major hacks since pytest wasn't designed for this. The code in pytest-trio is pretty complicated. If an async fixture depends on another fixture, The pytest plugin will likely have to do some dependency resolution where pytest would normally take care of things.

I need this in my own project too, but I have my plate currently full with other changes (particularly for AnyIO 2.0).

**Comment by fantix** [comment]
We're on the same page. Guess I'll stick with pytest-trio and pytest-asyncio for a bit longer, and use anyio for its adaptors. Keep up the great work! 👍

**Comment by agronholm** [comment]
I have a plan for this: run async fixtures in a separate thread where the event loop will be kept running. The tricky part is figuring out when to start and stop the event loop. Each back-end needs one thread each. This might also make it feasible to allow class/module/package level async fixtures.

**Comment by agronholm** [comment]
I figured out a way to handle this. Trio 0.16 added a new API for "guest mode" which makes it possible to run all three backends in the main thread without resorting to extra threads (asyncio and curio were never a problem here).

**Comment by agronholm** [comment]
I should mention, for the sake of completeness, that trio does in fact use a separate thread, but has a callback system to ensure that everything is really done in the main thread.

**Comment by agronholm** [comment]
I have an working, tested implementation of this in the v2 branch now.

**Comment by agronholm** [comment]
I just pushed the fully refactored pytest plugin to the `testrunner` branch. Feel free to check it out!
