### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by carlwgeorge** [agronholm/anyio#110]
Hello, I'm the package maintainer for python-anyio in Fedora.  Our development branch (Rawhide) has updated Python to 3.9 (pre-release versions) to get a head start on identifying issues with other Python packages.  We discovered that the anyio test suite doesn't pass on 3.9.

https://bugzilla.redhat.com/show_bug.cgi?id=1817681

Another maintainer pointed out an upstream issue that introduced `asyncio.loop.shutdown_default_executor`.

https://bugs.python.org/issue34037#msg366812

I think this means that anyio will need changes to be compatible with Python 3.9.  Here is the warning in the ["What’s New In Python 3.9" document](https://docs.python.org/dev/whatsnew/3.9.html#changes-in-the-python-api).

> asyncio.loop.shutdown_default_executor() has been added to AbstractEventLoop, meaning alternative event loops that inherit from it should have this method defined. (Contributed by Kyle Stanley in bpo-34037.)

I'm not familiar enough with the code base to implement the fix myself, I just wanted to bring it to your attention.  Once the fix is commited or submitted as a pull request, I can include the relevant commits as a patch in the Fedora package without waiting for a corresponding anyio release.

**Comment by agronholm** [comment]
The `spawn()` issue was already fixed in v1.3.0 so I'm baffled by that failure. As for the exception about `asyncio.loop.shutdown_default_executor`, that happens because asyncio broke backwards compatibility by introducing a mandatory new method which uvloop has not implemented yet.

**Comment by agronholm** [comment]
I only get 5 failures when testing against Python 3.9.0b1. Aside from the uvloop related problems, the remaining one is something I should look into.

**Comment by encukou** [comment]
I filed a Python issue to reconsider making `shutdown_default_executor` mandatory: https://bugs.python.org/issue40802

**Comment by agronholm** [comment]
I've created a ticket in uvloop: https://github.com/MagicStack/uvloop/issues/349

**Comment by agronholm** [comment]
I've release AnyIO 1.3.1 that includes this workaround.

**Comment by carlwgeorge** [comment]
Thank you for the quick fix and release.  It allowed me to update the Fedora package and clear the build failure.
