### ISSUE TITLE
it looks like some socket methods can block doing dns resolution?

### ISSUE THREAD

**Issue by njsmith** [agronholm/anyio#118]
I was just [investigating some performance issues in trio](https://github.com/python-trio/trio/issues/1595#issuecomment-643936957), and in the process noticed an issue in curio that it looks like anyio might share: anywhere you accept a socket address and pass it through to the stdlib `socket` module, the `socket` module will happily accept a hostname and then do a blocking DNS lookup. This is pretty annoying, but whaddaygonnado.

Asyncio and Trio both handle this by automatically resolving hostnames on their own, before passing them to the stdlib `socket` module. Curio doesn't seem to handle it, and I guess expects the user to pre-resolve all hostnames.

Looking at the v1 code currently, I think anyio's `bind` method does use a thread when it detects that the address has a hostname in it, but all the other methods that take addresses – `connect`, `sendto`, etc. – all pass the address through to stdlib `socket` directly, so can accidentally block doing DNS lookups.

**Comment by agronholm** [comment]
You may be right about `sendto()`, but `connect_tcp` does a DNS lookup in a thread first, and only passes raw addresses to `sock.connect()`.

**Comment by njsmith** [comment]
Oh, so `sock.connect` is a private/internal API?

**Comment by agronholm** [comment]
Yup. I'm still trying to figure out if asyncio is capable of supporting an async socket abstraction via transports and protocols, but until then, the internal Socket class is private.
