### ISSUE TITLE
[Question] Does receive_until include the delimiter?

### ISSUE THREAD

**Issue by space88man** [agronholm/anyio#120]
anyio 1.3.1:

I am testing a SocketStream line reader with `receive_until(b'\n', 1024)` but I don't seem to have the delimiter in the returned bytes.

The docs state that return value is "the bytes read, including the delimiter"

**Comment by space88man** [comment]
Ah, confusion was reading the docs for lastest but using 1.3.1.

**Comment by agronholm** [comment]
You're right – the delimiter is not included, contrary to the documentation.
