### ISSUE TITLE
[Question] Removal of create_queue, recommendation for producer/consumer workflows?

### ISSUE THREAD

**Issue by space88man** [agronholm/anyio#124]
Just ported a pet library of mine to anyio, then noticed the removal of `create_queue` which I was using.

Is there a recommendation for producer/consumer workflows (the queue contains objects rather than text/json)?

Thanks.

**Comment by agronholm** [comment]
I haven't pushed that commit yet but queues will be replaced in v2.0 with memory object streams (similar to memory channels in trio).

**Comment by agronholm** [comment]
I've just committed the implementation of memory object streams to master. Have fun!
