### ISSUE TITLE
Nested finalisation handled differently from Trio

### ISSUE THREAD

**Issue by mjwestcott** [agronholm/anyio#126]
Thank you for this excellent library. I noticed that tasks created in nested groups do not appear to be finalised when their group is cancelled. The tests below illustrate the problem. The Trio version passes.

anyio == 1.4.0
trio == 0.16.0

```python
import pytest
import anyio
import trio


@pytest.mark.anyio
async def test_anyio():
    async def subtask(finalised):
        try:
            await anyio.sleep(999)
        finally:
            # *** Not called ***
            await finalised.set()

    async def subgroup(finalised):
        async with anyio.create_task_group() as tg:
            await tg.spawn(subtask, finalised)

    async def main():
        finalised = anyio.create_event()
        async with anyio.create_task_group() as tg:
            await tg.spawn(subgroup, finalised)
            await anyio.sleep(1)
            await tg.cancel_scope.cancel()
        assert finalised.is_set()

    await main()


@pytest.mark.trio
async def test_trio():
    async def subtask(finalised):
        try:
            await trio.sleep(999)
        finally:
            finalised.set()

    async def subgroup(finalised):
        async with trio.open_nursery() as n:
            n.start_soon(subtask, finalised)

    async def main():
        finalised = trio.Event()
        async with trio.open_nursery() as n:
            n.start_soon(subgroup, finalised)
            await trio.sleep(1)
            n.cancel_scope.cancel()
        assert finalised.is_set()

    await main()
```
`FAILED test.py::test_anyio[asyncio] - assert False`

**Comment by agronholm** [comment]
I will check this out. Your timing is pretty good because I'm currently in the middle of a major push for AnyIO v2.0 and if any semantics need to be changed, this would be the perfect opportunity for that.

**Comment by agronholm** [comment]
Right now it is looking like you've found a bug. The task group in `subgroup` is in `__aexit__()` waiting for `subtask` to finish but then it receives the cancellation, leaving `subtask` running on its own.

**Comment by agronholm** [comment]
Wow – when I got a notification of this issue, I was struggling with a problem where my socket listeners were not being properly closed. As it turns out, it seems that problem and this one are one and the same! Talk about a coincidence :smile:

**Comment by mjwestcott** [comment]
That's interesting -- if `subtask` is left running, why doesn't the program sleep for 999 seconds?

**Comment by agronholm** [comment]
> That's interesting -- if subtask is left running, why doesn't the program sleep for 999 seconds?
```python3
import asyncio
async def main():
    asyncio.get_running_loop().create_task(asyncio.sleep(9999))

asyncio.run(main())
```
Does this script sleep for 999 seconds?

**Comment by mjwestcott** [comment]
I see, loose tasks are the root of all evil. Structured concurrency to the rescue!

**Comment by agronholm** [comment]
Yes, and you (and I, apparently) found a weak point in anyio's structured concurrency.

**Comment by mjwestcott** [comment]
```python
import asyncio

async def foo():
    try:
        await asyncio.sleep(999)
    finally:
        print("finalised")

async def main():
    asyncio.create_task(foo())

asyncio.run(main())
```

We're down a rabbit hole now, but I find this interesting. Although the above exits immediately, it does run the finally block.

**Comment by agronholm** [comment]
Yet if you do that with `anyio.run()`, it won't.

**Comment by mjwestcott** [comment]
Great, thanks for the prompt response.

**Comment by agronholm** [comment]
I could be persuaded to make a patch release (v1.4.1) if you're in a hurry to get this to production or something. Otherwise you can wait for v2.0 which should happen within the next 2 weeks.

**Comment by mjwestcott** [comment]
Thanks, but I can wait for v2.0. I'm building a stream processing library on top of AnyIO, still in the early stages of development.
