### ISSUE TITLE
Should we expose the user to 4-tuple IPv6 socket addresses?

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#130]
The result of `sock.getsockname()` for IPv6 sockets is a 4-tuple (address, port, flowinfo, scopeid). The last two fields are specific to IPv6. The flowinfo field is useless/deprecated and the scopeid is only meaningful for link-local addresses. The important part here is that the address field can carry a scope ID by appending it to the address with a `%` separator, like `fe80::dead:beef%1`.

Most people are not used to dealing with 4-tuple socket addresses, so maybe it would make sense to make it part of the address always. On the other hand, others might *expect* the usual behavior and get confused when they get 2-tuples instead!

**Comment by nosklo** [comment]
I like the idea of returning 2-tuples; it's a new api anyway and most use cases will just pass the tuple unchanged.
