### ISSUE TITLE
Infinite recursion in ExceptionGroup

### ISSUE THREAD

**Issue by Kinnay** [agronholm/anyio#145]
I discovered something weird. Here's a minimal example that reproduces it:
```python
import anyio

async def task():
	async with anyio.create_task_group() as tg:
		await tg.spawn(anyio.sleep, 1)
		await tg.cancel_scope.cancel()
		raise ValueError

async def main():
	async with anyio.create_task_group() as tg:
		await tg.cancel_scope.cancel()
		await task()
	
anyio.run(main)
```

With the trio backend, I get a `ValueError`, but with the asyncio and curio backends I get an infinite chain of exceptions until the recursion limit is reached.

**Comment by agronholm** [comment]
I'm not sure where the recursion is coming from. If I catch the `ValueError` on asyncio, its `__cause__` attribute is `None`.

**Comment by Kinnay** [comment]
Maybe it's the `__context__` attribute? `__cause__` is only set if you explicitly use `raise from` if I'm correct.

**Comment by agronholm** [comment]
Well, `__context__` is also None. The `__cause__` attribute is also set when you raise an exception in an `except` block.

**Comment by agronholm** [comment]
No, you were right – `__context__` does contain the exception group.
