### ISSUE TITLE
Add serializing stream wrappers

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#150]
Stream wrappers that serialize/deserialize objects passing through them. Ideal for connecting object streams with byte streams.

**Comment by smurfix** [comment]
Hmm, that's a question of "which wrapping method(s) do we support". "All of them" is a lot, besides: writing such a wrapper is quite trivial if the unpacker supports streaming.

Wouldn't this better in the documentation (one example using JSON which needs some message length / delimiter, one using msgpack which does not) with the actual code in anyio_util or something along these lines?

**Comment by agronholm** [comment]
Encoding to a bytestream could surely be implemented, but decoding might require an object stream of bytes. Anyway I'm closing this because there seems to be no pressing need for this, at least as part of the core AnyIO library,
