### ISSUE TITLE
Doctests with all possible backends

### ISSUE THREAD

**Issue by sobolevn** [agronholm/anyio#153]
Hi! 

I am using `anyio` to test our library: https://github.com/dry-python/returns
We do write a lot of unit tests in docs. So, I am wondering if it is possible to run the same way as test marked with `pytest.mark.anyio`? 

Basically, I want three test (asyncio, trio, curio) runs for a single doctest. 
Example: https://github.com/dry-python/returns/blob/master/returns/future.py#L47-L61

**Comment by agronholm** [comment]
If you have doctests enabled right now, what happens when you run them?

**Comment by sobolevn** [comment]
Here's the example test:

```python
# ex.py
async def example():
    """
    Example doctest.

    >>> import anyio
    >>> assert anyio.run(example) == 1

    """
    return 1
```

Let's run it:

```
» pytest ex.py
================================ test session starts =================================
platform darwin -- Python 3.8.0, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
Using --randomly-seed=1363777128
rootdir: /Users/sobolev/Documents/github/returns, inifile: setup.cfg
plugins: anyio-1.4.0, curio-1.2
collected 1 item                                                                     

ex.py .    

================================= 1 passed in 2.24s ==================================
```

**Comment by agronholm** [comment]
I don't know how that could work. AFAIK there is no concept of async doctests. The only way to run doctests on all backends is to include a `for` loop that iterates through the return value of `anyio.get_all_backends()` (v2.0) or `anyio.BACKENDS` (v1.0).

**Comment by agronholm** [comment]
I cannot help but to conclude that this is impossible to achieve and so I'm closing the ticket.

**Comment by sobolevn** [comment]
There's actually some thing we can try:
- `.getfixture` can try to resolve parametrized fixture for `anyio`: https://docs.pytest.org/en/stable/doctest.html#using-fixtures
- It can potentially be possibly to use this fixture https://docs.pytest.org/en/stable/doctest.html#doctest-namespace-fixture with `params=` and providing all existing backends there

**Comment by agronholm** [comment]
Where would you use `.getfixture()` then? I'm not at all convinced this can be done, but if you can come up with a working PR, I'm willing to review it.
