### ISSUE TITLE
TaskGroup Hangs If Coroutine Raises Without Awaiting

### ISSUE THREAD

**Issue by rmorshea** [agronholm/anyio#155]
The first scenario exits immediately in error (as expected):

```python
import asyncio
from anyio import run, create_task_group

async def await_then_raise_error():
    await asyncio.sleep(0)
    raise ValueError("asd")

async def main():
    async with create_task_group() as g:
        await g.spawn(await_then_raise_error)
        await g.spawn(asyncio.sleep, 3)

run(main)
```

However if we `raise_without_awaiting` and don't `await asyncio.sleep(0)` before the error, the `TaskGroup` blocks until `asyncio.sleep(3)` is complete. In this scenario, if the blocking task were to run forever, the `TaskGroup` would hang indefinitely:

```python
import asyncio
from anyio import run, create_task_group

async def raise_without_awaiting():
    raise ValueError("asd")

async def main():
    async with create_task_group() as g:
        await g.spawn(raise_without_awaiting)
        await g.spawn(asyncio.sleep, 3)

run(main)
```

Interestingly, just changing the order in which the tasks get spawn impacts whether or not the `TaskGroup` exits immediately. Putting the failing task after the `asyncio.sleep(3)` allows the group to exit without blocking:

```python
import asyncio
from anyio import run, create_task_group

async def raise_without_awaiting():
    raise ValueError("asd")

async def main():
    async with create_task_group() as g:
        await g.spawn(asyncio.sleep, 3)
        await g.spawn(raise_without_awaiting)

run(main)
```

**Comment by agronholm** [comment]
What version of anyio did you try this on? On 2.0.0b2 it worked without issues.

**Comment by rmorshea** [comment]
Ahh! Of course, I'm on `1.3.1`. Didn't think to upgrade. Will close once I try it out on the latest version.

**Comment by rmorshea** [comment]
Can confirm >=1.4.0 fixes this issue.
