### ISSUE TITLE
timeout discovery

### ISSUE THREAD

**Issue by smurfix** [agronholm/anyio#16]
Trio has a `current_effective_deadline()` method, which is very useful for interfacing with libraries that require explicit timeout parameters. AnyIO should provide that.

**Comment by agronholm** [comment]
Do you have an example of its usage in practice?

**Comment by smurfix** [comment]
For instance, I'm using it in an AMQP client-server library to pass the timeout to the broker and to the service. Thus the message will be rejected if it isn't answered in time, and the server can itself time out the request if it takes too long.

**Comment by agronholm** [comment]
I'm not sure I still understand. Do you have any actual code you can show me?

**Comment by smurfix** [comment]
Real code:

        props = dict(reply_to = self.read_queue, correlation_id = corr)

        timeout = trio.current_effective_deadline()-trio.current_time()
        if timeout <= 0:
            await trio.sleep(math.inf) # cancellation point
            raise RuntimeError("We should not be here")
        if timeout < math.inf:
            props['expiration'] = int(timeout*1000)

        await self.chan.basic_publish(exchange_name=self.exchange,
                                      routing_key=self.routing_key,
                                      properties=props,
                                      payload=msg)

**Comment by agronholm** [comment]
Thanks, I'll get back to this when I have more time to work on anyio.

**Comment by agronholm** [comment]
I must first get #8 done before I can tackle this one.
