### ISSUE TITLE
Integrate with the exceptiongroup library

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#17]
The current implementation of exception groups in anyio is quite poor. This has been left alone because of the emerging [exceptiongroup](https://github.com/python-trio/exceptiongroup) library which should provide a much better implementation. Once it's been released, we should add a dependency on it and remove our built-in implementation.

**Comment by agronholm** [comment]
I removed this from the 1.0.0 target because the exceptiongroup library is nowhere near release ready. It needs plenty of work to get there.

**Comment by smurfix** [comment]
This effort should be restarted, because as it is anyio is no longer compatible with Trio master. 
```
______________________________________ test_multi_error_host[trio] ______________________________________
anyio/_backends/_trio.py:121: in __aexit__
    return await self._nursery_manager.__aexit__(exc_type, exc_val, exc_tb)
../trio/trio/_core/_run.py:725: in __aexit__
    raise combined_error_from_nursery
E   trio.MultiError: Exception('host'), Exception('child')

During handling of the above exception, another exception occurred:
tests/test_taskgroups.py:205: in test_multi_error_host
    raise Exception('host')
anyio/_backends/_trio.py:123: in __aexit__
    raise TrioExceptionGroup(exc.exceptions) from None
../trio/trio/_core/_multierror.py:184: in __init__
    assert len(exceptions) == 1 and exceptions[0] is self
E   AssertionError
```

**Comment by agronholm** [comment]
The library isn't ready yet, and I've committed a much simpler fix in master now.

**Comment by agronholm** [comment]
What I could do at this point is to modify AnyIO's ExceptionGroup API to match [PEP 654](https://www.python.org/dev/peps/pep-0654/).

**Comment by agronholm** [comment]
I just tried, and the problem is that trio's `MultiError` is not compatible with this spec (it just takes a bunch of exceptions but not an error message). Any code that needs to raise an exception group must actually raise a `MultiError` in trio or else it will not be handled correctly.

**Comment by agronholm** [comment]
Actually, I already had in place a workaround where a trio-specific ExceptionGroup inherits from MultiError. I still need to improve my understanding of how `__new__()` and `__init__()` work before I can get this working.

**Comment by agronholm** [comment]
Got it now – all tests pass. I'll polish this later.
