### ISSUE TITLE
[asyncio] socket.send() raised exception.

### ISSUE THREAD

**Issue by mgrrx** [agronholm/anyio#171]
I get this very weird print on the console in my application:
"socket.send() raised exception."

The program essentially looks like the following

```
def handle(client):
    async with client:
        async for msg in receive_stream:
            await client.send(msg)

async with await anyio.create_tcp_listener(...) as listener:
    listener.serve(handle)
```

It looks to me as if there is an issue when the client disconnects:

https://github.com/agronholm/anyio/blob/b5dffbe7ccf28afd97d43113ae9e98fca61c6627/src/anyio/_backends/_asyncio.py#L764-L772

I "fixed" it locally by checking the state of the transport and the the stream. I don't know why I don't get this RuntimeError.

```
diff --git a/src/anyio/_backends/_asyncio.py b/src/anyio/_backends/_asyncio.py
index 4b4e6c2..65c0cbe 100644
--- a/src/anyio/_backends/_asyncio.py
+++ b/src/anyio/_backends/_asyncio.py
@@ -761,6 +761,11 @@ class SocketStream(abc.SocketStream):
     async def send(self, item: bytes) -> None:
         with self._send_guard:
             await checkpoint()
+            if self._closed:
+                raise ClosedResourceError
+            elif self._transport.is_closing():
+                raise BrokenResourceError
+
             try:
                 self._transport.write(item)
             except RuntimeError as exc:
```

I'm using anyio 2.0.2 on Ubuntu 20.04 (Python 3.8.5)

**Comment by agronholm** [comment]
Can you build a working example for me that reproduces the problem?

**Comment by mgrrx** [comment]
sorry for coming back to this issue that late. Here my example:

server.py
```
from anyio import create_tcp_listener, run

async def handle(client):
    async with client:
        while True:
            await client.send(b"Hello")

async def main():
    listener = await create_tcp_listener(local_port=1234)
    await listener.serve(handle)

run(main)

```

client.py
```
from anyio import connect_tcp, run
from anyio.streams.buffered import BufferedByteReceiveStream

async def main():
    async with await connect_tcp("localhost", 1234) as client:
        stream = BufferedByteReceiveStream(client)
        while True:
            response = await stream.receive_exactly(5)
            print(response)

run(main)

```

Steps to reproduce

1. python3 server.py
2. python3 client.py
3. Ctrl-C client.py
4. server.py prints a wall of

```
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
```

**Comment by agronholm** [comment]
I cannot reproduce this output.

**Comment by agronholm** [comment]
This happens on asyncio. On curio and trio, `BrokenPipeError` is raised. The asyncio error message does not come from AnyIO, however.

The `BrokenPipeError` should be wrapped on the other backends as a `BrokenResourceError`.

**Comment by agronholm** [comment]
Interestingly this happens only with vanilla asyncio and not with uvloop.

**Comment by agronholm** [comment]
Would you mind reviewing the PR?
