### ISSUE TITLE
documentation of TextReceiveStream is confusing

### ISSUE THREAD

**Issue by wearpants** [agronholm/anyio#176]
It says: `Receives from the wrapped stream until the given delimiter is found, and then returns the string (without the delimiter).` but there is no use of a delimiter in that class.

I'm trying to implement decoding of new line separated JSON, a la #150 (so bytes -> text -> JSON), not quite sure how to use this class in that.

**Comment by agronholm** [comment]
The in-development implementation of `TextReceiveStream` required delimiters but then I discovered incremental decoders in the `codecs` module and apparently forgot to update the docstring. I don't suggest using `TextReceiveStream` for this purpose, but instead using an `ObjectReceiveStream` that wraps a `ByteReceiveStream` and deserializes objects using some custom logic based on when you know a complete JSON object has been received.

I will fix the docstring.
