### ISSUE TITLE
bidirectional buffered stream?

### ISSUE THREAD

**Issue by joernheissler** [agronholm/anyio#178]
Hello,
since the API rewrite, it looks like I need to use a `BufferedByteReceiveStream` to use `receive_exactly`. But the class is only for receiving, not writing.
Is it by intention that I need to carry around two objects if I want both `receive_exactly` and `send`?

Thanks!

**Comment by smurfix** [comment]
You can combine the two back into one object. `anyio.streams.stapled.StapledObjectStream`.
