### ISSUE TITLE
Please drop support for Curio

### ISSUE THREAD

**Issue by dabeaz** [agronholm/anyio#185]
One of the most fundamental concepts in software architecture is the idea of "separation of concerns."   There are many ways that this can be achieved.  For example, via abstraction layers,  composition of objects, and so forth.   However, another possible approach involves the separation of environments.  For example, protected versus user mode on CPUs or kernel vs. user space in operating systems.    The separation of environments, in this case, async versus sync, is the fundamental architecture of the Curio project.   It effects everything about how Curio works and the nature of its programming API. 

This separation is the major difference between asyncio and Curio.   Moreover, the whole concept was one of the first things abandoned by the Trio project.  So, now with Anyio trying to provide a common programming interface to all of these libraries, it should come as no great surprise to find that Curio is a primary source of friction.  

Curio was not created to keep doing things in the "standard way."   Nor was it created to simply be some kind of swappable back-end engine for arbitrary async code.   Anyone who tries to use it in that way will only get a very muddled idea of what Curio is actually about and how it is supposed to work.   For that reason, I'd kindly ask that you drop your support for it.

Curio is not going anywhere.  If people like it and want to use it, I would encourage them to engage more directly with the project and its architectural model, as opposed to trying to wish away its differences with an abstraction layer.

**Comment by agronholm** [comment]
Well, if nothing else, this makes it easier to merge #182.
