### ISSUE TITLE
`BrokenResourceError` raised by `MemoryObjectStream.send` after successful send

### ISSUE THREAD

**Issue by tomwatson1024** [agronholm/anyio#186]
I'm unsure if this is working as designed - it's slightly unclear in the docs. Running the following:

```python
import anyio


async def demo() -> None:
    send_stream, receive_stream = anyio.create_memory_object_stream()

    async def send() -> None:
        async with send_stream:
            await send_stream.send(None)
            print("sent")

    async def receive() -> None:
        async with receive_stream:
            await receive_stream.receive()
            print("received")

    async with anyio.create_task_group() as task_group:
        await task_group.spawn(send)
        await task_group.spawn(receive)

```

prints only

```
received
```

before raising `anyio.BrokenResourceError`. It seems like we're falling afoul of https://github.com/agronholm/anyio/blob/master/src/anyio/streams/memory.py#L161. My guess for what's happening is:

- we enter the context of the send stream and attempt the send;
- we first attempt `send_nowait`, which fails as the `receive` coroutine has not yet called `receive_stream.receive()`;
- we create the send event and await on it, suspending the `send` coroutine;
- the `receive` coroutine is scheduled, receives the item, and closes `receive_stream` without the `send` coroutine being scheduled;
- the `send` coroutine resumes, notices that no receive channels are open, and raises.

I would've expected either:
- no exception to be raised, with an exception raised if another send was attempted;
- some kind of end-of-stream exception.

The `BrokenResourceError` seems inconsistent with the fact that the item has actually been sent.

Tested on 2.0.2 and current master (83a0cbd), on all three event loops.

**Comment by agronholm** [comment]
I will investigate and get to this before the next release.
