### ISSUE TITLE
curio task groups eat errors

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/anyio#19]
```py
import anyio


async def err():
    print("This definitely runs!")
    raise AttributeError("fewsfwsefwf")


async def main():
    async with anyio.create_task_group() as tg:
        await tg.spawn(err)


anyio.run(main, backend="curio")
```

Output in my PyCharm:

```
This definitely runs!

Process finished with exit code 0
```

**Comment by agronholm** [comment]
This apparently only happens with the git version of curio. It's unclear if anyio does something wrong or if there's a bug in curio. Either way, this works normally with curio 0.9.

**Comment by agronholm** [comment]
Apparently the necessary code was commented out in the git versio of curio. I'm closing this as invalid for now. If it resurfaces in the next release of curio, then please open a new issue.
