### ISSUE TITLE
Link to documentation on github page

### ISSUE THREAD

**Issue by uSpike** [agronholm/anyio#190]
I think it'd help to add a link to https://anyio.readthedocs.io/en/stable/ on the github page.  Easy enough to find with a quick search, but it'd help.  Doesn't need to be in the README necessarily.

**Comment by agronholm** [comment]
There's a "docs" button at the top:
![image](https://user-images.githubusercontent.com/130003/106357644-fde16b00-630f-11eb-99e8-15f4403571fb.png)
But I guess I can add it as text too.

**Comment by uSpike** [comment]
Agh you're right.  Sorry for the noise.  I couldn't find it on the page by searching text for "doc".
