### ISSUE TITLE
setup.py leads to egg with version 0.0.0

### ISSUE THREAD

**Issue by edrozenberg** [agronholm/anyio#197]
`Python 3.9.1`

`https://files.pythonhosted.org/packages/46/86/710a9c49c3c52d151321d16123db4e486d9048253696090d84a92f1973bc/anyio-2.1.0.tar.gz`

Doing:

`python3 setup.py install --root=/usr/local/src/anyio/pkg/`

Results:
```
...
...
running egg_info
creating src/anyio.egg-info
writing src/anyio.egg-info/PKG-INFO
writing dependency_links to src/anyio.egg-info/dependency_links.txt
writing entry points to src/anyio.egg-info/entry_points.txt
writing requirements to src/anyio.egg-info/requires.txt
writing top-level names to src/anyio.egg-info/top_level.txt
writing manifest file 'src/anyio.egg-info/SOURCES.txt'
reading manifest file 'src/anyio.egg-info/SOURCES.txt'
writing manifest file 'src/anyio.egg-info/SOURCES.txt'
removing '/usr/local/src/anyio/pkg/usr/lib64/python3.9/site-packages/anyio-0.0.0-py3.9.egg-info' (and everything under it)
Copying src/anyio.egg-info to /usr/local/src/anyio/pkg/usr/lib64/python3.9/site-packages/anyio-0.0.0-py3.9.egg-info
running install_scripts
```

Not sure why the resulting dist gets version 0.0.0. Does not happen with other python packages.

**Comment by agronholm** [comment]
It's because anyio uses setuptools_scm to retrieve the version number. Use `pip install` instead.
Having `setup_requires = setuptools_scm` in `setup.cfg` would probably fix this.

**Comment by agronholm** [comment]
Also, is there a reason why you're not installing the wheel instead of the source package?

**Comment by edrozenberg** [comment]
I'm using `python3 setup.py install --root=targetdir` in order to build packages for deployment to multiple servers.

Today I redid exactly the same steps as previously and it worked fine to create output with the correct version. Not sure what changed since yesterday, oh well.
