### ISSUE TITLE
Need a finalise helper

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/anyio#20]
Curio complains about async generators: 
```
RuntimeError: Async generator with async finalization must be wrapped by
async with curio.meta.finalize(agen) as agen:
    async for n in agen:
         ...
```

Unfortunately, this can't be done without hard-depending on curio.

**Comment by agronholm** [comment]
Why couldn't I implement something like `async with aclosing()` as an abstraction?

**Comment by Fuyukai** [comment]
That's basically what the issue is for. Something that would satisfy curio and either be a no-op or the same functionality everywhere else.

**Comment by Fuyukai** [comment]
You can't do what the error message suggests without hard-depending. Bad phrasing on my part.

**Comment by agronholm** [comment]
I'm mystified by this ticket now. I investigated and doesn't look like curio calls `is_safe_generator()` on its own. I certainly don't run into this while running the test suite. Explain please.

**Comment by agronholm** [comment]
It looks like that your curious library pretty more or less forces its use. Couldn't you just...not do that?

**Comment by Fuyukai** [comment]
curio has an async generator hook: https://github.com/dabeaz/curio/blob/master/curio/meta.py#L400

which is installed by this function; https://github.com/dabeaz/curio/blob/ed00d710ebf60963360853b23b66c63fc6592a66/curio/meta.py#L36

which the kernel then uses here: https://github.com/dabeaz/curio/blob/master/curio/kernel.py#L143

so it's definitely called

**Comment by agronholm** [comment]
What I cannot figure out is why I haven't run into this despite running unguarded async generators on curio in my test suite. I need to look deeper.
