### ISSUE TITLE
Add TTY streams

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#212]
It would be nice to have streams that read from or write to TTYs. It could check with `os.isatty()` if the given file handle is a TTY. Trio has `FDStream` which could be helpful here, as a reference if nothing else. Windows support for this feature could be tricky.

**Comment by agronholm** [comment]
Asynchronously reading TTYs on all platforms may be too complicated. The thread-based file streams, introduced in #209, could be sufficient.

**Comment by jonathanslenders** [comment]
Currently, I'm in a situations where I'd have to wrap an ``os.pipe()`` an an async way. I think having `FDStream` would be ideal for this. I'm not sure right now what would be the best alternative. I don't see a `from_fd()` in the file streams.
