### ISSUE TITLE
Implement worker processes for CPU parallelism

### ISSUE THREAD

**Issue by richardsheridan** [agronholm/anyio#219]
Not all applications are consistently CPU-bound. To obtain CPU parallelism of arbitrary python code, it is currently necessary to use worker subprocesses, the easiest method being to build on top of `multiprocessing` or `concurrent.futures`.

Other IO libraries provide a shortcut for this. `asyncio` provides [`loop.run_in_executor`](https://github.com/python/cpython/blob/6c4c11763fad106e43cdcfdbe3bd33ea2765a13f/Lib/asyncio/base_events.py#L800-L814) which when combined with a `ProcessPoolExecutor` instance does the job. `curio` provides [`run_in_process`](https://github.com/dabeaz/curio/blob/bb4efc43175d454e1a55d415184db3ce0542b34b/curio/workers.py#L182-L216) which wraps `multiprocessing.Process`.  `trio` does not provide this feature but lists it as a [missing piece](https://github.com/python-trio/trio/issues/5).

I wrote [`trio-parallel`](https://github.com/richardsheridan/trio-parallel) to provide that missing piece, but the code works just as well as a [component of `trio` itself](https://github.com/python-trio/trio/pull/1781). @agronholm mentioned in [Gitter](https://gitter.im/python-trio/general?at=6032e8ca7ba8124e547e236c) that he would like to see a similar feature in `anyio`. I don't really fancy maintaining another library but if you would like to design an API, I can squeeze the internals of `trio-parallel` to fit it and provide a PR to `anyio`.

**Comment by agronholm** [comment]
There are far many more moving pieces in a subprocess based executor which is why neither trio or anyio have picked up this feature. If it doesn't add an unreasonable maintenance burden, I'd be willing to consider such an addition (for v3.1, at the earliest).

**Comment by richardsheridan** [comment]
Personally, I don't think the maintenance will be too high, but I'm sure I have less expertise to judge that than others. 

For a first try at an API, what about copying the `run_sync_in_worker_thread` interface and placing it in say `anyio._core._workers`?

**Comment by agronholm** [comment]
What exactly would that do? Spawn a new subprocess, run the callable and terminate the process?

**Comment by richardsheridan** [comment]
It mimics the trio thread cache exactly. There is a global cache of worker processes and they are spawned on-demand when there are no idle workers available. They do work and, if they survive, they are returned to the cache. In the cache they have a 10 minute timeout waiting for more work before they exit on their own. The cache is global and is shared between parallel and sequential `trio.run` calls.

**Comment by agronholm** [comment]
Ok, I can't think of any good counterarguments so I'm convinced.

**Comment by agronholm** [comment]
Progress on this is unexpectedly rapid so I'm trying to get this into 3.0 already.

**Comment by richardsheridan** [comment]
> Progress on this is unexpectedly rapid so I'm trying to get this into 3.0 already.

Nice, looking forward to seeing it!

**Comment by agronholm** [comment]
Implemented in #240.
