### ISSUE TITLE
asyncio: Multiple consecutive cancel scopes cause a crash

### ISSUE THREAD

**Issue by smurfix** [agronholm/anyio#22]
The problem is that asyncio does not run callbacks immediately when a Future is done, so `CancelScope._task_done` is queued twice for the same task, which fails the second time around.

```
import asyncio
import anyio

async def main():
    async with anyio.open_cancel_scope() as scope:
        pass
    async with anyio.open_cancel_scope() as scope:
        pass
    await asyncio.sleep(0.1)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

**Comment by agronholm** [comment]
Opening a cancel scope should not add a callback for the host task, so this is something that needs to be fixed. It may even necessitate a larger refactoring inside the asyncio backend.

**Comment by smurfix** [comment]
No refactoring necessary. ;-)

**Comment by agronholm** [comment]
Well yes it is because cancel scopes in asyncio and curio, as they are now, cannot support the use cases needed for feature parity with trio.

**Comment by smurfix** [comment]
OK, that's correct, but not because of *this* bug.

**Comment by agronholm** [comment]
Indeed. Cancel scopes and their interaction with task groups is probably the hardest thing here to wrap one's head around. I've been trying to sort out the larger issue with this and so far I've made little progress. But I *will* get there ;)
