### ISSUE TITLE
Implement `CancelScope.cancelled_caught`

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#257]
The `CancelScope` implementation on AnyIO mirrors that of trio 1:1, except for this particular property.

Relevant trio documentation [here](https://trio.readthedocs.io/en/stable/reference-core.html#trio.CancelScope.cancelled_caught).

**Comment by agronholm** [comment]
@johnzeringue do you intend to work on this any further?

**Comment by johnzeringue** [comment]
> @johnzeringue do you intend to work on this any further?

I probably don't have the time to continue working on it. I was unable to find a way to make this work.

**Comment by agronholm** [comment]
Closing in favor of #591, as it introduces a more useful property, `deadline_reached`.
