### ISSUE TITLE
AssertionError in test_run_sync_from_thread_pooling on aarch64

### ISSUE THREAD

**Issue by mweinelt** [agronholm/anyio#265]
Running the 3.0.0 testsuite on aarch64 we got a (sadly not so reliable reproducible) test failure in `TestRunAsyncFromThread.test_run_sync_from_thread_pooling`.

```
___________ TestRunAsyncFromThread.test_run_sync_from_thread_pooling ___________
tests/test_from_thread.py:56: in test_run_sync_from_thread_pooling
    assert threading.active_count() == initial_count
E   assert 3 == 2
E    +  where 3 = <function active_count at 0xfffff73afa60>()
E    +    where <function active_count at 0xfffff73afa60> = threading.active_count
======================== 1 failed, 711 passed in 38.40s ========================
```

python3.8 https://gist.github.com/da7b04eb064b04100e446516096e8dd6
python3.9 https://gist.github.com/73e9cfe1b6f0b54b9db362012846e2b6

**Comment by agronholm** [comment]
I've seen this happen before but I have not been able to reproduce it locally.

**Comment by agronholm** [comment]
The assertion is flawed. I will fix the test to be reliable.
