### ISSUE TITLE
Using aiofiles for async file IO

### ISSUE THREAD

**Issue by Tinche** [agronholm/anyio#266]
Hello,

I have a PR open against my aiofiles library adding anyio support (by a third party): https://github.com/Tinche/aiofiles/pull/97

However I see that anyio already has support for async file IO. Would you be interested in dropping your code and depending on aiofiles if this is merged?

If not, I don't really see the point of merging it in, since the logic is already implemented here.

**Comment by agronholm** [comment]
Async file I/O is a core part of AnyIO functionality. I have no intention of dropping it, as it would add a dependency with no benfefits.  To be frank, there is little aiofiles can offer over AnyIO, but if you merge that PR, it gains trio support, and support for any future anyio backend (twisted?).

**Comment by Tinche** [comment]
Okie dokie!

**Comment by Tinche** [comment]
Forgot to add, thank you for your insight.
