### ISSUE TITLE
make CancelScope.shield mutable

### ISSUE THREAD

**Issue by belm0** [agronholm/anyio#274]
it should be possible to change the `shield` property of a CancelScope instance

**Comment by agronholm** [comment]
The tricky part is making this work properly with the asyncio "native cancellation" support added late in the 3.0 cycle.

**Comment by belm0** [comment]
I didn't see anything obvious in the asyncio code that would not work if the `_shield` attribute was mutated.   Is there specific code or a commit you could refer to?

**Comment by agronholm** [comment]
When a cancel scope is cancelled on asyncio, it starts a callback that tries to keep cancelling all the related tasks. If all the remaining tasks are currently within a shielded scope, this callback is adjourned until the cancel scope is exited. With the mutability of `shield`, we need to restart this callback if the task becomes eligible for cancellation again but without exiting the formerly shielded scope.

This is the callback I'm referring to: https://github.com/agronholm/anyio/blob/master/src/anyio/_backends/_asyncio.py#L347

**Comment by belm0** [comment]
(`_deliver_cancellation()` can be rescheduled on every scheduler tick.  Can't this consume a large proportion of CPU if the ticks are short and there are many tasks in the cancel scope?  Ideally the code would be event-driven somehow.)
