### ISSUE TITLE
Is @asynccontextmanager exempt from the "do not yield in an async generator" rule?

### ISSUE THREAD

**Issue by frederikaalund** [agronholm/anyio#282]
Sorry if this is the wrong place to post a question like this. Feel free to redirect me to the proper channels (if they exist).

---

In the [anyio docs](https://anyio.readthedocs.io/en/stable/cancellation.html#avoiding-cancel-scope-stack-corruption) I read that:

> However, in certain situations, cancel scope stack corruption might still occur:
>  * [...]
>  * Yielding in an async generator while enclosed in a cancel scope

Furthermore:

> Therefore, do NOT do this:
>
>     async def some_generator():
>     async with create_task_group() as tg:
>         tg.start_soon(foo)
>         yield
>

I want to do *exactly* that but within an `@asynccontextmanager`. Is this okay? I know that Trio has a [similar rule with an exemption for `@asynccontextmanager`](https://trio.readthedocs.io/en/stable/reference-core.html#cancel-scopes-and-nurseries).

**Comment by graingert** [comment]
@frederikaalund yes in an `@asynccontextmanager` is fine

**Comment by frederikaalund** [comment]
Great, thanks for the clarification. :+1:

**Comment by graingert** [comment]
> Sorry if this is the wrong place to post a question like this. Feel free to redirect me to the proper channels (if they exist).

@frederikaalund https://gitter.im/python-trio/AnyIO I think is the preferred channel for questions
