### ISSUE TITLE
Nested cancellation scopes fail to eat "their" exceptions

### ISSUE THREAD

**Issue by smurfix** [agronholm/anyio#29]
This code does not print "Done". It should.

```
import anyio

scope = None
async def scoped():
    async with anyio.open_cancel_scope() as sc:
        async with anyio.open_cancel_scope() as sc2:
            global scope
            scope = sc
            await anyio.sleep(2)

async def check():
    async with anyio.create_task_group() as tg:
        await tg.spawn(scoped)
        await anyio.sleep(1)
        await scope.cancel()
        await anyio.sleep(1)
        print("Done.")

anyio.run(check)
```

This patch fixes the immediate problem, but it's fragile. A "real" solution needs to store the cancel scope that's responsible for the cancellation in the exception, like Trio does.

```
diff --git a/anyio/_backends/asyncio.py b/anyio/_backends/asyncio.py
index 5f470d0..34a364d 100644
--- a/anyio/_backends/asyncio.py
+++ b/anyio/_backends/asyncio.py
@@ -221,7 +221,7 @@ async def open_cancel_scope(deadline: float = float('inf'), shield: bool = False
     except asyncio.CancelledError as exc:
         if timeout_expired:
             raise TimeoutError().with_traceback(exc.__traceback__) from None
-        else:
+        elif not scope._cancel_called:
             raise
     finally:
         if timeout_task:
```

**Comment by agronholm** [comment]
Thanks. Can you write a script which would fail despite this patch?

**Comment by smurfix** [comment]
I can (probably) write a script that uses this issue to detect whether it's running on Trio or not. I wouldn't classify that as a failure, however, because both scopes do get cancelled and which one got cancelled first should not matter in a "correct" program.

Doing that work is a whole lot less important than getting a 1.0 version out there …

**Comment by agronholm** [comment]
You don't have to write the script – just tell me how you would detect the difference. I aim for maximum compatibility with trio where possible so this is of great interest to me.

**Comment by agronholm** [comment]
Thanks again. I'll ponder this some more today.
