### ISSUE TITLE
Pylint error when iterating a stream: Non-iterable value is used in an iterating context (not-an-iterable)

### ISSUE THREAD

**Issue by flyte** [agronholm/anyio#297]
Given the following code:

```python
import anyio

async def read():
    _, s_rx = anyio.create_memory_object_stream()
    async for _ in s_rx:
        pass
```

Pylint gives the following error:

```
pylint-issue.py:5:19: E1133: Non-iterable value s_rx is used in an iterating context (not-an-iterable)
```

**Comment by agronholm** [comment]
What do you think I should do about it?

**Comment by flyte** [comment]
I don't know? Maybe it's to do with this bug https://github.com/PyCQA/pylint/issues/3233

**Comment by agronholm** [comment]
Well, it seems like a bug in pylint so maybe this one should be closed?

**Comment by flyte** [comment]
Just thought you might want to know about an issue affecting your software. Didn't know it was a pylint issue to begin with. Never mind.
