### ISSUE TITLE
starting a blocking portal permenantly sets the process global event loop policy in a thread unsafe way (when a policy is passed)

### ISSUE THREAD

**Issue by graingert** [agronholm/anyio#305]
also applies to `anyio.run` but that's mainly run from the main thread with `sys.exit(anyio.run(amain))` so is safer

Note: this issue was previously about the default behavior of opting into the uvloop policy

**Comment by graingert** [comment]
this is particularly problematic when a ChildWatcher() instance is holding state there

**Comment by agronholm** [comment]
I can think of a couple ways to fix this:

1. Default `use_uvloop` to `False`
2. Have `start_blocking_portal()` detect asyncio and pass `uvloop=False` explicitly

I'm kinda partial to the first option.

**Comment by graingert** [comment]
I think copying the source of asyncio.run and using:

```
asyncio.set_event_loop((policy or asyncio.get_event_loop_policy)().new_event_loop()
```
Is the way to go

**Comment by agronholm** [comment]
Yeah, we have already copied the source of `asyncio.run()` for py3.6, but we could start using that for all Python versions. I think that also enables us to drop the coroutine wrapper for the root task.

**Comment by graingert** [comment]
Also I think the `policy` kwarg should be deprecated in favour of a `loop_factory` kwarg

**Comment by agronholm** [comment]
What's the benefit of that?

**Comment by graingert** [comment]
It would make it clear that anyio doesn't touch the child_watcher

**Comment by graingert** [comment]
So it turns out uvloop needs the uvloop policy child watcher

**Comment by graingert** [comment]
https://github.com/MagicStack/uvloop/blob/c808a663b297bb2aee745523c277d6fafecebbeb/uvloop/loop.pyx#L2862-L2879

**Comment by agronholm** [comment]
Given this constraint, maybe we should 1) deprecate the `policy` and `uvloop` asyncio options and set `uvloop=False` by default?

**Comment by graingert** [comment]
As part of the GELectomy (removing the per thread global eventloop from asyncio.get_event_loop() ) asyncio.runners now provides a policy free way to select the eventloop implementation. anyio should use this on 3.11 and consider backporting the implementation for other python versions

**Comment by graingert** [comment]
> https://github.com/MagicStack/uvloop/blob/c808a663b297bb2aee745523c277d6fafecebbeb/uvloop/loop.pyx#L2862-L2879

Turns out this constraint doesn't apply when used with the ThreadedChildWatcher on (default on 3.8+) or if uvloop is run in an off main thread so I think this can be revisited.

**Comment by agronholm** [comment]
It's not clear to me what AnyIO should do on py < 3.11.

**Comment by graingert** [comment]
anyio can backport the `asyncio.Runner` code and provide a `loop_factory` backend option for asyncio
