### ISSUE TITLE
Document expectations on the `ByteReceiveStream.receive()` method.

### ISSUE THREAD

**Issue by lovelydinosaur** [agronholm/anyio#308]
It's unclear if [the `ByteReceiveStream.receive()` method](https://anyio.readthedocs.io/en/stable/api.html#anyio.abc.ByteReceiveStream) can be expected to possibly return `b""`.

If it *might* return `b""` then when performing a read-some-data-or-timeout, the user needs to consider that as a possible case, and always loop until we *do* have some data to return.

If it *cannot/should not* return `b""` then that'll need to be an explicitly documented expectation.

Prompted by https://github.com/encode/httpcore/issues/357, https://github.com/encode/httpcore/pull/358

**Comment by smurfix** [comment]
Well … it's a bytestream so there are no boundaries you can depend on anyway.

IMHO the reader should be robust and just shrug its metaphorical shoulders and repeat if it gets a zero-length buffer for whatever reason. In most code I've seen, a zero-byte read is just an expensive no-op.

Thus I propose to document that yes it can be empty but so what? We have an EOFError exception: a reader that regards an empty read to be an end-of-file is buggy IMHO.

**Comment by agronholm** [comment]
I guess this was never defined for the high level interface. The built-in implementations never return `b""` because the OS signals EOF that way. I think we should document it so that it shouldn't return `b""`.
