### ISSUE TITLE
UNIX server socket files are not automatically removed when closed

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#32]
UNIX server socket files should be automatically deleted when the socket is closed, but this is not currently being done.

**Comment by agronholm** [comment]
I wrote this little snippet for asyncio:
```python3
import asyncio


async def main():
    async def callback(reader, writer):
        pass

    server = await asyncio.start_unix_server(callback, '/tmp/socket.sock')
    await asyncio.sleep(1)
    print('closing')
    server.close()


asyncio.get_event_loop().run_until_complete(main())
```
It did not remove the socket either, so anyio is not doing anything horribly wrong by not removing the socket.

**Comment by daa** [comment]
I have to say that ``asyncio`` removes the socket on crieating unix server: https://github.com/python/cpython/blob/94d2c8df1a7657015a2fcdb4c4d43392f91f8348/Lib/asyncio/unix_events.py#L283
While it's not a problem for client's code to remove stale socket themselves ``anyio`` behavior differs from ``asyncio``, not sure for ``curio`` and ``trio``.

**Comment by agronholm** [comment]
Trio at least does not currently remove it: https://github.com/python-trio/trio/issues/279

So it is not clear what the user expectation is here.

**Comment by agronholm** [comment]
Ok, I think it's reasonable for AnyIO to unlink the existing socket file before `bind()`.
