### ISSUE TITLE
Cancellation semantics on asyncio and curio differ slightly from trio's

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#34]
The following script produces different results on the trio backend vs the asyncio and curio ones:

```python3
import anyio

scope = None


async def scoped():
    global scope
    async with anyio.open_cancel_scope() as scope:
        async with anyio.open_cancel_scope() as sc2:
            try:
                await scope.cancel()
                # await anyio.sleep(2)
            except BaseException as exc:
                await sc2.cancel()
                raise

        print("You should not see this.")


async def check():
    async with anyio.create_task_group() as tg:
        await tg.spawn(scoped)
        await anyio.sleep(1)
        await scope.cancel()
        await anyio.sleep(1)

anyio.run(scoped, backend='trio')
```
To fix this, we would need some way to track which cancellation exception was triggered by which cancel scope but currently we do not have the means for this.

**Comment by smurfix** [comment]
Umm … why should we not see this? Rewriting the test for (the current version of) native Trio does exactly the same thing.

**Comment by agronholm** [comment]
I didn't write this code, I just copied it off of another issue here. Uncomment the `await anyio.sleep(2)` line and you will see the problem.

**Comment by smurfix** [comment]
Ah. Right.

I added a commit to my PR which fixes this.

**Comment by agronholm** [comment]
Be aware that I am also working on my own set of changes to fix these issues.

**Comment by smurfix** [comment]
I don't have a problem with ditching my solution for yours.
Assuming that yours is better, of course. ;-)

**Comment by agronholm** [comment]
This was fixed by the latest batch of patches.
