### ISSUE TITLE
Link to docs?

### ISSUE THREAD

**Issue by codypiersall** [agronholm/anyio#35]
Someone pointed out this library to me, and it looks like it may be really helpful.  I see that you have docs, and it looks like they should be on Read the Docs, but my Googling didn't turn anything up: (YMMV) https://www.google.com/search?q=site%3Areadthedocs.org+python+anyio&rlz=1C1CHBF_enUS720US720&oq=site%3Areadthedocs.org+python+anyio&aqs=chrome..69i57j69i58.6112j0j7&sourceid=chrome&ie=UTF-8

If this library has published docs, it would be great if you could link to them in the README.

**Comment by agronholm** [comment]
There are documentation links, although only one of them is visible on Github:
![doclinks](https://user-images.githubusercontent.com/130003/48758798-ed51f680-eca9-11e8-9830-2b06ebbd145c.png)

**Comment by agronholm** [comment]
I guess you didn't try RTD's own search function either? Simply entering "anyio" in their search box gives you one result which is this project's documentation.

**Comment by codypiersall** [comment]
Ah yeah, I didn't try the search bar on readthedocs, and my eyes skimmed right over the docs button.  I tried searching Google with lots of apparently wrong combinations, and did a Ctrl+F search on the README page for `doc` but since the button is an image and not text it wasn't highlighted.  I even visited the PyPI page you linked to, but didn't see the Documentation link on the side.  I think I've become over reliant on Google.  How embarrassing for me!
