### ISSUE TITLE
3.3.0: `build_sphinx` fails

### ISSUE THREAD

**Issue by kloczek** [agronholm/anyio#354]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.1.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/anyio-3.3.0/docs/conf.py", line 17, in <module>
    v = pkg_resources.get_distribution('anyio').parsed_version
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'anyio' distribution was not found and is required by the application
```
I'm not 100% but looks like it is because source code of the module is in `src/`

**Comment by agronholm** [comment]
`tox -e docs` works fine, as do the [RTD builds](https://readthedocs.org/projects/anyio/builds/). What you're missing is a virtualenv where you have the `docs` extra installed.

**Comment by kloczek** [comment]
It would be need to use tox if source code would be not under `src/`.
KISS principle ..
Nevertheless hopefully cases like that will be solved in sphinx code.

**Comment by agronholm** [comment]
The RTD builds are not using tox, and they still work fine. You need to have the project installed (preferably in editable mode) to make the docs build correctly.

**Comment by kloczek** [comment]
This issue is not abut that `buil_sphins` is not able to find `anyio` module but `pkg_resources.DistributionNotFound`. so it is not related to location of the module source code under `src/`
I have no idea what kind of error it is. Dou know maybe what exactly it is?

Using `tox` for me is not viable solution because it has hardcoded generate html and I need man pages roff format.

**Comment by agronholm** [comment]
That error is caused by the `pkg_resources` trying to find the installed AnyIO distribution to get its version number.

Try this (in a fresh virtualenv):
```bash
pip install -e .[doc]
python setup.py build_sphinx
```
