### ISSUE TITLE
`ExceptionGroup.exceptions` does not show up in documentation

### ISSUE THREAD

**Issue by SyntaxColoring** [agronholm/anyio#356]
It seems like the `exceptions` attribute of the `ExceptionGroup` class is intended to be publicly documented. See https://github.com/agronholm/anyio/issues/141#issuecomment-667722214 and commit https://github.com/agronholm/anyio/commit/cd4d0bc39c822e534a1dac6be6c2111a46e8eb8d.

However, despite this doc comment being in the source:

https://github.com/agronholm/anyio/blob/bd8d1a19dd04062e1eb4ec916230ceaf0ccf36e3/src/anyio/_core/_exceptions.py#L49-L50

Nothing shows up on https://anyio.readthedocs.io/en/stable/api.html#anyio.ExceptionGroup.

![Screen Shot 2021-08-10 at 12 30 28 PM](https://user-images.githubusercontent.com/3236864/128897458-50119fed-f988-4773-b08f-9a14d69dbcfd.png)

I tried building the docs locally from source and got the same problem. I can't figure out why. Maybe some kind of Sphinx misconfiguration?

**Comment by SyntaxColoring** [comment]
I've only skimmed this, but maybe https://github.com/sphinx-doc/sphinx/issues/4534 is relevant?

**Comment by agronholm** [comment]
The related PR has been merged, so it doesn't seem that way. I'll look into fixing this manually. Thanks for pointing it out.
