### ISSUE TITLE
thread startup function

### ISSUE THREAD

**Issue by cfal** [agronholm/anyio#361]
I'm using some python code that runs various functions via asyncio.to_thread.run_sync(). I'd like it so that any function that is passed to run_sync can use some preconfigured objects available in thread-local storage. Is there a recommended way to do that or is it possible to make a change to do so?

I considered subclassing Thread to run something when it begins; looking at _backends/_asyncio.py (which is the backend currently used in our system), the locally declared WorkerThread class is started and tasks are immediately added via `worker.queue.put_nowait`. One possibility is monkey-patching threading.Thread, but that seems like a last resort.

Thanks!

**Comment by agronholm** [comment]
Couldn't your code just check if the thread-local stuff is in place and initialize it if it's not?

**Comment by cfal** [comment]
Thanks for the quick response! Yeah, we considered doing this and it's definitely an option for us, albeit with a bit of refactoring :) We were hesitant to have to add an additional preamble to every task we send; creating the thread local data requires some context/state that tasks currently aren't aware of and that we were hoping to keep decoupled.

Since there seems to be multiple solutions and since this seems to be fairly specific to our usecase, I'll just close this issue.
