### ISSUE TITLE
Prevent users from subclass `anyio.Lock`

### ISSUE THREAD

**Issue by Bluenix2** [agronholm/anyio#372]
## Description

Recently I migrated a project to using anyio. Previously I had subclassed `asyncio.Lock` to add some additional functionality but changing this to `anyio.Lock` proved to be troublesome.

The exact subclass of the subclass does not matter too much, eventually it tried to call `self.release()` in `__aexit__` which resulted in the following short traceback:

```python
 File "...\rest\locks.py", line 51, in __aexit__
    self.release()
  File "...\venv\lib\site-packages\anyio\_core\_synchronization.py", line 158, in release
    if self._waiters:
AttributeError: 'RateLimit' object has no attribute '_waiters'
```

## Proposed Solution

Python allows several ways to do this, but the end result should be that we warn the user perhaps through a RuntimeError, that subclassing this class is extremely troublesome.

**Comment by Bluenix2** [comment]
Actually, it was `anyio.Event` that was troublesome with the `__new__` trick. I am not sure why I got this error but I assume it is not a bug with the library with that in mind. The specific implementation of my subclass can be seen here:

```python
class RateLimit(anyio.Lock):
    """An API rate limit lock."""

    deferred: bool

    event: anyio.Event

    def __init__(self, event: anyio.Event) -> None:
        self.deferred = False
        self.event = event

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> None:
        if not self.deferred:
            self.release()

    def defer(self) -> None:
        """Defer the lock from releasing during the next __aexit__.
        This is used to release the lock later on, while still exiting.
        """
        self.deferred = True

    def acquire_nowait(self) -> None:
        """Acquire the lock, without blocking."""
        self.deferred = False  # Reset the value

        return super().acquire_nowait()
```

*Note: I am aware of the race-condition possible with the implementation of `acquire_nowait()`.*

**Comment by agronholm** [comment]
Not sure what you wanted here, since AnyIO's internals rely on the ability to subclass `anyio.Event`. What you are doing above looks OK.
