### ISSUE TITLE
When `standard_compatible=False` is set `.receive()` should `raise EndOfStream` for SSL EOF errors.

### ISSUE THREAD

**Issue by lovelydinosaur** [agronholm/anyio#379]
Prompted by https://github.com/encode/httpx/issues/1896 and https://github.com/encode/httpcore/issues/396.

Currently `standard_compatible=False` allows SSL streams to fail to unwrap properly without raising errors, which is great, and the expected behaviour.

It should *also* ensure that `receive()` operations that result in an `SSLEOFError` return `b""` rather than [raising a `BrokenResourceError`.](https://github.com/agronholm/anyio/blob/c0002bfbcbe83d69ea394cf7c8c9318c62426b26/src/anyio/streams/tls.py#L120-L121)

See [the equivalent in Trio](https://github.com/python-trio/trio/blob/0c2998f642d119f23a41e52d8b018fea1e1e1c28/trio/_ssl.py#L680-L690).

**Comment by tomchristie** [comment]
Ah right, `EndOfStream`, yes.

I'd forgotten that `anyio` uses that, rather than the `b""` sentinel value. (Reasonably enough)

**Comment by agronholm** [comment]
I'm really perplexed by this. The stdlib docs say:
> The parameter suppress_ragged_eofs specifies how the SSLSocket.recv() method should signal unexpected EOF from the other end of the connection. If specified as True (the default), it returns a normal EOF (an empty bytes object) in response to unexpected EOF errors raised from the underlying socket; if False, it will raise the exceptions back to the caller.

In AnyIO, `standard_compatible=False` means `suppress_ragged_eofs=True`. How is it then than an `SSLEOFError` could be raised with this set?

**Comment by tomchristie** [comment]
> In AnyIO, standard_compatible=False means suppress_ragged_eofs=True

Where are you setting `suppress_ragged_eofs=True`?

I see `standard_compatible` being used [to control the unwrap logic](https://github.com/agronholm/anyio/blob/c0002bfbcbe83d69ea394cf7c8c9318c62426b26/src/anyio/streams/tls.py#L142), but it's not used elsewhere as far as I can see?

Trio deals with it directly at the `receive_some` level, rather than through passing some additional arguments to `wrap_bio` (Which I don't think supports the `suppress_ragged_eofs` argument anyways?)

**Comment by agronholm** [comment]
Ah, my bad, I misremembered. That `suppress_ragged_eofs` was only an option passed to `wrap_socket`. Low level implementations such as AnyIO's `TLSStream` have to handle those things manually.

I have a fix for this, just need to add a test. Frankly I don't remember where `ssl.SSLSysCallError` comes from (I'm catching that too) but I'm handling that the same way as `SSLEOFError`.

**Comment by agronholm** [comment]
This fix is in v3.3.4 now.

**Comment by tomchristie** [comment]
Fabulous. 🙏
