### ISSUE TITLE
Cancel scope stack corruption when combining @asynccontextmanager and wrap_async_context_manager

### ISSUE THREAD

**Issue by jonathanslenders** [agronholm/anyio#381]
Consider the following snippet:

```python
from contextlib import asynccontextmanager
from anyio import create_task_group, start_blocking_portal

async def failing_func():
    0 / 0

@asynccontextmanager
async def run_in_context():
    async with create_task_group() as tg:
        tg.start_soon(failing_func)
        yield


def main():
    with start_blocking_portal(backend="asyncio") as portal:
        with portal.wrap_async_context_manager(run_in_context()):
            pass

main()
```

Executing this always causes "RuntimeError: Attempted to exit a cancel scope that isn't the current tasks's current cancel scope".

I wonder whether or not that's expected.

According to the docs [0], using a task group within an ``asynccontextmanager`` is fine in "most cases", but it's not clear to me what is "most cases" exactly. I would expect the exception to propagate nicely.

It seems to work fine when taking the blocking portal out of the equation. This nicely propagates the exception:
```python
import asyncio
from contextlib import asynccontextmanager
from anyio import create_task_group, start_blocking_portal

async def failing_func():
    0 / 0

@asynccontextmanager
async def run_in_context():
    async with create_task_group() as tg:
        tg.start_soon(failing_func)
        yield


async def main():
    async with run_in_context():
        pass
asyncio.run(main())
```

Is this expected?

[0] https://anyio.readthedocs.io/en/stable/cancellation.html?highlight=corruption#avoiding-cancel-scope-stack-corruption

**Comment by agronholm** [comment]
Looking at the code further, I see that what I said before is not quite true. The problem only occurs when there is an exception. If two separate tasks were used to run the CM, it would raise an error even without an exception happening in the task code.

**Comment by jonathanslenders** [comment]
@agronholm: I have a possible fix in the linked pull request.
