### ISSUE TITLE
make wait_socket_{readable,writable}() accept a file descriptor

### ISSUE THREAD

**Issue by dlax** [agronholm/anyio#386]
Both asyncio's `add_reader/writer()` and trio's `wait_{readable,writable}()` accept a file descriptor argument along with any object with a `fileno()` method (not just a `socket.socket`).
Can we make anyio support a similar interface?
(Perhaps following trio's names and drop the *_socket* part from functions name?)

Happy to work on a PR if agreed.

**Comment by agronholm** [comment]
I don't really encourage the use of these functions as they don't work on Windows. What use case did you have in mind?

**Comment by dlax** [comment]
I'm trying to see if psycopg could work with anyio, see https://github.com/psycopg/psycopg/issues/29 and discussions in https://github.com/psycopg/psycopg2/issues/1057. (I am aware of the limitations.)
Basically, we have a `PGconn` object wrapping a libpq connection and we need to wait for the underlying file descriptor to become read- or write-ready (https://www.postgresql.org/docs/current/libpq-async.html).

**Comment by agronholm** [comment]
What would you pass to these functions if not a `socket.socket` object?

**Comment by agronholm** [comment]
Does `PGconn` have a `fileno()` method?

**Comment by dlax** [comment]
I'd pass a `fd: int`, which trio and asyncio functions already accept.
`PGconn` has a `socket` property (mapping `PQsocket` accessor), this returns a file descriptor number.

**Comment by dlax** [comment]
In fact `socket.socket` is already too restrictive; probably a `HasFileno` protocol as defined in typeshed (https://github.com/python/typeshed/blob/994b69ef8f18e76689daca3947879c3d7f76173e/stdlib/_typeshed/__init__.pyi#L149) would be enough.

**Comment by agronholm** [comment]
`HasFileno` was too broad for functions designed to accept only sockets (they do work with selector loops on Windows, just not with proactor loops).

**Comment by agronholm** [comment]
So as not to change the scope of the functions, can we easily check that a file descriptor refers to a socket and not another type of file?

**Comment by agronholm** [comment]
We could let the back-end do that but I would like to keep the resulting exception consistent.

**Comment by dlax** [comment]
I don't know in general.
For the libpq connection, I tried that `socket.socket(fileno=pgconn.socket)` but this fails with `OSError: [Errno 9] Bad file descriptor`.

**Comment by agronholm** [comment]
Could you not just use `socket.fromfd()`?

**Comment by dlax** [comment]
`socket.fromfd()` works better; thank you!
