### ISSUE TITLE
Expose curio-like tcp_server_socket / unix_server_socket API

### ISSUE THREAD

**Issue by standy66** [agronholm/anyio#40]
Curio separates socket construction logic into separate *_server_socket [synchronous functions](https://curio.readthedocs.io/en/latest/reference.html#curio.tcp_server_socket). This gives ability to start listening in synchronous context, then do something with the socket, e.g. get actual bound port number when port=0 was passed to auto select, and only after that start accepting connections in asynchronous context.

This is the use case that may be beneficial in unit tests, for example, consider the following scenario:
1. Create a socket without any specific port, bind it and listen (sync)
2. Get bound port number
3. Spin up client thread / process with the port number obtained in part 2 (sync)
4. Start accepting incoming connections (async)

I think it would be a great addition and this is really easy to implement.

**Comment by agronholm** [comment]
How exactly does this differ from what anyio offers? In [this test](https://github.com/agronholm/anyio/blob/master/tests/test_networking.py#L23-L29), for example, I do something just like that.

**Comment by standy66** [comment]
The difference is in the context. In your example socket is created and bound is async context. From there the only way to pass it back to sync context is to use threads and thread synchronization primitives. You cannot "yield" from anyio.run. I think the approach where socket is created in plain old blocking way is more versatile. But I understand that this is debatable.

**Comment by agronholm** [comment]
Perhaps I do not understand the use case. Can you elaborate on that? With an (pseudocode if needed) example if possible.

**Comment by agronholm** [comment]
It's been over three months without any feedback, so I'm closing this.
