### ISSUE TITLE
Pass kwargs to run_sync?

### ISSUE THREAD

**Issue by davidbrochart** [agronholm/anyio#414]
It would be nice if [to_process.run_sync](https://anyio.readthedocs.io/en/stable/api.html#anyio.to_process.run_sync), [to_thread.run_sync](https://anyio.readthedocs.io/en/stable/api.html#anyio.to_thread.run_sync),  and [from_thread.run_sync](https://anyio.readthedocs.io/en/stable/api.html#anyio.from_thread.run_sync) could accept kwargs.
Is there a reason for not supporting it, or was it just not implemented until now?

**Comment by uSpike** [comment]
See discussion in https://github.com/agronholm/anyio/pull/403, https://github.com/python-trio/trio/issues/470

**Comment by davidbrochart** [comment]
Thanks @uSpike! So do you recommend using a lambda?
```python
run_sync(lambda: my_func('foo', kwarg='bar'))
```

**Comment by uSpike** [comment]
Yep that's the best way in my opinion, otherwise `functools.partial`.

**Comment by davidbrochart** [comment]
Thanks!
