### ISSUE TITLE
Support passing file objects and None as std* arguments of `open_process()` and `run_process()`

### ISSUE THREAD

**Issue by jwodder** [agronholm/anyio#419]
Would it be possible for the `stdin`, `stdout`, and `stderr` arguments of `open_process()` and `run_process()` to be expanded to accept both `None` (to inherit the file descriptor from the parent) and (synchronous) file-like objects (to read from/write to the given file)?  Based on their documentation, both [asyncio](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.subprocess_exec) and [trio](https://trio.readthedocs.io/en/v0.19.0/reference-io.html#trio.open_process) seem to support such arguments.

**Comment by agronholm** [comment]
I'm willing to review a PR to that effect.
