### ISSUE TITLE
Tests not compatible with pytest 7

### ISSUE THREAD

**Issue by jwodder** [agronholm/anyio#420]
I just cloned the repository and ran `tox`, and pytest's test collection failed with `ImportError: cannot import name 'Testdir' from '_pytest.pytester'`.  Setting the pytest "test" dependency to `pytest ~= 6.0` resolves the error, though mypy is still complaining `tests/test_pytest_plugin.py:2: error: Module "_pytest.pytester" has no attribute "Testdir"` (Also, a bunch of socket tests fail on my machine with "Can't assign requested address", but that seems like a macOS overzealous security thing that I can just live with for now.)

**Comment by agronholm** [comment]
You may want to rebase your changes to 4.0-dev. That branch should also work with pytest 7. I'm not planning on adding any more features to the 3.x branch.

**Comment by jwodder** [comment]
@agronholm Nope, that branch fails with pytest 7, too.

**Comment by agronholm** [comment]
It seems I had forgotten to push that commit. Fixed via 58fcb0c495a847e2f6627ec07fe07f4dd6ae9cd9.
