### ISSUE TITLE
Thread race condition in _eventloop.get_asynclib() (with fix)

### ISSUE THREAD

**Issue by danielrobbins** [agronholm/anyio#425]
I have a threading Web spider using httpx that is triggering a race condition in anyio/_core/_eventloop.py's get_asynclib() function. This race can be triggered if you have a lot of threads trying to initialize their own asyncio event loop and initializing httpx all at once. It happens intermittently -- sometimes we don't trigger the race, sometimes we do. When we do, the threads catch get_asynclib() mid-initialization and certain attributes that should be present are not available. I am using anyio 3.5.0, httpx 0.22.0 and python3.7.

[httpx-exception.txt](https://github.com/agronholm/anyio/files/8212004/httpx-exception.txt)

An ugly but functioning patch which I can confirm resolves the issue is below:

[get_asynclib_thread_fix.patch.txt](https://github.com/agronholm/anyio/files/8212005/get_asynclib_thread_fix.patch.txt)

In my test patch, I made the lock cover essentially the entire get_asynclib() call -- it could potentially be made tighter, with questionable benefit -- not sure.

**Comment by agronholm** [comment]
I'm very hesitant to add locking to `get_asynclib()` which is "hot" code. I'll take a look at this and see if I can find a better solution.

**Comment by agronholm** [comment]
I do question the use case though – why would you run multiple event loops?

**Comment by danielrobbins** [comment]
If you are using threads, each thread needs its own event loop. So if you ever use ThreadPoolExecutor, and you want to use async inside, each one needs its own event loop. That is the use case in my code. In my case, each thread is performing network operations so to use httpx, I require an event loop to exist for the lifetime of the thread.

**Comment by laker-93** [comment]
I wonder if this problem would still occur if you were to use `ProcessPoolExecutor` with 'spawn' context, rather than threads. That way each event loop would be running in a separate memory space and your event loops would be isolated. Therefore, there would be no chance of threads racing against each other due to shared state. I think separate processes is the correct solution here in any case, to give you true parallelism.

**Comment by graingert** [comment]
Rather than use sys.modules you can import into a global and return that

**Comment by gpsa** [comment]
Would that be possible to have this same fix added to `anyio 3.x`?

**Comment by agronholm** [comment]
I don't plan on updating v3.x anymore. Why are you still using it?

**Comment by gpsa** [comment]
We received a snyk alert about it and upon trying to upgrade it, I noticed both FasAPI and httpx depend on it and don't have upgrades for 4.x. I'd say just because the impact on big libs is huge.

**Comment by agronholm** [comment]
Both FastAPI and httpx work with AnyIO 4.x. What was the problem?

**Comment by gpsa** [comment]
I figured it out. `httpx` version constraint was preventing the use of `anyio 4.x`. 
After updating it to the latest version, it allowed for all the cascading of updates to happen on both FastAPI and (specially) Starlette, then it upgraded anyio to 4.x

**Comment by agronholm** [comment]
Well, good that you figured it out. I'm closing this as it was resolved by the linked PR.
