### ISSUE TITLE
Pre-release status makes it hard to install the package

### ISSUE THREAD

**Issue by nonsleepr** [agronholm/anyio#43]
I'm trying to install `asks` with `pipenv` and getting an error:
```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches anyio
Skipped pre-versions: 1.0.0a1, 1.0.0a1, 1.0.0a2, 1.0.0a2, 1.0.0b1, 1.0.0b1, 1.0.0b2, 1.0.0b2
There are incompatible versions in the resolved dependencies.
```

**Comment by agronholm** [comment]
This is a problem with pipenv. Pip itself has no problem installing a pre-release if it's the only option. What did you mean for me to do about this anyway? I'm not ready to make a final release until some serious outstanding issues have been resolved.

As an aside, I didn't realize the official branch of asks already depended on anyio.

**Comment by nonsleepr** [comment]
Yeah, `pipenv` is quite opinionated and makes (incorrect?) assumptions about versions. On the other hand, `anyio` doesn't have any release versions at all. Why start with `1.0.0` if there's not release yet? Maybe releasing the current version as `0.1.0` now would solve some problems?

Apparently, `asks` switched to `anyio` [two weeks ago](https://github.com/theelous3/asks/pull/114).

I've created theelous3/asks#117 in an attempt to address the issue on `asks` side.

**Comment by agronholm** [comment]
Issue #37 has been blocking progress for many weeks. I wanted to properly understand and deal with the problem rather than just accept the first offered solution. I've been working on it locally and have implemented several improvements along the way.
I've also created issues for the two other tasks I want to sort out before the 1.0.0 final release.

**Comment by madsmtm** [comment]
As @nonsleepr noted, can't you just make a `0.1.0`, or even a `0.0.1` release? That signals that the project is still in development, and does not guarantee any API stability, but it'll still allow people to install it using `pip`/`pipenv`. I'll put a link to [Semantic Versioning](https://semver.org/), in case you're not really familiar with it.

**Comment by agronholm** [comment]
> As @nonsleepr noted, can't you just make a 0.1.0, or even a 0.0.1 release?

If I were making the first release, this would be acceptable, but I've already made several v1.0.0 pre-releases which would compare as higher than 0.1.0, making the versioning illogical. But I promise to speed up the development and try to get v1.0.0 final out this weekend or next week at the latest.

> I'll put a link to Semantic Versioning, in case you're not really familiar with it.

As stated in the [version history](https://github.com/agronholm/anyio/blob/master/docs/versionhistory.rst), anyio already follows semantic versioning.

**Comment by madsmtm** [comment]
Whoops, sorry, didn't catch that document 😉. And you're right, I didn't think the versioning fully through, of course there's problems with releasing an earlier version than the current one, though perhaps it's possible? I haven't tried it, so I don't know how PyPI/`pip` handles it?

But anyhow, no need to stress and make hasty decisions, make the release when you feel the project is ready! 😊

**Comment by nonsleepr** [comment]
I feel bad that you have to make promises on the timeline.

Looks like the problem I stumbled on is caused by me using pre-release version of `asks`. The most recent published to PyPI version of Asks to date (`2.2.1`) uses `multio` and I used the version from GitHub (with the fixes I need), so I should have used `pipenv install --pre` to install all my dependencies.

Anyway. Take your time with the final release.

**Comment by agronholm** [comment]
I was able to make some progress on the cancellation semantics front (my refactored curio code had a problem). Anyio is my current pet project and it's blocking all the other cool things I want to do, hence my dedication.

**Comment by agronholm** [comment]
So, good news and bad news. I made some major progress and was able to refactor the cancellation system, along with implementing one of two last remaining 1.0 final features. The bad news is that by chance I discovered a problem (#46) with the new cancellation implementation. I'm hopeful that I can address the problem this weekend, but I will not release 1.0 final before it's taken care of.

**Comment by agronholm** [comment]
Ok, I've now fixed all the cancellation bugs I could find.

**Comment by agronholm** [comment]
I know it's over an hour past my self imposed deadline, but I've now done everything I wanted to do for v1.0.0 final. However, due to the extensive refactoring I had to do I wasn't yet comfortable putting out a final release. Thus, I've released v1.0.0rc1. I hope you're not too disappointed.

**Comment by agronholm** [comment]
I just made another RC release which contains **tons** of fixes and enhancements. The only thing holding me back from a final release now is that apparently two asyncio tests are failing on Windows. I cannot work on those problems before I get back home from PyCon due to the lack of a Windows machine.

**Comment by agronholm** [comment]
1.0 final is out now.
