### ISSUE TITLE
Number of exceptions in `ExceptionGroup` differs between trio and asyncio

### ISSUE THREAD

**Issue by valgarf** [agronholm/anyio#432]
Example reproducing the issue:

```python
import anyio
import sys

async def raise_runtime():
    try:
        await anyio.sleep(999)
    except anyio.get_cancelled_exc_class():
        raise RuntimeError()

async def exc_group():
    with anyio.move_on_after(1):
        try:
            async with anyio.create_task_group() as tg:
                ### Variant 1
                tg.start_soon(anyio.sleep, 999)
                tg.start_soon(anyio.sleep, 999)
                await anyio.sleep(999)
                ### Variant 2
                # await raise_runtime()
                ### Variant 3
                # tg.start_soon(anyio.sleep, 999)
                # await raise_runtime()
        except anyio.get_cancelled_exc_class():
            print("Cancelled")
        except:
            print(sys.exc_info())


if __name__ == "__main__":
    print("--- trio ---")
    anyio.run(exc_group, backend="trio")
    print("--- asyncio ---")
    anyio.run(exc_group, backend="asyncio")
```

Running this yields

```
--- trio ---
(<class 'anyio._backends._trio.ExceptionGroup'>, <ExceptionGroup: Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <traceback object at 0x7f1a0efc3180>)
--- asyncio ---
Cancelled
```
I expected the asyncio behavior - when cancelling a task group I would prefer to get a single `Cancelled` exception if no other exception was thrown. More importantly, I really expected the event loops to produce similar results.

There are also differences for the other variants in the example above.
Variant 2 prints:
```
--- trio ---
(<class 'anyio._backends._trio.ExceptionGroup'>, <ExceptionGroup: RuntimeError(), Cancelled()>, <traceback object at 0x7f00833dbbc0>)
--- asyncio ---
(<class 'RuntimeError'>, RuntimeError(), <traceback object at 0x7f008338ae00>)
```
Variant 3 prints:
 ```
--- trio ---
(<class 'anyio._backends._trio.ExceptionGroup'>, <ExceptionGroup: RuntimeError(), Cancelled(), Cancelled()>, <traceback object at 0x7f40e32b5e00>)
--- asyncio ---
(<class 'anyio._backends._asyncio.ExceptionGroup'>, <ExceptionGroup: RuntimeError(), CancelledError()>, <traceback object at 0x7f40e326d300>)
```

It seems the trio version always has one Cancelled exception more than the asyncio version.

I tried:
 - python 3.8.1 and anyio 3.5.0
 - python 3.10.4 and anyio 3.5.0
 - python 3.10.4 and anyio 3.4.0
 - python 3.10.4 and anyio 3.3.4
 - python 3.10.4 and current master (anyio-3.5.1.dev2+geac5293)

With identical results.

**Comment by agronholm** [comment]
Has this actually caused practical problems for you?

**Comment by agronholm** [comment]
I think the logic in trio for this is that it separates the cancellation of the host task from the cancellation from the outer scope (`move_on_after()`). I don't really see how this would become a practical problem though.

**Comment by agronholm** [comment]
Looking further into this matter, I found a worrying case:
```
    with CancelScope() as outer_scope:
        async with anyio.create_task_group():
            outer_scope.cancel()

        pytest.fail("Should not get here")
```
This fails on asyncio but passes on trio. I will need to rectify this in v4.0.

**Comment by agronholm** [comment]
It occurred to me that, if there are no tasks to wait on, `TaskGroup.__aexit__()` never hits a checkpoint on asyncio, thus no exception bubbles out of the method.
