### ISSUE TITLE
Should closing receive stream remove waiting senders?

### ISSUE THREAD

**Issue by mbrancato** [agronholm/anyio#440]
Currently, when `MemoryObjectReceiveStream.close()` is called, it completes the `asyncio.Event` for the senders, this should allow any senders awaiting the Event to continue.

https://github.com/agronholm/anyio/blob/48efdec45e70a833cc939c1d2752f24e29d1bf0b/src/anyio/streams/memory.py#L142-L145

But it does not remove the sender Event objects from the `MemoryObjectStreamState`. This appears to lead to `BrokenResourceErrors` in `MemoryObjectSendStream.send()` as they have not been removed from the dictionary, but they were completed by calling `event.set()`. 

https://github.com/agronholm/anyio/blob/48efdec45e70a833cc939c1d2752f24e29d1bf0b/src/anyio/streams/memory.py#L220-L221

This appears to at least happen when using `async with` on an `MemoryObjectReceiveStream` object.

Is this expected behavior when `MemoryObjectReceiveStream.close()` is called? To prevent raising an exception, what better way would there be beside using an async context manager on the `MemoryObjectReceiveStream` object?

Just to note, I'm tracking this down from its use in Starlette where we periodically see this exception raised.

**Comment by agronholm** [comment]
Sorry for not noticing this before!
> Is this expected behavior when MemoryObjectReceiveStream.close() is called?

Yes, as is documented [here](https://anyio.readthedocs.io/en/stable/api.html#anyio.streams.memory.MemoryObjectSendStream.send_nowait). The docstring for the `send()` method was inherited from the superclass and should probably be overridden here.

>To prevent raising an exception, what better way would there be beside using an async context manager on the MemoryObjectReceiveStream object?

The producer end should be closed first. It's an error to send an object when nobody is ever going to receive it.
