### ISSUE TITLE
Datagram streams on Unix sockets

### ISSUE THREAD

**Issue by jhominal** [agronholm/anyio#445]
I was trying to implement an asynchronous version of `SysLogHandler` using `anyio`, and I got stuck on the issue that the current `Stream` APIs do not handle datagram unix sockets.

I would propose adding the following APIs to `anyio`:

```python
class UnixDatagramSocket(anyio.abc.UnreliableObjectStream[Tuple[bytes, str]], anyio.abc._sockets._SocketProvider):
    async def sendto(data, path): ...

class ConnectedUnixDatagramSocket(anyio.abc.UnreliableObjectStream[bytes], anyio.abc._sockets._SocketProvider): ...

async def create_unix_datagram_socket(*, local_path: str) -> UnixDatagramSocket: ...

async def create_connected_unix_datagram_socket(remote_path: str, *, local_path: str) -> ConnectedDatagramSocket: ...
```

From my preliminary analysis, adding these APIs to `anyio` does not look like it would be too onerous, and I would be happy to submit a PR if you have any interest in such a feature.

I also wonder if you would find it useful/relevant to define `DatagramSocket[T]` and `ConnectedDatagramSocket` types in `anyio`, which would be common bases for `UnixDatagramSocket`/`UDPSocket` and `ConnectedUnixDatagramSocket`/`ConnectedUDPSocket`?

**Comment by agronholm** [comment]
I am interested in having this feature, but the latter change (the new datagram socket interfaces) should be added in their own PR.

**Comment by jhominal** [comment]
Just as a heads up, I have also prepared a [commit](https://github.com/jhominal/anyio/commit/4a0f0f2f49105c37c61a6daa58db90c9fdc834be) that defines base types `DatagramSocket` and `ConnectedDatagramSocket`, which I will put in a PR if and when #446 is merged.

**Comment by agronholm** [comment]
What is the reason you want to add these extra base types?
