### ISSUE TITLE
Guard against concurrent read/write from/to streams

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#45]
Right now there is nothing blocking multiple tasks from reading from or writing to streams. Each stream should know if there's already a task performing either of those operations and either raise an exception or block the operation. Looking at trio should yield the answer on which action to take then.

**Comment by smurfix** [comment]
Trio raises an exception when writing in parallel, by way of a simple `ConflictDetector` context manager. Reading in parallel works (one task gets the data and the others block), so either wrap the read in a lock to be safe/consistent, or simply leave it to the runtime.
