### ISSUE TITLE
support for anyio.start_background_task

### ISSUE THREAD

**Issue by 4n1qz5skwv** [agronholm/anyio#457]
**an example pseudo code:**

```python
import anyio


async def do_few_things_and_email(client_id):
    await send_email()
    await anyio.sleep(60)
    await delete_all_traces()


async def main():
    await send_text('all ready')
    await anyio.start_background_task(do_few_things_and_email, client_id)
    await send_text('you will soon get an email')


anyio.run(main)

```

**Some libraries that has this feature:**
https://pgjones.gitlab.io/quart/how_to_guides/background_tasks.html
https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.start_background_task
https://fastapi.tiangolo.com/tutorial/background-tasks/

**function example:**
```python
anyio.to_background.run_sync()
anyio.to_background.run_async()
```

**Comment by uSpike** [comment]
This seems antithetical to structured concurrency.  Your code could be written as:

```python
import anyio


async def do_few_things_and_email(client_id):
    await send_email()
    await anyio.sleep(60)
    await delete_all_traces()


async def main():
    await send_text('all ready')
    async with anyio.create_task_group() as task_group:
        task_group.start_soon(do_few_things_and_email, client_id)
        await send_text('you will soon get an email')


anyio.run(main)

**Comment by uSpike** [comment]
> Or have to drag that task group all around the app and build whole app inside that task group.

> Currently using apschedular for this task.

I'm curious how these differ?  Either you need to pass around your scheduler, or you need to reference a parent task group.

Anyio is mostly implementing the Trio API (or very similar), and I don't think that there would be a desire to add functionality such as this to Anyio unless it were first added to Trio.  If you feel strongly about this feature then I'd suggest you open a feature request in https://github.com/python-trio/trio

**Comment by agronholm** [comment]
The question becomes: who is responsible for handling the exception raised by that task? On asyncio, you can just do `task = asyncio.create_task(do_something())` but that will not affect anything else in the app if the task crashes. Something should react to the exception. On trio, you can launch a system task, but those will crash the entire app if they raise exceptions.

**Comment by agronholm** [comment]
As @uSpike said, the ability to create tasks that nobody is responsible for is antithetic to structured concurrency which AnyIO is trying to push. This sort of thing is best handled by the app providing a task group that other tasks can then use to start these one-off background tasks.

If you're using asyncio exclusively, you could just use `asyncio.create_task()` if you don't care about structured concurrency. But since this feature would be contrary to the goals of this project, I'm closing this issue.
