### ISSUE TITLE
Would it make sense to make CancelScope._timeout_expired public?

### ISSUE THREAD

**Issue by alegonz** [agronholm/anyio#461]
I'm a situation where I'd like to know whether the scope cancelled was cancelled by either calling `.cancel()` or by the expiration of the deadline, and take a different action in each case. Kinda something like this.

```python
async with anyio.create_task_group() as task_group:
    @task_group.start_soon
    async def do_stuff():
        # ... do stuff ...
        # something happened that requires to cancel immediately
        task_group.cancel_scope.cancel()
    async def keep_alive():
        # ... check some condition periodically ...
        while True:
            if await wait_for_some_condition():
                task_group.cancel_scope.deadline = anyio.current_time() + 1
# Use task_group.cancel_scope.cancel_called and task_group.cancel_scope._timeout_expired to determine the next action
```
It seems `_timeout_expired` is unambiguous and could be made public. Would it make sense to make it public?

**Comment by alegonz** [comment]
Oh, looks like that wouldn't work on the `trio` backend.

**Comment by smurfix** [comment]
That's easy. Wrap the taskgroup in another scope and use that for the deadline.

**Comment by smurfix** [comment]
Alternate solution: don't cancel the taskgroup explicitly; instead you raise an exception and catch it outside the TG.

**Comment by alegonz** [comment]
@smurfix 
oh right, it never ocurred to me that I could use two scopes 🤦‍♂️  That solution seems more ergonomic than the second idea for my use-case. Thank you!
