### ISSUE TITLE
`T_Item` for `MemoryObject{Send,Receive}Stream` should be {contra,co}variant.

### ISSUE THREAD

**Issue by jonathanslenders** [agronholm/anyio#466]
Take this example snippet, and run ``mypy --strict`` over the code:

```python
from __future__ import annotations
from anyio.streams.memory import MemoryObjectReceiveStream, MemoryObjectSendStream

# * MemoryObjectReceiveStream issue *

stream: MemoryObjectReceiveStream[bytes]
stream2: MemoryObjectReceiveStream[bytes | BrokenPipeError]

# This should be fine, because when we're in a situation that can handle
# receiving both A and B, having something from which we receive only A, we're
# good. This fails, because `T_Item` in anyio.streams.memory is not covariant.
stream2 = stream

# * MemoryObjectSendStream issue *

stream: MemoryObjectSendStream[bytes | BrokenPipeError]
stream2: MemoryObjectSendStream[bytes]

# This should be fine, because when we're in a situation that can send both A
# and B, but we promise to only send A, we're good. This fails, because
# `T_Item` in anyio.streams.memory is not contravariant.
stream2 = stream
```

This would mean that the same type variable can't be used for both class definitions, because in one class it should be covariant, while in the other, it should be contravariant.

**Comment by agronholm** [comment]
I'm favorable to adding this since trio-typing also employs co-/contravariance in this manner: https://github.com/python-trio/trio-typing/blob/1133c5816813e8cb9d9be670911b5528f5750a07/trio-stubs/abc.pyi#L87-L91

**Comment by agronholm** [comment]
But what would be the type of the deque storing the items in the buffer?

**Comment by jonathanslenders** [comment]
The deque as a whole is invariant. But either end of the deque is covariant/contravariant.

So, what we should do is not type the deque as a deque in the `MemoryObjectReceiveStream`/`MemoryObjectSendStream`, but use a `typing.Protocol` to type the fraction of the interface of the deque that we need in each case.

Something like:

```python
class DequeSender(typing.Protocol, Generic[_T_co]):
    def __len__(self) -> int: ...
    def append(self, __item: _T_co) -> None: ...


class MemoryObjectSendStream(Generic[_T_co]):
    buffer: DequeSender[_T_co]
    
```

So, the deque remains invariant, but at the point that its gets passed to the streams, we assign it to something of that protocol type, that only refers to one end of the deque.

**Comment by agronholm** [comment]
I extended this idea to all object streams in the linked PR.
