### ISSUE TITLE
Fire-and-forget semantics option

### ISSUE THREAD

**Issue by Eldar1205** [agronholm/anyio#468]
While AnyIO it meant to provide structured concurrency guarantees, sometimes what ia desired is to spin of an async task to run in the background as part of the event loop without awaiting it.

Use case: In my FastAPI app during startup I'd like to spin up a long running async background queue worker with `async def run()` that will execute on same event loop as the one used with FastAPI. I want to start that background worker, which will run until the FastAPI app shuts down, and I don't want to `await worker.run()` in my FastAPI startup.

For `asyncio` we have `asyncio.create_task`, I couldn't find something similiar with AnyIO.

**Comment by agronholm** [comment]
The same question has been asked in #457. The response here is the same: this runs counter to the structured concurrency design of AnyIO and thus will never be implemented. Your best bet is to run a task group somewhere and expose that task group to other tasks that need to run things in the background. For ASGI apps, a lifecycle scoped middleware is a good place to do this. You can find an example of something similar [here](https://github.com/agronholm/apscheduler/blob/master/examples/web/asgi_fastapi.py).

**Comment by Eldar1205** [comment]
> The same question has been asked in #457. The response here is the same: this runs counter to the structured concurrency design of AnyIO and thus will never be implemented. Your best bet is to run a task group somewhere and expose that task group to other tasks that need to run things in the background. For ASGI apps, a lifecycle scoped middleware is a good place to do this. You can find an example of something similar [here](https://github.com/agronholm/apscheduler/blob/master/examples/web/asgi_fastapi.py).

I'll take a look at your suggestion, thank you!

**Comment by Eldar1205** [comment]
> The same question has been asked in #457. The response here is the same: this runs counter to the structured concurrency design of AnyIO and thus will never be implemented. Your best bet is to run a task group somewhere and expose that task group to other tasks that need to run things in the background. For ASGI apps, a lifecycle scoped middleware is a good place to do this. You can find an example of something similar [here](https://github.com/agronholm/apscheduler/blob/master/examples/web/asgi_fastapi.py).

I looked at your suggestion with ApScheduler and FastAPI, and there are some things unclear to me. According to [ASGI lifespan docs](https://asgi.readthedocs.io/en/latest/specs/lifespan.html) it's not enough to check `if scope["type"] == "lifespan"`, but there are both startup and shutdown events to be checked. FastAPI already has startup and shutdown hooks, I'd like to be able to start ApScheduler on FastAPI startup and close it on FastAPI shutdown, two different async flows.

**Comment by agronholm** [comment]
The way it's built is that the line `await self.app(scope, receive, send) ` does not return until the app receives a shutdown event. Otherwise the async context manager would not make a lot of sense :smile:
You can do the same with a task group.

Task groups are required to be used as async context managers, so starting and stopping them in different callbacks isn't really possible.

**Comment by Eldar1205** [comment]
> The way it's built is that the line `await self.app(scope, receive, send) ` does not return until the app receives a shutdown event. Otherwise the async context manager would not make a lot of sense 😄 You can do the same with a task group.
> 
> Task groups are required to be used as async context managers, so starting and stopping them in different callbacks isn't really possible.

I read Starlette code and I see that now. Thank you very much for the tip it helps a lot :)
