### ISSUE TITLE
Trio DeprecationWarning from trio 0.22.0

### ISSUE THREAD

**Issue by provinzkraut** [agronholm/anyio#470]
With anyio 3.6.1 I get this warning:

```
anyio/_backends/_trio.py:164: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; 
use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead 
(https://github.com/python-trio/trio/issues/2211)
```

**Comment by agronholm** [comment]
There's been a 9 month process involving switching to PEP 654 exception groups in both projects. Yesterday my PR was accepted and today trio 0.22 was released with that change. AnyIO 4.0 (4.0-dev branch) already uses PEP 654 and should be released within a week or so.

**Comment by drernie** [comment]
> AyIO 4.0 (4.0-dev branch) already uses PEP 654 and should be released within a week or so.
22-SEP

Did this ever get released? If not, how can we access it?  `poetry add git+https://github.com/agronholm/anyio.git` downgrades me to 3.6.1.post111 5e0d323

**Comment by agronholm** [comment]
It's not out yet.

**Comment by BabakAmini** [comment]
> It's not out yet.

So when we'll have the final v4.0? I'm using asks besides trio and facing the same issue.

**Comment by smittysmee** [comment]
@agronholm - Any update would be swell. Thank you

**Comment by agronholm** [comment]
I'm currently trying to get the next major releases of [typeguard](https://pypi.org/project/typeguard/) and [sqlacodegen](https://pypi.org/project/sqlacodegen/) out. Once I'm done with that, I can fully focus on AnyIO 4.0. The biggest problem is the asyncio cancellation issue (#374). I tried to tackle that before but mental exhaustion made me context switch to other projects for a while.

**Comment by drernie** [comment]
Thanks so much. Can I [buy you a coffee](https://www.buymeacoffee.com) or something to help with the exhaustion?

**Comment by agronholm** [comment]
I appreciate the gesture 😊
You should know that I will switch back to working on this project this weekend. Hopefully I can get the cancellation issues sorted out.

**Comment by drernie** [comment]
Any update? The coffee offer still stands...

**Comment by agronholm** [comment]
I've resumed work on the project. I'm currently sorting out the TLS test failures on the very latest Python versions (#550). When that's dealt with, I will resume my work on fixing the native cancellation issue (#374). When _that_ is dealt with, then I can start considering a release.
