### ISSUE TITLE
`TaskGroup.start/start_soon` do not accept `Callable[..., Awaitable]`

### ISSUE THREAD

**Issue by gschaffner** [agronholm/anyio#493]
538b739b8a33bbdbf305e11d93c8bc34154e50d7 documents that support for this was added, but both of the tests in 2f89d1f762ab0ca53747269e23723469fc549252 fail at runtime. One of them also fails at type checking time, but the other does not (since 538b739b8a33bbdbf305e11d93c8bc34154e50d7 did not update all of the relevant annotations).

I've attempted to add the documented support in 8dec1b13de533d6ee2ac1d6e616c64f4186aefdb, but it's causing `test_task_in_sync_spawn_callback[trio]` to fail. As far as I can tell, `Callable[..., Awaitable]` support won't work on trio since it requires a wrapper (since trio requires `Callable[..., Coroutine]` and does not accept `Callable[..., Awaitable]`) and using a wrapper changes task ID behavior.

See also https://github.com/python-trio/trio-typing/pull/66.

**Comment by agronholm** [comment]
How is it that the test suite passes on GitHub then?

**Comment by agronholm** [comment]
This may be a misunderstanding on your part. The backends don't actually accept arbitrary callables returning awaitables; the intention here  was to amend the annotations to have them accept _coroutine-like_ objects like `<class 'async_generator_asend'>` objects you get from an async generator. These don't register as coroutines (though IMHO they should), so this was the only way to get static type checkers to accept such calls. This was only done because nobody bothered to give such objects a special type I could have checked against.

**Comment by agronholm** [comment]
In that sense, the changelog text may be a bit misleading. I can certainly correct that.

**Comment by agronholm** [comment]
[Here](https://github.com/agronholm/anyio/blob/master/tests/test_taskgroups.py#L780-L799) is a test that runs a non-coroutine awaitable (an async generator's `asend` object).

**Comment by agronholm** [comment]
Yeah, bad times all over because of the neglected `asend` type that is a non-citizen in typeshed. What do you want to do about this?

**Comment by agronholm** [comment]
I'm still thinking about what to do. I didn't plan to expand the capabilities of `anyio.run()` or friends, just amend the annotations to accommodate the things they can already do (but where static type checkers report errors).

**Comment by agronholm** [comment]
I looked at trio-typing, and their annotations match the new ones in AnyIO. The ones in typeshed, however, do not.

Perhaps the best option is to have permissive annotations, but better document what you can pass to these functions? Right now I'm not inclined to merge #567.

**Comment by agronholm** [comment]
> I think that test does not run a non-coroutine awaitable. on CPython and PyPy, `agen.__anext__` returns an `async_generator_asend`, and `issubclass(async_generator_asend, Coroutine) is True`.

It's a kind of a "Schrödinger's coroutine":
```pycon
>>> s = g.asend(None)
s
<async_generator_asend object at 0x7f6ccf8dd2c0>
>>> iscoroutine(s)
False
>>> isawaitable(s)
True
>>> isinstance(s, CoroutineType)
False
```

**Comment by agronholm** [comment]
This was addressed a while back.
