### ISSUE TITLE
Host connection issue with tcp protocol

### ISSUE THREAD

**Issue by bharathimohan11** [agronholm/anyio#498]
In file `anyio/_core/_sockets.py`, in the function `connect_tcp`  , in the  doc string , it specified that the parameter, 'remote_host',
can either be IP address or host name. [`:param remote_host: the IP address or host name to connect to`]

But remote_host is passed to the `ipaddress.ip_address()`  in `connect_tcp` function [code ref: `addr_obj = ip_address(remote_host)`], where ip_address validates the given input to IPV4 and IPV6 type where it returns error when it accepts host name.

Example Error:
'oauth2.googleapis.com' does not appear to be an IPv4 or IPv6 address.

which will be working when respective ip-address is given.

**Comment by agronholm** [comment]
Yeah, and then the `ValueError` is caught and it then proceeds to do DNS resolution for the name. What is the practical problem you encountered with this?

**Comment by bharathimohan11** [comment]
During the DNS resolution, `connect_tcp` raises Timeout error. The practical use case is with usage of async-firebase package for push notification is when  I encountered this error.

```
Traceback (most recent call last):
  File "/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/anyio/_core/_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError
```

**Comment by agronholm** [comment]
It looks like DNS lookup is timing out. I still don't see a bug though.
