### ISSUE TITLE
please hide internals

### ISSUE THREAD

**Issue by belm0** [agronholm/anyio#50]
When I'm importing trio in my IDE, I'd rather not see `anyio._backends.trio` as an option.

**Comment by agronholm** [comment]
Isn't that your IDE's fault for displaying modules from private packages?

**Comment by belm0** [comment]
Python lets you access underbar names, so an IDE is going to as well-- otherwise it would be of limited use.  And how should an IDE discern between what code is "yours" (ok to access underbars) vs. not yours?

The problem isn't limited to private packages.  Non-private packages can expose internal imports as well.  It's an anti-pattern I believe, and packages like Trio are careful to avoid it.

**Comment by agronholm** [comment]
> Python lets you access underbar names, so an IDE is going to as well-- otherwise it would be of limited use. And how should an IDE discern between what code is "yours" (ok to access underbars) vs. not yours?

At least PyCharm knows the difference between project code and third party packages, so that's not an issue.

As for trio, it too contains non-private modules inside a private package: https://github.com/python-trio/trio/tree/master/trio/_subprocess_platform

**Comment by belm0** [comment]
PyCharm is where this problem happens.

![Screen Shot 2019-04-12 at 10 07 01 PM](https://user-images.githubusercontent.com/1708631/56039508-6512e180-5d6f-11e9-935e-a658bcb81a78.png)

**Comment by belm0** [comment]
Note that trio-websockets, asks, and other packages using trio did not show up in that list.  Only anyio.

**Comment by agronholm** [comment]
I didn't say that PyCharm would behave correctly. In fact, PyCharm's autocompletion is notoriously bad. It has two competing autocompletion mechanisms, one which requires full words but auto-imports more reliably (though still not completely reliably) and one which does partial matching but rarely manages to add autoimports.

> Note that trio-websockets and other packages using trio did not show up in that list. Only anyio.

Does any of those packages contain a module named `trio`?

**Comment by belm0** [comment]
I see-- it's due to a module named trio, rather than import of trio.

Please pick another name.  Given that every codebase using anyio (transitively or directly) is going to depend and use trio directly, it's going to cause confusion many times over.

**Comment by agronholm** [comment]
I'll see what I can do, but given that autocompleting even asyncio stuff in PyCharm tries to give me `_asyncio` rather than `asyncio`, I'd say the problem is in PyCharm.

**Comment by agronholm** [comment]
I suggest you open a new issue with PyCharm to fix autocompletion to not suggest private packages or modules, at least as the first option.

**Comment by belm0** [comment]
https://youtrack.jetbrains.com/issue/PY-35385

**Comment by agronholm** [comment]
I finally decided in favor of this, seeing as how trio now does the same thing everywhere.
