### ISSUE TITLE
async tests marked with @pytest.mark.anyio are not respecting asyncio only 

### ISSUE THREAD

**Issue by gauravcanon** [agronholm/anyio#505]
In version `anyio:3.6.2` When test cases marked with `@pytest.mark.anyio` is running both `asyncio` and `trio` test cases . Earlier version `3.6.1` was running only `asyncio` when pytest.ini was set to auto 

```
[pytest]
asyncio_mode = auto
```
**When executing with `3.6.2`**

<img width="1479" alt="Screenshot 2022-11-23 at 11 50 10 PM" src="https://user-images.githubusercontent.com/897747/203623465-1a303f5a-41d0-4fab-8cd8-24434a6438ed.png">

**when executing with `3.6.1`**

<img width="1376" alt="Screenshot 2022-11-24 at 12 11 55 AM" src="https://user-images.githubusercontent.com/897747/203623870-870ff5a2-38e9-4f46-907e-11fdf0a41cd1.png">

**Comment by agronholm** [comment]
You may be confusing AnyIO's pytest plugin with `pytest-asyncio`. AnyIO's pytest plugin does not have a pytest option named `asyncio_mode`.

**Comment by gauravcanon** [comment]
@agronholm  you are right what I am trying to say is when I am on `3.6.1` test cases are only getting executed with asyncio with the same fixture when upgrading to version `3.6.2` it is running both `asyncio` and `trio`

**Comment by agronholm** [comment]
The only difference between 3.6.1 and 3.6.2 is how the version of the `trio` extra is pinned. It has nothing whatsoever to do with test plugins. I think you previously had `pytest-asyncio` installed and that was running your tests instead of AnyIO.

**Comment by agronholm** [comment]
For reference, [this](https://anyio.readthedocs.io/en/stable/testing.html#specifying-the-backends-to-run-on) is how you specify that you want to only test on asyncio.
