### ISSUE TITLE
trio 0.22.0 deprecation warning

### ISSUE THREAD

**Issue by henningWoehr** [agronholm/anyio#507]
In the current asyncio version (3.6.2) together with trio 0.22.0 this deprecation warning comes up
```
.../.venv/lib/python3.10/site-packages/anyio/_backends/_trio.py:164: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
    class ExceptionGroup(BaseExceptionGroup, trio.MultiError):
```

**Comment by agronholm** [comment]
Why are you reporting this as a bug here?

**Comment by henningWoehr** [comment]
I just saw your [commit](https://github.com/agronholm/anyio/commit/787cb0c2e53c2a3307873d202fbd49dc5eac4e96), where you specified that trio must be below 0.22 but now I'm a little confused, why I can still use trio 0.22 with the curent asyncio version. So it will not be fixed until version 4 of anyio am I right?

**Comment by agronholm** [comment]
AnyIO 3 uses its own exception group class which is inherently incompatible with the new standard exception group class, hence the limitation. And yes, this is already fixed in master, but I'm still struggling with some cancellation changes that are necessary for the upgrade.

**Comment by henningWoehr** [comment]
Ah ok thanks for the fast replies
