### ISSUE TITLE
`from_thread.run(_sync)?` does not set sniffio on asyncio

### ISSUE THREAD

**Issue by gschaffner** [agronholm/anyio#523]
note that `from_thread.run(_sync)?` _does_ set sniffio on trio, however.

this causes a few bugs:

1.  `from_thread.run(_sync)?` fails when used to call sniffio-dependent functions when the `to_thread` worker is running a non-asyncio async backend known to sniffio (i.e. trio, curio, or (situationally) trio-asyncio) and the thread that started the worker is on asyncio.

    reproducer: bc3cc490714c6022243012b6c902c33f3c4b287a.

1.  because `BlockingPortal._spawn_task_from_thread` shares its underlying implementation with `from_thread.run_sync` on asyncio, using a `BlockingPortal` that was started by `start_blocking_portal("asyncio")` in a non-asyncio async backend known to sniffio deadlocks.

    reproducer: cd9deb1e20dcb3e84bf6adcd8d9d22266ce31d0e.

**Comment by tapetersen** [comment]
At least for sync callbacks in asyncio this is an issue I also ran into and wanted to solve by detecting asyncio as backend if we were running a sync task directly in sniffIO. Would be interested in either this solution or mine going forward 

issue https://github.com/python-trio/sniffio/issues/35
PR https://github.com/python-trio/sniffio/pull/36
