### ISSUE TITLE
Implicit parent task group

### ISSUE THREAD

**Issue by davidbrochart** [agronholm/anyio#529]
When we want to launch a task not directly in the asynchronous context manager of the task group, but lower in the call stack, we need to [pass around the task group](https://trio.readthedocs.io/en/stable/reference-core.html#spawning-tasks-without-becoming-a-parent).
I was wondering if we could imagine an automatic way to do this, so that instead of writing:
```py
async def new_connection_listener(handler, tg):
    while True:
        conn = await get_new_connection()
        tg.start_soon(handler, conn)

async def server(handler):
    async with create_task_group() as tg:
        tg.start_soon(new_connection_listener, handler, tg)
```
We could write something like:
```py
async def new_connection_listener(handler):
    while True:
        conn = await get_new_connection()
        start_soon_in_parent(handler, conn)

async def server(handler):
    async with create_task_group() as tg:
        tg.start_soon(new_connection_listener, handler)
```
`start_soon_in_parent` would retrieve `tg` and call `start_soon` on it.
Maybe context variables could allow to do this?

**Comment by smurfix** [comment]
We wouldn't need a context var to access the taskgroup the current task runs in, just add an appropriate field to the `TaskInfo` struct that's returned by `anyio.get_current_task`.

However: "Explicit is better than implicit" is one of Python's tenets for a reason.

Passing the taskgroup to a procedure/method tells the reader of the calling code that "this thing may have lingering effects after it returns", and thus that you can't just cancel it and be sure that it's all gone (whatever that means in any particular context).

Experience with asyncio has taught some of us, including me, that this guarantee is essential for us (as programmers/debuggers) to keep our sanity, and thus anyio is unlikely to offer you ways to circumvent it.

**Comment by agronholm** [comment]
Well, I don't see a compelling case here, just design problems that we wouldn't be able to back out of.
