### ISSUE TITLE
expose raw_socket via public API in TCPSocketListener

### ISSUE THREAD

**Issue by oboehmer** [agronholm/anyio#531]
Hi,

I have a use case where I want to have the operating system assign a local port when calling `create_tcp_listener()` with `local_port=0`. and the need to subsequently retrieve the assigned local port from `MultiListener`/`TCPSocketListener`. I saw that `TCPSocketListener` provides a private `_raw_socket` attribute I could leverage, but wonder if you could make this one public so our code can rely on it? Or provide an alternative attribute which provides the local port assigned.

thanks!

**Comment by agronholm** [comment]
You can use the [typed attribute system](https://anyio.readthedocs.io/en/stable/typedattrs.html#using-typed-attributes) to get the socket from `TCPSocketListener` using `SocketAttribute.raw_socket` ([here](https://github.com/agronholm/anyio/blob/master/src/anyio/abc/_sockets.py#L49)). The documentation for `SocketAttribute` did apparently not render properly, hence the omission in the docs.

**Comment by oboehmer** [comment]
Thanks for the quick reply, @agronholm .. This helps a lot, and I'm closing this issue..
