### ISSUE TITLE
Ordering of acquiring CapacityLimiters vs Semaphores.

### ISSUE THREAD

**Issue by luke-1993** [agronholm/anyio#538]
In the CapacityLimiter example in the documentation:

```
from anyio import CapacityLimiter, create_task_group, sleep, run


async def use_resource(tasknum, limiter):
    async with limiter:
        print('Task number', tasknum, 'is now working with the shared resource')
        await sleep(1)


async def main():
    limiter = CapacityLimiter(2)
    async with create_task_group() as tg:
        for num in range(10):
            tg.start_soon(use_resource, num, limiter)

run(main)
```

The output gives:

```
Task number 0 is now working with the shared resource
Task number 1 is now working with the shared resource
Task number 9 is now working with the shared resource
Task number 8 is now working with the shared resource
Task number 7 is now working with the shared resource
Task number 6 is now working with the shared resource
Task number 5 is now working with the shared resource
Task number 4 is now working with the shared resource
Task number 3 is now working with the shared resource
Task number 2 is now working with the shared resource
```

However, when swapping the `CapacityLimiter` for a `Sempahore`, the output is:

```
Task number 0 is now working with the shared resource
Task number 1 is now working with the shared resource
Task number 2 is now working with the shared resource
Task number 3 is now working with the shared resource
Task number 4 is now working with the shared resource
Task number 5 is now working with the shared resource
Task number 6 is now working with the shared resource
Task number 7 is now working with the shared resource
Task number 8 is now working with the shared resource
Task number 9 is now working with the shared resource
```

I understand that one of the key differences between a CapacityLimiter and a Semaphore is the former tracks which tasks are holding each of the tokens and enforces that the task used for acquisition is the same as the task used for releasing. Whereas a Semaphore lets any task acquire/release, with the only restriction being that acquire will block if the counter is 0. However, in the above example, the acquisition and release is done via a context manager, with each task handling acquiring and releasing it self. Therefore I would've thought there should be no difference in these two examples. I can't understand why the ordering of acquisition changes between the two.

**Comment by smurfix** [comment]
Which Python version is that?

On my Debian system with Py3.11, the above is deterministic and ordered 0…9 no matter whether semaphore or cap-limiter is used – with an asyncio backend.

Trio on the other hand reverses the batch order 50% of the time, thus the ordering is somewhat randomized.

**Comment by luke-1993** [comment]
I'm on Python 3.10.
I've looked in to the implementation of Semaphore and CapacityLimiter in anyio and see that Semaphore releases using a `popleft()` on a deque, therefore giving FIFO ordering: https://github.com/agronholm/anyio/blob/master/src/anyio/_core/_synchronization.py#L351

Whereas the CapacityLimiter on an asyncio backend uses pop on a dictionary, using the result of `asyncio.Task.current_task(loop)` as the key. Therefore I'm guessing that `current_task()` ordering is not necessarily deterministic.

**Comment by luke-1993** [comment]
> TaskGroup.start_soon does not give any guarantees about scheduling order (neither does Nursery.start_soon in trio).

Right and because of this the `current_task()` lookup that's used as the key for the `_wait_queue` Dict in CapacityLimiter is not deterministic.
Yes, I think the docs could be improved by adding that the CapacityLimiter tracks the tasks so that it can ensure the task that has acquired it is the same task that releases it. I also think the examples in the docs could show this behaviour better, perhaps by using acquire and release explicitly rather than via a context manager. What do you think of using the below example instead? It runs as expected using a Semaphore as `limiter_a` and `limiter_b` but raises a RuntimeError if using `CapacityLimiter`. I think it is a better example to demonstrate the differences, since the features of CapacityLimiters are somewhat redundant when acquired and released through a per task context manager.

```
import datetime
from anyio import CapacityLimiter, create_task_group, sleep, run


async def use_resource_a(tasknum, limiter_a, limiter_b):
    await limiter_a.acquire()
    print(
        f"{datetime.datetime.utcnow()} Task number {tasknum} has acquired {limiter_a} and is working with shared resource A"
    )
    await sleep(1)
    limiter_b.release()


async def use_resource_b(tasknum, limiter_a, limiter_b):
    await limiter_b.acquire()
    print(
        f"{datetime.datetime.utcnow()} Task number {tasknum} has acquired {limiter_b} and is working with shared resource B"
    )
    await sleep(1)
    limiter_a.release()


async def main():
    limiter_a = CapacityLimiter(2)
    limiter_b = CapacityLimiter(2)
    async with create_task_group() as tg:
        for num in range(10):
            tg.start_soon(use_resource_a, num, limiter_a, limiter_b)
            tg.start_soon(use_resource_b, num, limiter_a, limiter_b)


if __name__ == "__main__":
    run(main)

```

**Comment by agronholm** [comment]
I would love `CapacityLimiter` to be deterministic too. I'll see if I can fix that.

**Comment by agronholm** [comment]
I just wrote the following test:
```python
    @pytest.mark.parametrize("anyio_backend", ["asyncio"])
    async def test_asyncio_fifo(self) -> None:
        """Regression test for #538."""
        limiter = CapacityLimiter(2)
        acquisition_order: list[int] = []

        async def acquire(tasknum: int) -> None:
            async with limiter:
                acquisition_order.append(tasknum)

        async with create_task_group() as tg:
            for i in range(10):
                tg.start_soon(acquire, i)
                await sleep(0.1)

        assert acquisition_order == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
And ran `tox -p -- -k asyncio_fifo`. It passed on all interpreters (py3.7 - py3.11 plus pypy3).
@gschaffner can you write me a test that actually fails?

**Comment by luke-1993** [comment]
@agronholm - if you place the sleep at the end of the acquire coroutine, rather than the task group, then you should see your test case fail.

**Comment by agronholm** [comment]
> @agronholm - if you place the sleep at the end of the acquire coroutine, rather than the task group, then you should see your test case fail.

It didn't. Tested against the whole array of minor Python versions. Does it fail on your end?

**Comment by luke-1993** [comment]
Yes it does fail every time on both asyncio and trio back ends when running the below testcase:

```
@pytest.mark.anyio
async def test_asyncio_fifo() -> None:
    """Regression test for #538."""
    limiter = CapacityLimiter(2)
    acquisition_order: list[int] = []

    async def acquire(tasknum: int) -> None:
        async with limiter:
            acquisition_order.append(tasknum)
            await sleep(0.1)

    async with create_task_group() as tg:
        for i in range(10):
            tg.start_soon(acquire, i)

    assert acquisition_order == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

```


The failure is the same every time:


```
anyio_cap_lim_acquire.py:4 (test_asyncio_fifo[asyncio])
[0, 1, 9, 8, 7, 6, 5, 4, 3, 2] != [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Expected :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Actual   :[0, 1, 9, 8, 7, 6, 5, 4, 3, 2]
```

I'm running on Python 3.10.0 on Windows.

**Comment by agronholm** [comment]
I've added a new branch: `capacitylimiter-acquisition-order` which contains this new test.
As you can see, the test passes just fine on all platforms: https://github.com/agronholm/anyio/actions/runs/4865592749/jobs/8676098556
Not sure why you're testing on trio, as we cannot use a custom implementation of `CapacityLimiter` there anyway since trio uses them internally.

**Comment by agronholm** [comment]
Still, the test only fails on trio, but that makes sense because trio doesn't schedule tasks sequentially like asyncio does. But then _that_ problem is solved by putting back the `sleep(0.1)` from my original version to the task group block.

**Comment by agronholm** [comment]
@luke-1993 so far this seems to only happen to you, as I cannot reproduce the problem in any environment, no matter how much I try. Could you try to dig in a bit deeper into this?

**Comment by luke-1993** [comment]
I've looked into this. The test passes against HEAD of the master branch but fails against the latest anyio release.
The bug was resolved in the following PR which is not in the latest anyio release: https://github.com/agronholm/anyio/pull/455

**Comment by agronholm** [comment]
Ok so this report was about a bug that was fixed 7 months ago? The fix is also in the 3.x branch, in preparation for the upcoming 3.x maintenance release. Is there anything more you need me to do?

**Comment by luke-1993** [comment]
correct. Nothing more needed apart from releasing the new version with the fix in. Closing this issue. Thanks.
