### ISSUE TITLE
inheritance of anyio.Path always return anyio.Path

### ISSUE THREAD

**Issue by blurhead** [agronholm/anyio#541]
here is my code example
```
from anyio import Path

class Storage(Path):
    pass


if __name__ == "__main__":
    storage = Storage("/tmp").joinpath("test.txt")

```
i expect Storage("/tmp") to return instance of Storage, not anyio.Path. i don't know if this is a bug or designed to do so

**Comment by agronholm** [comment]
It never occurred to me that someone would subclass `anyio.Path`. What is your use case? I'm not sure it is feasible to support subclassing here.

**Comment by blurhead** [comment]
for me, i want to integrate encryption and decryption in it, maybe just replace return Path(...) with self.__class__(...) could be a solution?

**Comment by agronholm** [comment]
I don't think this is the appropriate place to add such features. There is no guarantee that the subclass has the same arguments. Incidentally, this does not work with `pathlib.Path` either:
```pycon
>>> from pathlib import Path
>>> class Foo(Path): pass
... 
>>> f = Foo("/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.9/pathlib.py", line 700, in _parse_args
    return cls._flavour.parse_parts(parts)
AttributeError: type object 'Foo' has no attribute '_flavour'
```

**Comment by blurhead** [comment]
ok, i will close this issue, thanks for you answer
