### ISSUE TITLE
 ContextVar value set in async fixture is not available in test

### ISSUE THREAD

**Issue by chbndrhnns** [agronholm/anyio#544]
It seems I cannot set a value of a `ContextVar` member from a fixture in pytest if that fixture is async. 

In the snippet below, I expect all tests to pass but `test_set_in_async_fixture` which depends on a async fixture fails.

```py
from contextvars import ContextVar

import pytest

_var = ContextVar("var", default=None)

pytestmark = [pytest.mark.anyio, ]


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.fixture
async def async_():
    _var.set("other")
    yield
    _var.set(None)


@pytest.fixture
def sync_():
    _var.set("other")
    yield
    _var.set(None)


async def test_None():
    assert _var.get() is None


async def test_not_None():
    _var.set("other")
    assert _var.get() == "other"
    _var.set(None)


async def test_set_in_sync_fixture(sync_):
    assert _var.get() == "other"


async def test_set_in_async_fixture(async_):
    assert _var.get() == "other"

```

**Comment by agronholm** [comment]
This is a shortcoming of the 3.x series, and is resolved in `master`. This happens in v3.x because each async fixture is run in a separate task, and is thus isolated from the actual test. The upcoming v4.0 runs each test along with its set of async fixtures within the same task.

**Comment by chbndrhnns** [comment]
Awesome, thanks for letting me know! 
I noticed there is a [similar problem](https://github.com/pytest-dev/pytest-asyncio/issues/127#issuecomment-601315189) in `pytest-asyncio` and the suggestion from there works here, too:

> A much easier solution is to set the contextvar directly in the sync fixture — note, not async fixture, but sync:
