### ISSUE TITLE
Add Hypothesis support to pytest plugin

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#55]
Hypothesis requires some explicit support to work properly with async tests. This would also make @Zac-HD happy :)

**Comment by Zac-HD** [comment]
The trick is basically that Hypothesis can only run sync tests, so we provide an attribute that you can assign.  ([relevant docs](https://hypothesis.readthedocs.io/en/latest/details.html?highlight=inner_test#custom-function-execution), [in pytest-trio](https://github.com/python-trio/pytest-trio/blob/68dad9c085dd6b78bb5345900de02ce902784c57/pytest_trio/plugin.py#L354-L371), [in pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio/blob/f35d06b7172c3248363aae3b14a756379a2d6f37/pytest_asyncio/plugin.py#L179-L194))

```python
@pytest.mark.trio
@given(x=integers())
async def test(x):
    ...
# Illustrative code, inside the pytest-trio plugin it's a bit more complicated...
test.hypothesis.inner_test = lambda x: trio.run(test, x)
```
