### ISSUE TITLE
Pytest `RuntimeError: Event loop is closed` when autousing differently scoped fixtures

### ISSUE THREAD

**Issue by kevinvalk** [agronholm/anyio#555]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

3.6.2

### Python version

3.11.3

### What happened?

Sadly I cannot fully boil it down but I tried to be as complete as possible in the test example below. In short, if you use an async generator fixture that you put to `autouse=True` and have other async generator fixture(s) that you directly use with a scope higher than `function` you will get the following error:

```
➜  anyio-pytest poetry run pytest
================================================= test session starts ==================================================
platform darwin -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
rootdir: ...
plugins: anyio-3.6.2
collected 2 items

test_problem.py ..E                                                                             [100%]

======================================================== ERRORS ========================================================
_____________________________________________ ERROR at teardown of test_2 ______________________________________________

anyio_backend = ('asyncio', {}), args = (), kwargs = {}, backend_name = 'asyncio', backend_options = {}, runner = <anyio._backends._asyncio.TestRunner object at 0x104ab97d0>

    def wrapper(*args, anyio_backend, **kwargs):  # type: ignore[no-untyped-def]
        backend_name, backend_options = extract_backend_and_options(anyio_backend)
        if has_backend_arg:
            kwargs["anyio_backend"] = anyio_backend

        with get_runner(backend_name, backend_options) as runner:
            if isasyncgenfunction(func):
>               yield from runner.run_asyncgen_fixture(func, kwargs)

python3.11/site-packages/anyio/pytest_plugin.py:70:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python3.11/site-packages/anyio/_backends/_asyncio.py:2161: in run_asyncgen_fixture
    self._loop.run_until_complete(fixture_task)
python3.11/asyncio/base_events.py:628: in run_until_complete
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_UnixSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed

python3.11/asyncio/base_events.py:519: RuntimeError
```

So what did I expect to happen, well I expect that this would simply work. As far as I can see I am not doing anything special, but maybe I missed something.

### How can we reproduce the bug?

**test_problem.py**
```python
from typing import Any, AsyncGenerator

import pytest

AnyioBackend = tuple[str, dict[str, Any]]

"""
Event loop is closed happens in the following scenarios:
- SCOPE:
    - session
    - package
    - module
    - class: IF all fixtures are part of the same class
"""
SCOPE = "session"

@pytest.fixture(scope=SCOPE)
def anyio_backend() -> AnyioBackend:
    return ("asyncio", {})


@pytest.fixture(autouse=True, scope=SCOPE)
async def some_autouse_fixture(anyio_backend: AnyioBackend) -> AsyncGenerator[None, None]:
    """
    The auto use of this fixture is the "main" cause as in, if you disable autouse it will never fail. Does not matter
    if you provide all other fixtures and tests with "some_autouse_fixture".

    Using the `anyio_backend` fixture yes or no does not make any difference.
    """
    yield None

@pytest.fixture(scope='function')
async def some_fixture() -> AsyncGenerator[None, None]:
    """
    This fixture is also important for the error, if you remove this fixture or not use it in test_1 the error also
    goes away.

    If you make this fixture into a normal return fixture or an sync yield fixture the error goes away.
    """
    yield None


@pytest.mark.anyio
async def test_1(some_fixture: None):
    """
    The event loop is closed error does NOT happen if this test is last in all tests. If it is not last, event loop
    is closed error.
    """
    assert 1 == 1

@pytest.mark.anyio
async def test_2():
    assert 1 == 1
```

**pyproject.toml**
```toml
[tool.poetry]
name = "anyio-pytest"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "anyio_pytest"}]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.1"
anyio = "^3.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by kevinvalk** [comment]
Using commit cdc88ef33dbca9c8744f1056cfb410bd4bc20bd8 I get exact same error (but for line _backends/_asyncio.py:1831: in run_asyncgen_fixture). However, an extra message popped up that a coroutine was never awaited:
```
sys:1: RuntimeWarning: coroutine 'TestRunner._call_in_runner_task' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by agronholm** [comment]
Thanks for the report. I have a lot on my plate right now but I'll get back to you when I have a chance to test this properly by myself.

**Comment by kevinvalk** [comment]
Small extra nugget of information:

Fixture chain (as each next fixture has in its arguments list the one above):
- async(scope="session") -> AsyncGenerator[OtherObject, None]
- async(autouse=True, scope="session") -> AsyncGenerator[None, None]
- async(scope="session") -> AsyncGenerator[SomeObject, None]
- synchronize (autouse=True, scope="session") -> Generator[None, None, None]

If you have an async test function that you did not mark as `@pytest.mark.anyio` the last synchronize fixture receives its parent fixture (SomeObject) as a generator instead of the actual object `<async_generator object some_object at 0xffff7f5abca0>`.

This causes an error BEFORE pytest shows that async functions should be marked.

**Comment by kevinvalk** [comment]
The "magic" sauce ended up being the addition of the `anyio_backend` fixture from within the autouse fixture. It is partially documented at https://anyio.readthedocs.io/en/stable/testing.html#asynchronous-fixtures. However, because I have a sync fixture that uses an async fixture I assumed it was not needed in the sync fixture, **but it is**!

To illustrate:
```python
@pytest.fixture(scope="session")
async def async_fixture() -> AsyncGenerator[int, None]:
    yield 1


@pytest.fixture(scope="session", autouse=True)
def sync_fixture(async_fixture: int) -> Generator[None, None, None]:
    assert isinstance(async_fixture, int)
    yield
```
Can throw
```
async_fixture = <async_generator object async_fixture at 0xffffabc02980>

>   ???
E   assert False
E    +  where False = isinstance(<async_generator object async_fixture at 0xffffabc02980>, int)
```

Adding `anyio_backend` fixture any of the two fixtures resolves this error. _I did observe that I could add `anyio_backend` to ANY fixture that has the same scope to resolve the issue!_

That said, the errors I described in this ticket are super flaky and sometimes I cannot reproduce them no matter what I try.... so I am closing this ticket for now...
