### ISSUE TITLE
`from_thread.run()` typing issue with TypeVar

### ISSUE THREAD

**Issue by uSpike** [agronholm/anyio#560]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

3.6.2

### Python version

3.11

### What happened?

Trying to run a program similar to this:

```python
from typing import TypeVar

import anyio
from anyio import to_thread, from_thread

T = TypeVar("T")

async def coro(val: T) -> T:
    return val

def run_from_thread() -> int:
    return from_thread.run(coro, 1)

async def main() -> None:
    val = await to_thread.run_sync(run_from_thread)
    print(val)

if __name__ == "__main__":
    anyio.run(main)
```
mypy and pylance both complain:
```
test.py:12:12: error: Incompatible return value type (got "T", expected "int")  [return-value]
Found 1 error in 1 file (checked 1 source file)
```

### How can we reproduce the bug?

Run the program through the latest mypy (1.1.1)

**Comment by agronholm** [comment]
Is this even fixable? Does it work in another library/framework?
