### ISSUE TITLE
Re-entrant lock implementation

### ISSUE THREAD

**Issue by uSpike** [agronholm/anyio#563]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

I have a use-case for a re-entrant lock, functionally similar to the `threading.RLock` implementation but for async tasks instead of threads.

I propose to add a simple `anyio.RLock` implementation:

```python
from collections import defaultdict

import anyio

class RLock(anyio.Lock):
    """Reentrant lock that can be acquired multiple times by the same task."""
    def __init__(self) -> None:
        super().__init__()
        self._tasks: defaultdict[anyio.TaskInfo, int] = defaultdict(int)

    async def acquire(self) -> None:
        current_task = anyio.get_current_task()
        if current_task not in self._tasks:
            await super().acquire()
        self._tasks[current_task] += 1

    def release(self) -> None:
        current_task = anyio.get_current_task()
        self._tasks[current_task] -= 1
        if self._tasks[current_task] == 0:
            super().release()
            del self._tasks[current_task]
  ```
  which can be used in the following way:
  ```python
  class Thing:
    def __init__(self) -> None:
        self.lock = RLock()

    async def foo(self, a: int) -> None:
        async with self.lock:
            print("foo", a)
            await anyio.sleep(1)

    async def bar(self, a: int) -> None:
        async with self.lock:
            await self.foo(a)
            print("bar", a)

async def main() -> None:
    thing = Thing()
    async with anyio.create_task_group() as tg:
        tg.start_soon(thing.bar, 1)
        tg.start_soon(thing.bar, 2)

anyio.run(main)
```
yielding output
```
foo 1
bar 1
foo 2
bar 2
```

### Use case

I have a hardware abstraction library written with anyio and it can be very tricky to get `Lock` instances setup in exactly the right places without ever accidentally acquiring them in the same task.

**Comment by agronholm** [comment]
Trio does not seem to have a re-entrant lock implementation either. This is a bit of a mystery. Has this use case never come up before?

**Comment by uSpike** [comment]
Happy to submit a PR, just wanted to start a conversation and see if you were like "woah this is a terrible/hard idea" :P

I find it hard to believe it's never come up before for either async library.. maybe people aren't using locks that much?  I find it very useful since you can be more liberal about sprinkling lock usage around.

**Comment by uSpike** [comment]
Looks like there was a discussion: https://discuss.python.org/t/asyncio-rlock-reentrant-locks-for-async-python/21509

**Comment by agronholm** [comment]
Personally I've used quite a few locks, but I've never needed a re-entrant lock in async code. I've needed them in sync code somewhere though.

**Comment by njsmith** [comment]
Reentrant locks are a very dubious idea: https://blog.stephencleary.com/2013/04/recursive-re-entrant-locks.html

I think they're mostly "standard" only because they're somewhat useful if you're trying to brute-force port a legacy single-threaded library to survive in a multi-threaded environment without understanding the underlying invariants, by sticking a reentrant lock around every entry point? There are other more situations where they're useful (Trio even uses one `threading.RLock` internally to work around a subtle edge case in CPython's signal handling), but I think modern consensus is that they're a highly specialized tool and almost always when you're tempted to reach for them it's a sign that you should take a deep breath and rethink your design.

**Comment by agronholm** [comment]
@uSpike could you elaborate on what exactly you need them for?

**Comment by agronholm** [comment]
Closing due to lack of responses.
