### ISSUE TITLE
Futures from BlockingPortal.spawn_task don't wake up concurrent.futures.wait when cancelled

### ISSUE THREAD

**Issue by tapetersen** [agronholm/anyio#575]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

3.7.0

### Python version

3.10.6

### What happened?

Not sure if this is supposed to be supported and digging into the internals of futures.Future and wait I can see why it's a headache todo so but for what it's worth and what I've found.

When creating a blocking portal and spawning tasks in it from a worker thread I can wait on the `concurrent.futures.Future` returned from `BlockingPortal.spawn_task()`  using `Future.result()` and if I stop the portal with `portal.stop(cancel_remaining=True)` the waiting thread will exit with a `CancelledError`

If I try to wait on the result with `concurrent.futures.wait([future], return_when=futures.FIRST_COMPLETED)` however it is never notified of the cancellation and hangs the thread.

Tested on asyncio backend

### How can we reproduce the bug?

```python
import anyio

from concurrent import futures

import anyio.abc
from anyio import from_thread, to_thread

def sync_thread(portal: anyio.abc.BlockingPortal):
    # Normal result() method of future works as expected
    portal.spawn_task(anyio.sleep_forever).result()
    # wait will never return
    # futures.wait([portal.spawn_task(anyio.sleep_forever)], return_when=futures.FIRST_COMPLETED)


async def main():
    async with (
        from_thread.BlockingPortal() as portal,
        anyio.create_task_group() as tg,
    ):
        tg.start_soon(to_thread.run_sync, sync_thread, portal)
        # Ensure thread has time to start the task
        await anyio.sleep(0.1)
        await portal.stop(cancel_remaining=True)

if __name__ == "__main__":
    anyio.run(main)
```

**Comment by tapetersen** [comment]
Ok after digging a whole lot deeper the problem is basically that `Future.cancel()` nofifies the condition variable which will wake up direct callers of `Future.result()` but will not take care of `Future._waiters` where `future.wait` adds itself.

This is since it waits for the "Executor" to call `Future.set_running_or_notify_cancel` to tell that this is really cancelled and won't be run.

Adding a `future.set_running_or_notify_cancel()` to the except block after https://github.com/agronholm/anyio/blob/f7a880ffac4766efb39e6fb60fc28d944f5d2f65/src/anyio/from_thread.py#L219 solves it.

I can however see that the code is substantially different in master. I wll see if I can test it with master or if it's solved there.

**Comment by tapetersen** [comment]
Have created initial minimal PR that solves the problem. I can add a test if needed as well.
Have checked locally and this solves it on both asyncio and trio backends

**Comment by tapetersen** [comment]
I was running into this after having started to write something more or less equivalent to blocking portals and getting stuck on some problems with mapping concurrent.Futures cancellation and notification model to async tasks in the event loop.

Futures expect you to call set_running_or_notify_cancel when the executor, in this case the event loop starts executing them which puts them in RUNNING state (or notifies waiters that it's cancelled). Problem with doing that at task creation time is that Future assumes you can't be cancelled once started running and will short-circuit that call, not cancelling the Task

This means that doing do would mean calling cancel from the thread would no longer work for cancelling the Task either.

Understandable since threads generally aren't interruptable but taks and processes are. Ideally I would probably want a subclass of Future that allows this cancelation even in RUNNING state (if nothing else to have the future report correct state but I don't really have a concrete use case for that)

**Comment by agronholm** [comment]
I can confirm this still happens on master. A test would be required for the PR to be merged.
