### ISSUE TITLE
Unable to create new event loop in a subprocess

### ISSUE THREAD

**Issue by luke-1993** [agronholm/anyio#588]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

3.7.1

### Python version

3.10.8

### What happened?

asyncio allows creating a new event loop in a separate sub process and using asyncio in the separate process.
Attempting to run a new event loop with anyio with an asyncio backend causes the following error:

"Already running asyncio in this thread"

Can be reproduced using the below program. Switching out `anyio.run` for `asyncio.run` in `subprocess_runner()` works. This shows there is a problem with anyio when used in a separate sub process.

```
import asyncio
import functools
from concurrent.futures import ProcessPoolExecutor

import anyio
from anyio import Event


async def async_subprocess_runner():
    for _ in range(5):
        print("doing something in a subprocess")
        await anyio.sleep(1)


def subprocess_runner():
    print("restrictions runner started")
    try:
        # using asyncio works
        # asyncio.run(async_subprocess_runner())
        anyio.run(async_subprocess_runner)
    except Exception as ex:
        print(f"got exception {ex}")
        raise


async def run(executor, event):
    loop = asyncio.get_event_loop()
    async with anyio.create_task_group() as tg:
        with executor as executor:
            try:
                await loop.run_in_executor(
                    executor,
                    functools.partial(
                        subprocess_runner,
                    )
                )
            except Exception as ex:
                print(f"got exception {ex}")
        print("sub process completed")
        event.set()


async def main():
    event = Event()
    async with anyio.create_task_group() as tg:
        exec = ProcessPoolExecutor()
        tg.start_soon(run, exec, event)
        await event.wait()


if __name__ == '__main__':
    anyio.run(main)
```

### How can we reproduce the bug?

Use the provided example program

**Comment by agronholm** [comment]
What is the practical use case you want to solve here? You're not even using AnyIO's own subprocess facilities.

**Comment by luke-1993** [comment]
use case: having two parallel processes each performing asynchronous IO operations.

AnyIO's sub process facilities unfortunately do not provide sub process communication so I am forced to use the core library. An example of why the process communication primitives are needed is to implement logging properly in the sub processes: https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes)

**Comment by agronholm** [comment]
> use case: having two parallel processes each performing asynchronous IO operations.

I'm curious about the reason why you need this.
At any rate, the following change fixes the problem (you need to add `import multiprocessing`):
```python
        exec = ProcessPoolExecutor(mp_context=multiprocessing.get_context("spawn"))
```

**Comment by luke-1993** [comment]
Interesting. Thanks for the work around. I'm interested in why that works? I'm running on a unix system so I would think its default context would be to spawn rather than fork.

As for my specific use case. The work performed in the sub process is quite substantial. It involves receiving real time updates from a messaging broker as well as querying external HTTP services whilst performing CPU intensive operations on the consumed messages.

**Comment by luke-1993** [comment]
Thanks for your help in this.

**Comment by agronholm** [comment]
You're welcome!
