### ISSUE TITLE
Timeout error after success

### ISSUE THREAD

**Issue by smurfix** [agronholm/anyio#589]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there
- [X] I have checked that my bug is still present in the latest release

### AnyIO version

3.7 or master, Trio 0.22.2 or asyncio

### Python version

3.11

### What happened?

Consider this code snippet:
``` python3
     try:
         with anyio.fail_after(10):
             msg = await self._wqueue_r.receive()
             logger.debug("We got %s", msg)  ## A
     except TimeoutError:
         msg = NOPMsg()
         logger.debug("We timed out and use %s", msg)  ## B
     ... # do something with the message
     logger.debug("We processed %s", msg)  ## C
```

This seems straightforward, no? We log either A or B, depending on whether something's in the queue or not, then C.

… except that once in a blue moon I get A+B+C.

The problem occurs with Trio or asyncio back-ends. It does not occur when using Trio directly.

### How can we reproduce the bug?

On my (fast) development VM, this code exhibits the problem pretty much immediately. On a Raspberry Pi 3, T=0.1 causes it to show up after a few seconds. If it doesn't, change the `0.9` in the third-last line so that the reported numbers increase roughly at the same speed.

```python3

import sys
import anyio
import trio
import random

T = 0.0001
N=int(2/T)

async def eat(r):
    a=0
    b=0
    while True:
        msg = None
        try:
            with anyio.fail_after(T):
            # with trio.fail_after(T):  # bug disappears
                msg = await r.receive()
        except (TimeoutError, trio.TooSlowError):
            if msg is not None:
                raise RuntimeError("Owch {a} {b}")
            b += 1
        else:
            a += 1
        if a%N == 0 or b%N == 0:
            sys.stderr.write(f"  {a} {b}\r"); sys.stderr.flush()

async def main():
    s,r = anyio.create_memory_object_stream(10)
    async with anyio.create_task_group() as tg:
        tg.start_soon(eat,r)
        while True:
            await anyio.sleep(T*(random.random() * 0.7 + 0.9)) ## might need to adapt
            await s.send(True)

anyio.run(main)
```

**Comment by agronholm** [comment]
@smurfix could you review the linked PR? I would like to get this into v4.0.
