### ISSUE TITLE
Different stack traces when there is an issue between Windows and Linux/Mac in 4.0.0

### ISSUE THREAD

**Issue by gameAnalyticsGreg** [agronholm/anyio#613]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.0.0

### Python version

3.8

### What happened?

Hi,

After update to 4.0.0 when exception happens during development, part of the message is not visible in version 4.0.0 on windows. This code seems to be running fine on Mac/Linux ( it shows full stack trace). After downgrading back to 3.7.1 full stack trace is visible.

I have noticed that removing sentry sdk seems to be fixing the issue so I am not sure if I should reported it here or in their repo BUT same sdk version works fine with 3.7.1 and breaks in 4.0.0....

I have 2 stack traces from my colleagues (but those are not from minimal workable example below, I can attach them on request).

Thanks and have a nice day.

### How can we reproduce the bug?

Fastapi version: 0.99.1
Sentry SDK: 1.30.0

Working example:
[api_test.txt](https://github.com/agronholm/anyio/files/12525554/api_test.txt)
I am running it from within PyCharm with this command:

```
import sys; print('Python %s on %s' % (sys.version, sys.platform))
C:\Users\grzegorz\AppData\Local\pypoetry\Cache\virtualenvs\project-MO2amzI4-py3.8\Scripts\python.exe -B "C:/Users/grzegorz/AppData/Local/Programs/PyCharm Professional 2/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 50093 --file C:\work\python\project\project\api_test.py 
Connected to pydev debugger (build 232.9559.58)
INFO:     Will watch for changes in these directories: ['C:\\work\\python\\project']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [20012] using WatchFiles
INFO:     Started server process [4932]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:50118 - "GET /test HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
```

```
### test
GET {{host}}/test
Content-Type: application/json
```

Stack trace with 4.0.0 from minimal example:
[not_working_stack_4.txt](https://github.com/agronholm/anyio/files/12525556/not_working_stack_4.txt)

Reverting back to 3.7.1:
[working_stack_3_7_1.txt](https://github.com/agronholm/anyio/files/12525559/working_stack_3_7_1.txt)

I see that removing sentry sdk initialization fixes the issue:
[working_stack_4_0_0_without_sentry_sdk.txt](https://github.com/agronholm/anyio/files/12525584/working_stack_4_0_0_without_sentry_sdk.txt)

**Comment by agronholm** [comment]
FastAPI depends on a version of Starlette that is not compatible with AnyIO 4. The latest Starlette does work properly with AnyIO 4, but you won't get that with FastAPI as it pins to a specific Starlette. The latest FastAPI release pins AnyIO to < 4 to fix this.

**Comment by agronholm** [comment]
Does this answer your question or do you need further clarification of the issue? This relates to the first item on the 4.0.0 changelog: https://anyio.readthedocs.io/en/stable/versionhistory.html

**Comment by gameAnalyticsGreg** [comment]
> Does this answer your question or do you need further clarification on the issue? This relates to the first item on the 4.0.0 changelog: https://anyio.readthedocs.io/en/stable/versionhistory.html

That explains it :) Sorry for not checking change log first :/
