### ISSUE TITLE
RuntimeError: Runner is closed in pytest

### ISSUE THREAD

**Issue by EdorianDark** [agronholm/anyio#619]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.0.0

### Python version

3.11.5

### What happened?

The error message "RuntimeError: Runner is closed" appears.

### How can we reproduce the bug?

The following leads to the described error:
````python
import pytest
pytestmark = pytest.mark.anyio

@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"

@pytest.fixture(scope="class")
async def bbbbbb():
    yield ""
 
@pytest.fixture(scope="class")
async def aaaaaa():
    yield ""

class TestJobs(object):
    async def test_1(self, bbbbbb):
        pass

    async def test_2(self, aaaaaa, bbbbbb):
        pass

    @pytest.mark.skip
    async def test_3(self, aaaaaa, bbbbbb):
        pass
 ````
I get always the error in the skipped test
````
self = <asyncio.runners.Runner object at 0x101af5d50>

    def _lazy_init(self):
        if self._state is _State.CLOSED:
>           raise RuntimeError("Runner is closed")
E           RuntimeError: Runner is closed

/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py:133: RuntimeError
=================================== short test summary info ===================================
ERROR test_pytest_error.py::TestJobs::test_3 - RuntimeError: Runner is closed
============================ 2 passed, 1 skipped, 1 error in 0.04s =========================
````

Not that if I change it to ``pytestmark = pytest.mark.asyncio`` there is no error.
Also the error goes away if I change the order of the function parameters to have bbbbb always in front.

**Comment by agronholm** [comment]
Notes: The third test seems irrelevant. The second test also passes if the `bbbbbb` fixture is removed from it.

**Comment by agronholm** [comment]
Minimal test case with module scoped fixtures:
```python
import pytest

pytestmark = pytest.mark.anyio


@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"


@pytest.fixture(scope="module")
async def bbbbbb():
    yield ""


@pytest.fixture(scope="module")
async def aaaaaa():
    yield ""


async def test_1(bbbbbb):
    pass


async def test_2(aaaaaa, bbbbbb):
    pass
```

**Comment by agronholm** [comment]
I just ran into this problem at my day job :sweat_smile:

**Comment by agronholm** [comment]
The issue is that the first fixture gets "ownership" of the test runner, and if that fixture isn't the last one to be torn down, the rest will fail with this error at teardown.

**Comment by agronholm** [comment]
@EdorianDark Let me know if you're available to review the fix PR or not.
