### ISSUE TITLE
Expose ResourceGuard

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/anyio#627]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

ResourceGuard should be exposed publically, instead of requiring importing from an internal module.

### Use case

It's a useful object for implementing streams that use pumping tasks behind the scenes.

**Comment by agronholm** [comment]
I've considered this. It would help if you elaborated on the use case.

**Comment by Fuyukai** [comment]
> It would help if you elaborated on the use case.

My client class uses a background task to read messages from the socket and turn them into objects, then publishes them on a channel for the downstream users to read. It's essentially the same reason as socket streams having their receive/sends wrapped in a conflict detector.
