### ISSUE TITLE
Pytest async method fixture is run with different `self` than the test method

### ISSUE THREAD

**Issue by Guerilla94** [agronholm/anyio#633]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.0.0

### Python version

3.11.4

### What happened?

I'm trying to use an fixture class method to initialize some data for tests and store it in attributes. With synchronous fixture everything works as expected, the filled attributes are available in the test methods. But attributes filled in async function are not available in test methods. This happens because different objects are passed as "self" for the fixture and the test method. 

I found [similar issue for pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio/issues/197) which was fixed

### How can we reproduce the bug?

```
import pytest


class TestSomething:
    @pytest.fixture()
    async def do_setup(self):
        self.some_attr = 'value'

        print()
        print('in fixture')
        print(self)
        print(self.__dict__)

    async def test_something(self, do_setup):
        print()
        print('in test')
        print(self)          # different object
        print(self.__dict__) # some_attr missing
```

Output:

```
in fixture
<tests.test_anyio.TestSomething object at 0x107b0ca50>
{'some_attr': 'value'}

in test
<tests.test_anyio.TestSomething object at 0x107f06590>
{}
```

**Comment by agronholm** [comment]
Linking the pytest-asyncio fix PR here: https://github.com/pytest-dev/pytest-asyncio/pull/439

**Comment by agronholm** [comment]
Meanwhile I suggest that you don't assign anything to the instance. That's not the correct way to use fixtures.

**Comment by Guerilla94** [comment]
Assigning something to an instance looks strange when calling a fixture directly. We usually use a fixture with `autouse=True` to initialize data for all tests in a class:
```
class TestSomething:
    @pytest.fixture(autouse=True)
    def _setup(self):
        self.some_attr = 'value'
```
In this case, assigning to an instance seems more justifiable. Or in this case assigning to the instance is also not the correct way?

I didn't include `autouse` in the reproduction example because it doesn't affect the problem

**Comment by agronholm** [comment]
Why not return the value from the fixture?

**Comment by Guerilla94** [comment]
To do this, you will have to specify in each test of class the use of the fixture directly instead of `autouse`. It looks like boilerplate when each test in the class directly uses same setup fixture:
```
class TestSomething:
    @pytest.fixture()
    async def setup_data(self):
        return {}

    async def test_something(self, setup_data):
        pass

    async def test_something_else(self, setup_data):
        pass

    async def test_something_else2(self, setup_data):
        pass
```
Additionally, not all tests require data from the setup, but the setup process is still necessary. In this case it is easy to forget to specify setup fixture for test

**Comment by Guerilla94** [comment]
Thank you, now I understand your point. I haven't thought about using a fixture with `autouse=True` directly if result is needed. I'll need to rethink the use of fixtures. Looks like it would be better not to use assigning to instance in fixtures. 

Therefore, I think that this behavior can be left as is. It seems that the issue can be closed

**Comment by agronholm** [comment]
> Therefore, I think that this behavior can be left as is. It seems that the issue can be closed

I disagree. This plugin should not make pytest deviate from how it normally works.

**Comment by reneleonhardt** [comment]
@Guerilla94 does this problem still affect you?
The fix for pytest-asyncio has been merged 2 years ago, so anyio would have be fixed too?

**Comment by smurfix** [comment]
Umm, the problem still exists.

```
import pytest
from contextlib import asynccontextmanager

pytestmark = pytest.mark.anyio

class TestMe(object):
    @pytest.fixture(autouse=True, scope="function")
    async def fix_foo(self):
        print("setup A")
        self.foo = "bar"

    @pytest.fixture(autouse=True, scope="function")
    async def fix_bar(self):
        print("setup B")
        self.bar = "baz"
        yield
        print("teardown")

    async def testSupport(self):
        print("test start", id(self),vars(self))  # error: empty
        assert hasattr(self,"foo")
        assert hasattr(self,"bar")
```

A pytest run emits:
```
setup B 140325416335072
setup A 140325416335072
start 140325424259888 {}
```
and then dies, which is not the intended result at all.

Tested in a fresh venv. pytest 8.3.3, anyio 4.6.0, trio/asyncio doesn't matter.

This is a problem. I'm currently porting the caldav library to anyio; its tests use nontrivial setup/teardown methods which can easily be converted to fixtures (simply replace the "def teardown(…)" with "yield" and prepend `@pytest.fixture(autouse=True)`). Replacing the fixture with a context manager would re-indent the complete test file, and that basically prevents further merges from upstream and is not at all when I'm trying to achieve.

The above test works perfectly when using sync fixtures, or when using `pytest-asyncio` instead. I do NOT want to switch to that.

**Comment by agronholm** [comment]
I would welcome a PR to fix this.

**Comment by smurfix** [comment]
So would I. I would also welcome enough free time to acquire enough knowledge of pytest's internals to be able to do so, but the world doesn't seem to work that way. :-/

**Comment by agronholm** [comment]
I'll see if I can fix this quickly. No promises though.

**Comment by smurfix** [comment]
Don't sweat it, for my purposes the pytest-anyio workaround is sufficient for the short term.
