### ISSUE TITLE
Backend specific options don't appear to be used

### ISSUE THREAD

**Issue by DaGenix** [agronholm/anyio#643]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.1.0

### Python version

3.11

### What happened?

As best as I can tell, the backend specific options for both the asyncio and trio options aren't being used

https://github.com/agronholm/anyio/blob/cc18942a384dcb881e78a81c898d7e89d4e1ce0b/src/anyio/_backends/_asyncio.py#L1939-L1960

https://github.com/agronholm/anyio/blob/cc18942a384dcb881e78a81c898d7e89d4e1ce0b/src/anyio/_backends/_trio.py#L807-L814

### How can we reproduce the bug?

I'm sorry if I'm missing something, but the backend options don't appear to be used, except for `debug` for asyncio. I don't have a test case, however, so, I apologize again if I'm not seeing how the options are getting applied.

**Comment by agronholm** [comment]
What backend options are you trying to pass?

**Comment by DaGenix** [comment]
I was looking into enabling the uvloop option and was overall interested in which options where available. But, looking at the code, it appeared that the options weren't being used.

**Comment by agronholm** [comment]
On the asyncio backend, the `debug`, `loop_factory` and `use_uvloop` options are used, as indicated in the code you pasted. What other options are you looking to pass?

**Comment by DaGenix** [comment]
@agronholm In the code I posted, the only mention of `use_uvloop` is:
```python
     options.get("use_uvloop", False) 
```
Which fetches it from the options dictionary, but then does nothing with the value.

I'm not super familiar with the anyio code, however, so, I apologize if its being used somewhere else.

However, I tried the following test program:

```python
import anyio
import asyncio


async def inside_asyncio() -> None:
    print(asyncio.get_running_loop())


anyio.run(inside_asyncio, backend_options={"use_uvloop": True})
```

When I run the above with anyio 3.7.1, it prints out:
```
<uvloop.Loop running=True closed=False debug=False>
```

However, when I run it with 4.1.0, it prints out:
```
<_UnixSelectorEventLoop running=True closed=False debug=False>
```

**Comment by agronholm** [comment]
Oh wow, I didn't see that. So apparently while they **are** used for the test runner, they're ignored for `anyio.run()`. This is a big oversight. I'll get this sorted out for the next release.

**Comment by agronholm** [comment]
@DaGenix I trust that the linked PR fixes the issue? Would you mind taking a peek?

**Comment by DaGenix** [comment]
@agronholm cool. that looks good to me!
