### ISSUE TITLE
IPv6 is not supported

### ISSUE THREAD

**Issue by daa** [agronholm/anyio#65]
Currently it's impossible to create TCP or UDP server listening on IPv6 address, also it's impossible to connect to IPv6 address using ``anyio.connect_tcp()`` because ``socket.gaierror: [Errno -9] Address family for hostname not supported`` is raised.

To solve the issue I suggest to make following changes:
- allow to pass optional ``family`` argument to ``create_tcp_server()`` and ``create_udp_socket()``
- if ``family`` is not given infer it from ``interface`` argument if possible
- implement ``create_connection()`` function and use it instead of ``socket.connect()`` in ``connect_tcp()`` function

If proposed changes are fine with you I will submit a pull request.

**Comment by agronholm** [comment]
This is a tremendous oversight on my part. I always did try to design anyio with ipv6 in mind, but it seems that I actually failed to test it. I'll have a look and see what I can do to fix this.

**Comment by agronholm** [comment]
Out of curiosity: how did you plan to implement the async aspect with `create_connection()`?

**Comment by daa** [comment]
I hoped to use correponding functions from underlying async libraries:
- for ``curio`` it would be ``socket.create_connection()``
- for ``trio`` - ``trio.open_tcp_stream()``
- for ``asyncio`` - ``loop.create_connection()``
However it would require some work to adapt result of those functions to ``anyio`` abstractions. And when I looked more carefully I'm not sure it would be possible to do in clean way because for example ``asyncio`` has socket as a private attribute of transport.

On the other hand simpler approach is possible - run ``socket.create_connection()`` in thread like ``curio`` does.

**Comment by agronholm** [comment]
The first approach you suggest is a non-starter due to the wildly varying interfaces provided by the return values of these calls. I've now implemented connection creation locally by adapting `socket.create_connection()`. There are some tweaks to be made and then I need to add support to `create_tcp_server()` as well, but things are looking good.

**Comment by daa** [comment]
Great! Thank you very much.

**Comment by agronholm** [comment]
So here is what I am thinking regarding `create_tcp_server()`: if you pass `::` as the interface, it will listen on all IPv6 interfaces (but not IPv4). If you pass `0.0.0.0`, it will listen on all IPv4 interfaces. If you pass `None` (the default), it will listen on `::` but without the `IPV6_V6ONLY` flag which means it will listen on any v6 or v4 interface. Of course all of this will be added to the docs. Thoughts?

**Comment by smurfix** [comment]
Makes sense, though "interface" is a bit of a large misnomer here. "interface" to me is `eth0` or `lo`.

**Comment by agronholm** [comment]
It's the address of the interface that the socket should be bound to. Lots of apps and libraries use the same terminology.

**Comment by agronholm** [comment]
That said, I could easily clarify this in the docstring.

**Comment by smurfix** [comment]
Please do.

**Comment by agronholm** [comment]
Another problem is, what would a user expect to happen if they pass `localhost` as the interface name?

**Comment by agronholm** [comment]
Or should I require an IP address?

**Comment by smurfix** [comment]
You beat me to it … there's no good answer here because it's anybody's guess which address "localhost" will first resolve to and which any client connecting to it will get.

Thus, do what you'd do with any other name: either look it up, and if there's more than one address attached to the name, raise an error. Or don't look it up at all and require a literal address.

**Comment by agronholm** [comment]
I think I will require an IP address. I will leave in a compatibility code path for `localhost` (as that worked before) which binds to 127.0.0.1 but will generate a `DeprecationWarning`.

**Comment by agronholm** [comment]
I have the fix implemented, tested and working for TCP. But the problem exists for UDP sockets as well so I'm going to fix that as well before pushing my changes.

**Comment by agronholm** [comment]
Almost done. Just need to check the new TCP connection logic.

**Comment by agronholm** [comment]
Yeah, looks like I'll have to follow trio's example and implement RFC 6555 (Happy eyeballs algorithm).

**Comment by agronholm** [comment]
For the time being I'm going to let it slide and just go with what I have.

**Comment by agronholm** [comment]
I've created #69 to track the Happy Eyeballs implementation.
