### ISSUE TITLE
sent_count, received_count for MemoryObjectStreamStatistics

### ISSUE THREAD

**Issue by tapple** [agronholm/anyio#657]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

When an object is sent or received on an object stream, increment a counter. Return that counter with statistics()

### Use case

It would be great for monitoring. I would like to use it for showing progress bar to end-users

**Comment by agronholm** [comment]
The memory object stream statistics were modeled after trio's channel statistics which doesn't do this. I also think it might be easier for you to implement your progress bar some different way. I'm not convinced that this is the proper place for that.
