### ISSUE TITLE
Anyio not picking on ssl stuff when moved from one domain to a subdomain with asks

### ISSUE THREAD

**Issue by Spyder-exe** [agronholm/anyio#67]
I've been trying to access the spotify accounts overview page using python, I can do this with requests and aiohttp, however when trying with the async httplib asks, I get an error: `[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)`

So I opened an issue for asks: https://github.com/theelous3/asks/issues/132

And after some investigation asks' creator believes the error comes from anyio and recommended I open an issue here to see what we can do about not panicing on ssl stuff when we are 30x moved from one domain to a subdomain.

**Comment by theelous3** [comment]
Hi. Yeah haven't had time to see if this is an issue with anyio specifically, or just an edge case that needs to be worked around bubbling up from stdlib (guessing the latter).

**Comment by agronholm** [comment]
Can someone provide me a simple script that repros the problem?

**Comment by Spyder-exe** [comment]
import trio
    import asks
    async def check(s):

        overview = await s.get("https://www.spotify.com/us/account/overview")
        print(overview.text)


    async def run_task():
        s = asks.Session()
        async with trio.open_nursery() as nursery:
            nursery.start_soon(check, s)
        
    trio.run(run_task)

**Comment by agronholm** [comment]
Right, I was just saying that the original issue has a snippet :)

**Comment by agronholm** [comment]
I'll see what I can find out.

**Comment by agronholm** [comment]
The problem only occurs on a redirect. I suspect this has something to do with the fact that asks passes the previous SSL context to `anyio.connect_tcp()`.

**Comment by agronholm** [comment]
Nope, that wasn't it.

**Comment by agronholm** [comment]
Wow, this is a tricky one. I can't reproduce it by simply first establishing an HTTP connection to the first host and then the second.

**Comment by agronholm** [comment]
Waitaminute...asks calls `anyio.connect_tcp()` using port 80 but with `autostart_tls=True`. This is definitely a bug in asks, not anyio.
