### ISSUE TITLE
anyio release

### ISSUE THREAD

**Issue by belm0** [agronholm/anyio#68]
please release recent fixes (deprecated use of Trio.Event.clear())

**Comment by agronholm** [comment]
I am planning to make a minor release in the next few days which will include the trio 0.12 fixes, ipv6 fixes and capacity limiter support.

**Comment by agronholm** [comment]
Sorry this is taking longer than I said it would. I have capacity limiters implemented but I wanted to make them apply to `run_in_thread()` as well and I'm currently in the process of writing tests for that. Once I'm done with that I'll be ready to release.

**Comment by agronholm** [comment]
I have `run_in_thread()` limiter support in place but I'm still having weird issues with the curio backend. Once this has been dealt with I'm ready to make the release.

**Comment by agronholm** [comment]
v1.1.0 is out now.
