### ISSUE TITLE
[pytest] support keeping event loop for higher scope

### ISSUE THREAD

**Issue by ckyoog** [agronholm/anyio#686]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

For `pytest-asyncio`, we can use the event loop within a higher scope by `@pytest.mark.asyncio(scope='module')`.

Can we have the equivalence in `anyio`?

In `anyio`, we can create a specific async client or server in a higher scope by this
```
@pytest.fixture(scope='module')
def anyio_backend():
    return 'asyncio'


@pytest.fixture(scope='module')
async def server(anyio_backend):
    server = await setup_server()
    yield
    await server.shutdown()
```

But that is not event loop, I wonder whether the event loop can live in a higher scope.

### Use case

My unit test can work with `pytest-asyncio`, with the scope set to `module` or `session`. But it doesn't work with `anyio`.

 In order to let it work with `anyio`, I need to change the code structure, to create a bunch of fixtures and set their scope to like `module` or `session`. If I can set the scope of the event loop to higher, I will not have to make these changes.

**Comment by agronholm** [comment]
I routinely use a higher scoped event loop with the anyio pytest plugin. You keep saying "doesn't work" but you don't provide any details. What's not working with the above setup?

**Comment by ckyoog** [comment]
Sorry for the delay.

Here is the example code to illustrate the issue
```python
import pytest
import aiohttp


s = None


#@pytest.fixture(scope='module')
@pytest.fixture(scope='session')
def anyio_backend():
    return 'asyncio'


async def test_pass(anyio_backend):
    global s
    s = aiohttp.ClientSession()
    r = await s.get("http://www.example.com")
    print(r.status)


async def test_fail(anyio_backend):
    r = await s.get("http://www.example.com")
    print(r.status)
```
Same code works if switch to "asyncio"
```python
import pytest
import aiohttp


s = None


@pytest.mark.asyncio(scope='session')
async def test_pass():
    global s
    s = aiohttp.ClientSession()
    r = await s.get("http://www.example.com")
    print(r.status)


@pytest.mark.asyncio(scope='session')
async def test_pass_too():
    r = await s.get("http://www.example.com")
    print(r.status)
```

---

Please don't complain the global variable `s`. I know it looks ugly. What I present is just an example. It is just the simple version of the real-world code. In the actual code, there is no such a global variable.

And in order to save your time, I know how to workaround the issue. E.g., I could use a fixture instead of the global variable.
```python
import pytest
import aiohttp


@pytest.fixture(scope='session')
def anyio_backend():
    return 'asyncio'


@pytest.fixture(scope='session')
async def s(anyio_backend):
    return aiohttp.ClientSession()


async def test_pass(anyio_backend, s):
    r = await s.get("http://www.example.com")
    print(r.status)


async def test_pass_too(anyio_backend, s):
    r = await s.get("http://www.example.com")
    print(r.status)
```
or create a local session in each function instead of using a global one.
```python
import pytest
import aiohttp


@pytest.fixture(scope='session')
def anyio_backend():
    return 'asyncio'


async def test_pass(anyio_backend):
    s = aiohttp.ClientSession()
    r = await s.get("http://www.example.com")
    print(r.status)


async def test_pass_too(anyio_backend):
    s = aiohttp.ClientSession()
    r = await s.get("http://www.example.com")
    print(r.status)
```

**Comment by agronholm** [comment]
This works fine:
```python
import pytest
import aiohttp

pytestmark = pytest.mark.anyio


@pytest.fixture(scope='session')
def anyio_backend():
    return 'asyncio'


@pytest.fixture(scope='session')
async def http_session():
    async with aiohttp.ClientSession() as s:
        yield s


async def test_pass(http_session):
    r = await http_session.get("http://www.example.com")
    print(r.status)


async def test_fail(http_session):
    r = await http_session.get("http://www.example.com")
    print(r.status)
```
One issue was that you're forgetting to close the aiohttp session.

**Comment by ckyoog** [comment]
> This works fine:
I know it works fine. "Copy-paste" my code and telling me it works fine doesn't help with the issue.

**Comment by agronholm** [comment]
What code did I copy-paste? Not yours for sure.
From the looks of it, you're trying to use the pytest plugin in an unsupported manner. But since I don't know why you're trying to use it that way, I don't know how to help you.

**Comment by ckyoog** [comment]
The code snippet number 3 in my post.

**Comment by agronholm** [comment]
If you look more closely, your fixture for the aiohttp session doesn't close the session, and the tests don't explicitly depend on the `anyio_backend` fixture.

**Comment by ckyoog** [comment]
Don't be silly. They are the same, in the core.

And most important thing is I mentioned that the code snippet number 3 and number 4 are the workaround that I know. I wrote them out to save the time for people who is concern. My intention was "Hey friend, you don't need to tell me these workarounds, or say "the supposed manner of using pytest", because I know them. I just want you to focus on my issue, within the code snippet number 1." --  Looks like you don't get my point.

**Comment by agronholm** [comment]
Let me explain why this happens. The AnyIO pytest plugin works on a basis of "leases", so that each test or fixture gets a "lease" which is scoped to the function, or in the case of fixtures, the scope of the fixture. Therefore, if you have just two tests that don't share any common fixtures, they are run in separate event loops. The only reason to make the `anyio_backend` fixture scoped higher than function-scoped, is to make pytest happy so it can run higher order fixtures.

Can you explain why you're not able to use fixtures like this? AnyIO's pytest plugin isn't the same as pytest-asyncio, obviously, and it's expected to work differently. Why are you switching to it if you have such misgivings about the way it works? And finally, I remind you that I'm a volunteer, and I don't owe you anything, so could you try to be a bit more respectful in the way you speak to me?

**Comment by ckyoog** [comment]
I don't have to use Anyio this way. I just found the difference that pytest-asyncio can do while Anyio can't. So I published the issue in order to see whether it is a fixable issue, or in order to understand the root cause of the difference. And thank you for the explanation. Now I got what I am looking for:
- The internal way how the Anyio works
- The root cause of the difference
And finally, I am just a user, I don't expect you can answer me or help me. Since you responded me, I expected you at least took my post seriously, looked through my words carefully. Then we wouldn't have to wast our time on those useless conversations.

**Comment by fleming79** [comment]
Hi,

I think an async fixture with `autouse=True, scope="session"` will retain the event loop. 

Adding the following fixture will use the same event loop for the entire session. 

``` python
@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"

@pytest.fixture(autouse=True, scope="session")
async def common_event_loop(anyio_backend):  # noqa: ARG001
    # This autouse fixture ensures a common event loop.
    return None
```





# Example


## test_2 fails (different event loop)

``` python
import asyncio

import pytest


@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"


# @pytest.fixture(autouse=True, scope="session")
# async def common_event_loop(anyio_backend):  # noqa: ARG001
#     return None

pytestmark = pytest.mark.anyio

@pytest.fixture
def loop():
    return asyncio.get_running_loop()

loop_id = None

async def test_1():
    global loop_id
    loop_id =  id(asyncio.get_running_loop())

async def test_2():
    current_loop_id = id(asyncio.get_running_loop())
    assert current_loop_id == loop_id

```

## test_2 passes (common event loop)

The common event loop is maintained by `common_event_loop` which is scoped to the session. 
This means it isn't necessary to pass a fixture to each function, however it does mean that each
async function is assumed to be run by anyio (`pytestmark = pytest.mark.anyio` is not required).

``` python
import asyncio

import pytest


@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"


@pytest.fixture(autouse=True, scope="session")
async def common_event_loop(anyio_backend):  # noqa: ARG001
    # This autouse fixture ensures a common event loop.
    return None

# pytestmark = pytest.mark.anyio

@pytest.fixture
def loop():
    return asyncio.get_running_loop()

loop_id = None

async def test_1():
    global loop_id
    loop_id =  id(asyncio.get_running_loop())

async def test_2():
    current_loop_id = id(asyncio.get_running_loop())
    assert current_loop_id == loop_id


```
