### ISSUE TITLE
merge policy?

### ISSUE THREAD

**Issue by belm0** [agronholm/anyio#70]
anyio is being picked up by a lot of libraries 🚀 

I know for Trio at least, any typical project using Trio is going to have a transitive dependency on anyio.  At my workplace it's the case for a commercial product that uses Trio.

Given that, **I'm concerned that anyio code changes are committed without peer review in most cases.**  Could it follow the lead of trio itself, trio-websocket, and other libraries at this low level in the stack and maintain a pull request review policy?

Unit tests and high code coverage is nice, but having at least one other person look at changes can really help maintain code quality and avoid subtle and latent bugs.

**Comment by agronholm** [comment]
Are you saying that you volunteer to review my every commit? Or what do you mean?

**Comment by belm0** [comment]
Reviewers would have to be people you respect, so perhaps ask existing project contributors.  I mentioned already, but smurfix would be a good candidate if he has time.

PR's often group a number of logically related commits, so perhaps it's less overhead than you are thinking.  Scope would be determined by the policy (e.g. library code only, docs and config changes don't need review).

**Comment by agronholm** [comment]
How do you feel about this @smurfix ? Do you think you would have time to review anyio PRs in a reasonable timeframe?

**Comment by smurfix** [comment]
I'm most likely to be able to, but I can't hard-commit to that if "reasonable" is < 2…3 days.

**Comment by agronholm** [comment]
I've decided to make PRs of nontrivial features/fixes but directly commit less significant changes. Good enough?

**Comment by florimondmanca** [comment]
@agronholm I would wholeheartedly recommend putting in place reviewing and merge guidelines for `anyio`. If it aims to become a fundational piece of the Python async ecosystem, I think this would be 100% worth it.

IMO the policy should be akin to the following:

- Ensure that *all* changes go through a PR, even the smallest ones. (The goal here is to make everything discoverable, searchable, linkable, and make discussions possible/easier.)
- Try to get feedback on a PR *first*. If things get stalled, it *might* be OK to merge.

This *may* induce slower development, but then again this *will* result in even better quality code and help engage more people with the `anyio` project. And IMO, engaged contributors is exactly what a foundational open source project (such as `anyio` seems likely to become) needs most.

I'd be glad to give a helping hand with reviews, and I'm sure a few others would too. What do you think @agronholm?

**Comment by agronholm** [comment]
> If it aims to become a fundational piece of the Python async ecosystem, I think this would be 100% worth it.

AnyIO is meant to be a crutch, a bridge between asyncio and trio (and curio), giving users a way to slowly migrate towards structured concurrency, rather than jumping in with both feet. As asyncio gains the same features, I expect AnyIO's importance to wane. This is a very lengthy process, however.

> Ensure that all changes go through a PR, even the smallest ones. (The goal here is to make everything discoverable, searchable, linkable, and make discussions possible/easier.)

I'm not ready to go hardcore like this.

> I'd be glad to give a helping hand with reviews, and I'm sure a few others would too.

You're certainly welcome to do so!

**Comment by florimondmanca** [comment]
> As asyncio gains the same features, I expect AnyIO's importance to wane.

Good point, yeah.

> I'm not ready to go hardcore like this.

Maybe the way I wrote it made it sound hardcode, but I really think it's a sane process. For example, you'd get CI checks running on the code *before* it reaches master. Also, I think it's a really good way to help people (esp. reviewers) stay up to date with the latest changes.

Your call, though.

> You're certainly welcome to do so!

Sure :) Feel free to @ me, or add me as a contributor so that you can request a review from me. Probably also @smurfix?

**Comment by belm0** [comment]
> AnyIO is meant to be a crutch, a bridge between asyncio and trio (and curio), giving users a way to slowly migrate towards structured concurrency, rather than jumping in with both feet.

I'll speculate again that 90% of applications using Trio will find a transitive dependency on anyio.  For structured concurrency and cancellation to work you need cooperation all the way down the software stack.  So for Trio apps this means scrambling to find Trio-supported libraries (network clients & servers, logging, etc.), and there is high probability of one of those depending on anyio.

So a latent or subtle bug in anyio would have almost as much impact on the nascent Trio userbase as a bug in Trio proper.

I would think API is important too, and needs peer review.  Because this abstraction is hard, and trio/asyncio are moving targets.  If the API gets steered in the wrong direction, it could cause a lot of pain in terms of migration.  From the app's view, every transitive dependency needs to migrate to the fixed API, and that can be a long and frustrating process.

**Comment by smurfix** [comment]
I'm OK with "direct commit of less significant change", provided that the bar which trivial changes might slip through underneath is low enough. To me that means minor bugfixes only, certainly no API changes.

**Comment by agronholm** [comment]
Yeah, certainly no API changes w/o a PR :)

**Comment by smurfix** [comment]
I'd define/approximate "minor bugfix" as "touches one function [per back-end] and/or adds one testcase".

**Comment by agronholm** [comment]
I'm facing a bit of a problem with AnyIO 2.0 approaching. I have a series of important PRs including major API changes but not a lot of volunteers willing to review them. So as not to lose momentum on this, I'm leaning towards pushing forward with the changes and then releasing a beta (so I can still change the API if problems arise). How does that sound?

**Comment by smurfix** [comment]
Go for it.

**Comment by florimondmanca** [comment]
Agreed with ^.

(A thought — one thing I've been doing on solo projects is opening and merging PRs myself. Sounds silly but I've found it to bring huge benefits in terms traceability and changes history. But please do as you feel!)

Also popping by to say thank you so much for the work you've been doing on this project! ❤️

**Comment by agronholm** [comment]
I've done this with the 2.0 development and it seems like a good approach. It's also the easiest way to run the test suite on all the major platforms before merging a feature. I think I will close this issue now and use this method going forward.
