### ISSUE TITLE
anyio is unexpectedly cancelling tasks

### ISSUE THREAD

**Issue by Booplicate** [agronholm/anyio#716]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.3.0

### Python version

3.11

### What happened?

It appears that anyio is cancelling outer task. Originally I thought it was httpx, but the maintainer team helped to nail down the problem to anyio. [Original issue](https://github.com/encode/httpx/discussions/3154#discussioncomment-8944055) with more examples and discussion.

### How can we reproduce the bug?

Given example code:
```py
import asyncio

import anyio


async def loop():
    while True:
        stream = await anyio.connect_tcp('www.example.com', 80)
        # await stream.aclose()
        await asyncio.sleep(1)

async def spawn_task():
    task = asyncio.create_task(loop())
    while True:
        await asyncio.sleep(1)
        print("cancelling: ", task.cancelling())

asyncio.run(spawn_task())
```
Output:
```
cancelling:  1
cancelling:  2
cancelling:  3
cancelling:  4
cancelling:  5
```
Expected output: anyio shouldn't increment the cancelling counter of the outer task.

**Comment by Booplicate** [comment]
Same (?) code but using asyncio:
```py
import asyncio


async def loop():
    while True:
        stream = await asyncio.open_connection("www.example.com", 80)
        await asyncio.sleep(1)

async def spawn_task():
    task = asyncio.create_task(loop())
    while True:
        await asyncio.sleep(1)
        print("cancelling: ", task.cancelling())

asyncio.run(spawn_task())
```
Output
```
cancelling:  0
cancelling:  0
cancelling:  0
cancelling:  0
cancelling:  0
```

**Comment by agronholm** [comment]
I think this is an artifact of AnyIO's happy eyeballs implementation which makes multiple concurrent connection attempts and cancels the rest after one succeeds. I'm not sure yet why it would lead the incrementing of the host task's cancel counter though.

**Comment by agronholm** [comment]
Here's another repro that doesn't involve `connect()`:
```
import asyncio

import anyio
from anyio import Event, create_task_group, sleep


async def fail(tg, event):
    if not event.is_set():
        event.set()
    else:
        tg.cancel_scope.cancel()


async def loop():
    while True:
        event = Event()
        async with create_task_group() as tg:
            for _ in range(2):
                tg.start_soon(fail, tg, event)
                with anyio.move_on_after(0.3):
                    await event.wait()

        await asyncio.sleep(1)


async def spawn_task():
    task = asyncio.create_task(loop())
    while True:
        await asyncio.sleep(1)
        print("cancelling: ", task.cancelling())

asyncio.run(spawn_task())
```

**Comment by agronholm** [comment]
That `with anyio.CancelScope()` _seemingly_ does nothing here, but if it's commented out, the snippet no longer reproduces the problem.

**Comment by agronholm** [comment]
I've been digging into this for a while, and it's looking like `_deliver_cancellation()` increments the cancel counter of the wrong cancel scope when cancellation cascades to derivative cancel scopes. At least a particular one-line change seems to have fixed the issue. I'll just make sure it doesn't break anything else.

**Comment by agronholm** [comment]
An even simpler repro:
```python
import asyncio

import anyio


async def spawn_task():
    with anyio.CancelScope() as root_scope:
        with anyio.CancelScope():
            root_scope.cancel()
            await anyio.sleep(0)

    task = asyncio.current_task()
    print("cancelling: ", task.cancelling())

asyncio.run(main())
```
