### ISSUE TITLE
Typing issue while use ParamSpec

### ISSUE THREAD

**Issue by evgenii-moriakhin** [agronholm/anyio#745]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.4.0

### Python version

3.9.19

### What happened?

I needed to use `TaskGroup.start_soon` along with a function typed with `ParamSpec`

This leads to the following typing error (using Pyright), though it works correctly

![image](https://github.com/agronholm/anyio/assets/100143049/2dedfae1-8d86-496e-b822-9420fb2691d9)

```
Argument of type "*tuple[(sleep_time: int) -> Coroutine[Any, Any, None], Literal[2]]" cannot be assigned to parameter "args" of type "*PosArgsT@start_soon" in function "start_soon"
  Type "*tuple[(sleep_time: int) -> Coroutine[Any, Any, None], Literal[2]]" cannot be assigned to type "*tuple[(**P@exec_async) -> Awaitable[T@exec_async]]"
    "*tuple[(sleep_time: int) -> Coroutine[Any, Any, None], Literal[2]]" is incompatible with "*tuple[(**P@exec_async) -> Awaitable[T@exec_async]]"
      Tuple size mismatch; expected 1 but received 2
```

### How can we reproduce the bug?

Run static type checks with code:

```python
from collections.abc import Awaitable, Callable
from typing import TypeVar

import anyio
from typing_extensions import Concatenate, ParamSpec

T = TypeVar("T")
P = ParamSpec("P")

async def exec_async(
    fn: Callable[Concatenate[P], Awaitable[T]],
    *args: P.args,
    **kwargs: P.kwargs,
) -> T:
    return await fn(*args, **kwargs)

async def sleeper(sleep_time: int) -> None:
    print(f"sleep {sleep_time}...")  # noqa: T201
    await anyio.sleep(sleep_time)

async def main() -> None:
    async with anyio.create_task_group() as tg:
        tg.start_soon(sleeper, 1)
        await exec_async(sleeper, 2)
        tg.start_soon(exec_async, sleeper, 3)

anyio.run(main)
```

**Comment by agronholm** [comment]
Why do you presume this is a bug in AnyIO?

**Comment by evgenii-moriakhin** [comment]
Yeah, really, I'm sorry.

For some reason I was thinking from that point of view about the suggestion to translate task_group to `ParamSpec`

but now I've found reasons why not to do that.

https://github.com/agronholm/anyio/discussions/611
