### ISSUE TITLE
Add default `SIGINT` signal handler to `process_worker()` at `anyio.to_process`

### ISSUE THREAD

**Issue by jiho0307** [agronholm/anyio#747]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

`anyio.to_process.run_sync()` re-raise exception which occurs in task that parent process request to child. When work at terminal, `ctrl + c` is sent `SIGINT` to the foreground process group. At this time, the `process_worker()` process receives the `SIGINT` signal too and pickles `KeyboardInterrupt` as the return of `run_sync()`, an exception occurs again at that location even though main process already handled signal.

### Use case

I know that when using the `run_sync()`, just add exception handling for `KeyboardInterrupt` is simple. But wouldn't it be nice if the worker process of `anyio.to_process` had a signal handler to suppress `KeyboardInterrupt` by default?

**Comment by agronholm** [comment]
So...how then should `run_sync()` react to `KeyboardInterrupt` being raised from the subprocess? I don't think it can ignore that, as whatever it was running isn't running anymore, so it has to do _something_.

**Comment by jiho0307** [comment]
> So...how then should `run_sync()` react to `KeyboardInterrupt` being raised from the subprocess? I don't think it can ignore that, as whatever it was running isn't running anymore, so it has to do _something_.

Thank you for answer. My opinion was insufficient consideration of normal cases.
