### ISSUE TITLE
Support the asyncio ProactorEventLoop

### ISSUE THREAD

**Issue by njsmith** [agronholm/anyio#77]
Currently anyio's asyncio support relies on APIs like `add_reader` which are not guaranteed to be available, and in particular are not available when using the `ProactorEventLoop` on Windows.

Starting in 3.8, the `ProactorEventLoop` will be the default.

This isn't a big deal for programs that use `anyio.run`, because that can keep the old `SelectorEventLoop` default. But it's a big problem for libraries that use anyio internally, since they'll have to document that they don't work on Windows by default, and that anyone who wants to use them has to switch their whole program to a different event loop before they can use the library. That's going to be pretty awkward.

Tornado has a similar problem: https://github.com/tornadoweb/tornado/issues/2608

The standard asyncio solution to this is to use the protocols/transports layer; that's the lowest-level layer that's guaranteed to be portable. anyio might have to figure out how to do that...

**Comment by njsmith** [comment]
Some relevant discussion on BPO: https://bugs.python.org/issue37373

**Comment by agronholm** [comment]
I've mitigated this somewhat in the last couple commits. Should reduce the number of users hit by this issue. I've started work on an alternative networking implementation which, unfortunately, nixes `wait_socket_readable()` and `wait_socket_writable()` as they cannot be supported on Windows + asyncio.
