### ISSUE TITLE
aiofiles.tempfile.NamedTemporaryFile replacement

### ISSUE THREAD

**Issue by jameshilliard** [agronholm/anyio#786]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

It would be helpful if anyio had a replacement for [`aiofiles.tempfile.NamedTemporaryFile`](https://github.com/Tinche/aiofiles?tab=readme-ov-file#tempfile).

### Use case

I'm replacing aiofiles with anyio in a project and ran into an issue where there doesn't seem to be any tempfile operation support in anyio.

**Comment by agronholm** [comment]
Would you like to submit a PR? I have my hands full as it is.

**Comment by agronholm** [comment]
Also, isn't this a duplicate of https://github.com/agronholm/anyio/issues/344 ?

**Comment by agronholm** [comment]
Closing as duplicate.
