### ISSUE TITLE
pytest-anyio should raise error if sync test relies on async fixture

### ISSUE THREAD

**Issue by jakkdl** [agronholm/anyio#789]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Sync test function attempting to use async fixture fails silently. pytest-trio will raise a `RuntimeError` in this instance.

The one possible downside is that this will break users who have async autouse fixtures in the same file where they have sync tests. But this restriction probably isn't too onerous, and may catch bugs as well.

### Use case

Catch bugs and align behavior with pytest-trio

```python
import pytest

pytestmark = pytest.mark.anyio

@pytest.fixture(autouse=True)
async def async_fixture():
    assert False
    yield


def test_1(async_fixture):
    assert True

def test_2():
    assert True
```
will pass, but probably shouldn't

**Comment by euri10** [comment]
big +1 on this

**Comment by jakkdl** [comment]
It appears this works if the sync test explicitly requests the `anyio_backend` fixture
```python
import pytest

@pytest.fixture
async def fix():
    return 1

def test_foo(fix, anyio_backend):
    assert fix == 1
```
but if using `@pytest.mark.anyio`, `pytestmark = pytest.mark.anyio`, or forgetting to add anything, you get an unawaited coroutine object as the value.
