### ISSUE TITLE
AttributeError: 'Path' object has no attribute 'walk'

### ISSUE THREAD

**Issue by Goldziher** [agronholm/anyio#794]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.6.0

### Python version

3.11

### What happened?

Anyio.Path implements the `walk` method which is available in pathlib.Parth from python 3.12 onwards. For lower versions of python, this causes anyio.Path.walk to through an attribute error. 

I expected anyio to implement an alternative using os.walk on lower python versions, or at least to through an informative error instructing the user. 

### How can we reproduce the bug?

Try using anyio.Path.walk in a lower Python version.

**Comment by agronholm** [comment]
IIRC, implementing `Path.walk()` was not trivial, and I was pressed for time as there were other urgent updates to be done. But if you'd like to take a stab at this, I'm willing to review a PR. But by no means is this a bug.

**Comment by smurfix** [comment]
`Path.walk`doesn't exist in Python <3.12 (and throws an `AttributeError` when you try to use it), so why would I expect a different behavior from `anyio.Path.walk`?

**Comment by agronholm** [comment]
I suppose because there are other methods that I did implement for all Python versions where their stdlib counterparts required a specific minimum Python version. I can't remember off hand which methods those were though.

**Comment by Goldziher** [comment]
> IIRC, implementing `Path.walk()` was not trivial, and I was pressed for time as there were other urgent updates to be done. But if you'd like to take a stab at this, I'm willing to review a PR. But by no means is this a bug.

Well, its a question of documentation in this case.
