### ISSUE TITLE
AttributeError: type object 'Path' has no attribute 'parser'

### ISSUE THREAD

**Issue by hurek** [agronholm/anyio#797]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.6.0

### Python version

3.13.0a3

### What happened?

Error when importing anyio

### How can we reproduce the bug?

```
if __name__ == "__main__":
    import anyio
```

**Comment by agronholm** [comment]
Um, could you try with a more recent version of Python 3.13? AnyIO 4.6.0's test suite does pass on 3.13.

**Comment by hurek** [comment]
@agronholm everything is ok 3.13.0rc2. thank you!
