### ISSUE TITLE
Version 4.6.2 tagged on the wrong branch/commit

### ISSUE THREAD

**Issue by NickCao** [agronholm/anyio#811]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.6.2

### Python version

3.12.6

### What happened?

Version 4.6.2 is incorrectly tagged on the 4.5.x branch: https://github.com/agronholm/anyio/commit/5861355e2a882e0e33c209fcab287569c8405189, while the correct commit for 4.6.2 is not tagged: https://github.com/agronholm/anyio/commit/c4844254e6db0cb804c240ba07405db73d810e0b

### How can we reproduce the bug?

Check git log

**Comment by agronholm** [comment]
Force-pushed the `4.6.2` tag, added `4.6.2.post1`.
