### ISSUE TITLE
`AsyncFile.readinto()` has incorrect return type

### ISSUE THREAD

**Issue by sanmai-NL** [agronholm/anyio#825]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.6.2.post1

### Python version

3.12.6

### What happened?

For one, `AsyncFile.readinto()` was declared to return the generic type parameter rather than `int`, the number of bytes written [like the standard library method](https://docs.python.org/3/library/io.html#io.BufferedIOBase.readinto1). Should this method even be available for text IO?

### How can we reproduce the bug?

N.A.

**Comment by agronholm** [comment]
I fixed the immediate reported issue. If you have ideas on how to further improve the type annotations, let me know.

**Comment by sanmai-NL** [comment]
@agronholm Thanks! I raised a question in addition. I question whether `readinto()` etc. may even be provided for text IO objects. From my reading of the standard library docs, these are only available for binary IO objects.

**Comment by agronholm** [comment]
Yeah so there is no way to remove methods from a class just based on the type variables so the method exists but won't work.
