### ISSUE TITLE
Assertion error when `current_task()` returns an instance of `_asyncio.Task`

### ISSUE THREAD

**Issue by edgarrmondragon** [agronholm/anyio#840]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.7.0

### Python version

3.12.8

### What happened?

It seems that sometimes when `asyncio.current_task()` is called in

https://github.com/agronholm/anyio/blob/97f064295b65dc1d7a2ded6fd24ba5be46d4c4f4/src/anyio/_backends/_asyncio.py#L2367

an instance of `_asyncio.Task` is returned. This then causes an assertion to be raised in

https://github.com/agronholm/anyio/blob/97f064295b65dc1d7a2ded6fd24ba5be46d4c4f4/src/anyio/_backends/_asyncio.py#L685-L694

### How can we reproduce the bug?

This is triggered in our test suite (fastapi, httpx, pytest-asyncio) after upgrading to anyio 4.7.0, but I haven't been able to come up with a MRE so hopefully this is enough to point maintainers to the potential fix.

**Comment by agronholm** [comment]
What is `key` in this case then, if not a `Task`?

**Comment by agronholm** [comment]
Can you at least post the traceback?

**Comment by agronholm** [comment]
So how does that make any sense? It's checking if `key` is an asyncio task, and it is. What am I missing here? Why is this error triggered there?

**Comment by agronholm** [comment]
Are you using a custom task factory or something?

**Comment by edgarrmondragon** [comment]
> So how does that make any sense? It's checking if `key` is an asyncio task, and it is. What am I missing here? Why is this error triggered there?

It's an instance of `_asyncio.Task` (notice the leading `_` in the module name) instead of `asyncio.Task`. In case it helps, here's how I confirm that:

```python
(Pdb) key
<Task finished name='Task-47' coro=<test_google_callback() done, defined at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/mock.py:1408> exception=AssertionError("assert False\n +  where False = isinstance(<Task pending name='Task-47' coro=<test_google_callback() running at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/mock.py:1413> cb=[_run_until_complete_cb() at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py:181]>, <class 'asyncio.tasks.Task'>)\n +    where <class 'asyncio.tasks.Task'> = asyncio.Task")>
(Pdb) type(key)
<class '_asyncio.Task'>
```

> Are you using a custom task factory or something?

We are using something like

```python
def async_to_sync(
    func: Callable[_P, Coroutine[Any, Any, _R]],
) -> Callable[_P, _R]:
    """Decorator to convert an async function to a sync function using `asyncio.run`."""

    @wraps(func)
    def _decorator(*args: _P.args, **kwargs: _P.kwargs) -> _R:
        loop = asyncio.get_event_loop()
        nest_asyncio.apply(loop)
        return loop.run_until_complete(func(*args, **kwargs))

    return _decorator


class ItemGetter:
    @async_to_sync
    async def __getitem__(self, key: str):
        return ...
```

and then an instance of `ItemGetter` as a fixture, but I still can't find a MRE. The workaround on our end seems to be getting rid of that and instead just do


```python
class ItemGetter:
    async def get(self, key: str):
        return ...


@pytest.mark.asyncio()
async def test_example(getter):
    item = getter.get(...)
```

**Comment by agronholm** [comment]
> 's an instance of `_asyncio.Task` (notice the leading `_` in the module name) instead of `asyncio.Task`. In case it helps, here's how I confirm that:

Yes, that is the type of all asyncio tasks:
```pycon
>>> from asyncio import run, current_task
>>> async def foo():
...     task = current_task()
...     print(type(task))
...     
>>> run(foo())
<class '_asyncio.Task'>
```

**Comment by agronholm** [comment]
Wait, is `key` a Mock instance and not a task?

**Comment by agronholm** [comment]
No, probably not. At any rate, you need to either come up with a MWE or figure out why the assert fails.

**Comment by graingert** [comment]
Did you run nest-asyncio or something similar that replaced asyncio.Task with PyTask?

**Comment by chbndrhnns** [comment]
I have seen this issue yesterday while using the PyCharm, any 4.7.0. 
Only in the debugger in 2024.3.1 RC 2 and only with low impact monitoring api enabled.

I posted this to the [PyCharm tracker](https://youtrack.jetbrains.com/issue/PY-78056/Cannot-debug-web-apps-with-Low-impact-monitoring-enabled) first.

However, I cannot replicate today. Strange.

Here is the snippet:

```py
from pathlib import Path

import anyio
import uvicorn
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route

f = (Path(__file__).parent / "tmp")
f.write_text("hello")


async def read(file):
    async with await anyio.open_file(file) as f:
        content = await f.read()

    return content


async def homepage(request):
    res = await read(f)
    # set breakpoint on return statement
    return PlainTextResponse(f'{res}, world!')


if __name__ == '__main__':
    routes = [
        Route('/', homepage),
    ]
    app = Starlette(routes=routes)
    uvicorn.run(app, port=8080)
```

**Comment by s3rius** [comment]
We also found this issue in our ptoject. Here is the related issue:

https://github.com/taskiq-python/taskiq/issues/387

As people claim, it only happens on 4.7.0.

I could narrow down the MRE to this code:

```python
import asyncio
import nest_asyncio
import anyio


async def test_func():
    await asyncio.sleep(1)


async def main():
    nest_asyncio.apply()
    async with anyio.create_task_group() as tg:
        tg.start_soon(test_func)


if __name__ == "__main__":
    asyncio.run(main())
```

Here is the setup:

```
Python 3.12.7

anyio==4.7.0
nest-asyncio==1.6.0
```

**Comment by agronholm** [comment]
I figured out what's happening here. It seems that `nest_asyncio.apply()` replaces the asyncio modules in `sys.modules` with its own implementations, but not before they've already been imported by AnyIO. That's why the `isinstance` checks fail even though the MRO looks identical to real asyncio. I could confirm this by moving `nest_asyncio.apply()` to the module level:
```py
import asyncio
import nest_asyncio
import anyio


async def test_func():
    await asyncio.sleep(1)


async def main():
    async with anyio.create_task_group() as tg:
        tg.start_soon(test_func)


if __name__ == "__main__":
    nest_asyncio.apply()
    asyncio.run(main())
```
The above snippet works fine.

**Comment by agronholm** [comment]
By the way, may I ask what you're using `nest_asyncio` for?

**Comment by chbndrhnns** [comment]
For me, it seems to be part of the PyCharm debugger, and it’s used to be able to run coroutines in the debug console.

**Comment by agronholm** [comment]
Would you mind verifying that the linked PR works for you?
