### ISSUE TITLE
Different handling of queue with capacity=0

### ISSUE THREAD

**Issue by tkukushkin** [agronholm/anyio#86]
```python
queue = anyio.create_queue(capacity=0)
assert queue.full()
```
On trio `capacity=0` means real zero capacity and `put` blocks on `get`, on asyncio, curio `capacity=0` means inifine capacity.

If you choose which behaviour is right, I would make pull request with fix.

**Comment by agronholm** [comment]
Hopefully nobody is relying on either behavior :)
I don't think queues that are always full are very useful to anyone, so I'd lean towards them having infinite capacity.

**Comment by tkukushkin** [comment]
Zero capacity channels often used in Go, trio and CSP at all, I think it is wrong to remove this feature. Perhaps `None` (how `functools.lru_cache` works) or `math.inf` (how trio channel works) is better solution for infinite capacity.

**Comment by agronholm** [comment]
What use is a zero capacity Queue? I'd also like to point out that trio does not even have a Queue class anymore. This is not about how to make infinite capacity queues, it's how to react to `capacity=0`.

**Comment by agronholm** [comment]
Ok, seems like the entire debate is moot since the docstring of `asyncio.Queue` says this:
> If maxsize is less than or equal to zero, the queue size is infinite.

This means it is not possible to have asyncio queues of zero capacity. I will change the trio backend to reflect this fact.
