### ISSUE TITLE
Should we expose raw sockets in socket-based streams?

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#93]
The WIP v2 code exposes the stdlib socket objects from the stream to the user. Should we keep doing this, or simply expose methods like `getsockopt()` etc., as we see fit?

Pros:

* Would allow the user to use the socket for use cases we did not foresee

Cons:

* Would allow the user to introduce subtle problems by doing bad things, like calling `setblocking(True)`
* None of the supported back-ends expose the raw socket object
* Some back-ends require accessing a private attribute to get the raw socket
* We should probably add those convenience methods anyway

**Comment by agronholm** [comment]
Another option: expose an async-wrapped socket like how trio does. But will that cover all use cases?

**Comment by aeros** [comment]
> Another option: expose an async-wrapped socket like how trio does.

I think the approach in trio makes sense, as they provide an async-wrapped socket API for the majority of users through a high-level API, but expose `getsockopt()`/`setsockopt()` for users that want additional functionality.

IMO, it provides a good balance between preventing most users from accidentally shooting themselves in the foot and providing enough extensibility for library maintainers (or advanced users). Then, if a particular feature is frequently being extended (or requested) by many separate users for convenience, you can consider eventually adding it to the async-wrapped socket class.

> But will that cover all use cases?

I don't think it's realistically feasible to cover all possible use cases while simultaneously maintaining a reasonable API surface area and high usability. There's always going to be some functionality or convenience features that are  missing, that's inevitable to some degree.

**Comment by agronholm** [comment]
And how would you provide an async-wrapped socket class in the asyncio backend?
Problems:

- `sock_recv()`, `sock_send()` and `sock_accept()` have cancellation related bugs in various Python versions (I just submitted a patch against the last one)
- There is no `sock_recvfrom()` or `sock_sendto()`, not to mention `sock_recvinto()` et al.
- Transports and protocols are higher level constructs which makes their use challenging in this capacity at best

**Comment by agronholm** [comment]
I'm currently leaning towards exposing the stdlib socket object, as an escape hatch for advanced uses cases. I will make sure to include some words of warning about its use.
