### ISSUE TITLE
Transparently entering and exiting anyio land

### ISSUE THREAD

**Issue by vxgmichel** [agronholm/anyio#95]
This follows up on an old discussion that started [here](https://github.com/agronholm/anyio/issues/37#issuecomment-481215995).

As far as I understand, anyio has been designed to provide a generic layer on top of specific backends and it works great for this purpose. 

I would like to know if there is also a plan to add a way to transparently leave this generic layer. Here is an example where this can be useful: let's say I write a coroutine using asyncio:
```python
def mycoro(*args):
     # Bunch of asyncio stuff here
```
It would be nice to be able to use it with trio too! I could write a separate version, or I could fully rewrite it using anyio:
```python
def mycoro(*args):
     # Bunch of anyio stuff here
```
It works great, but then I realize it doesn't exactly behave the same as before: for instance the exceptions are now anyio exceptions. That means that any caller of `mycoro` should be anyio aware. Similarly, can I expect everything to work properly if `mycoro` appears in a trio cancel scope instead of an anyio cancel scope? 

It would be great if there was a way to transparently enter and leave anyio-land, because the coroutine could then be written as:
```python
def mycoro(*args):
    with anyio_context():
        # Bunch of anyio stuff here
```
Then `mycoro` could go in a library that anyone could use, regardless of the backend there are using and without having to stick to anyio.

Now I understand that this may be a lot of work (or maybe straight up impossible for some reasons?), but I'd like to know if there is a plan to support this kind of use case.

And thank you for your work :)

**Comment by agronholm** [comment]
I think you need to give more concrete examples. AnyIO does not do any monkey patching, so the only way you would be getting AnyIO exceptions is if you're still using AnyIO's functionality.

**Comment by vxgmichel** [comment]
It seems like we keep talking past each other with this particular point, this was already the case back in [April](https://github.com/agronholm/anyio/issues/37#issuecomment-481637428). I'm quite confused now, hopefully you can clear it up for me:
- Would you say it's ok to use anyio in a library (instead of a full application)? 
- If yes, are there constraints / downsides?
- What are the implications for the library user? Does he have to use anyio too?

**Comment by agronholm** [comment]
> Would you say it's ok to use anyio in a library (instead of a full application)?

Yes, it was explicitly designed to be used that way.

> If yes, are there constraints / downsides?

Cancel scopes only cover AnyIO-spawned tasks, except on Trio which has native support.

> What are the implications for the library user? Does he have to use anyio too?

They're already using AnyIO if they're using a library that uses AnyIO.
In case you're referring to `anyio.run()`, that's just a convenience function, not a mandated entry point.

**Comment by agronholm** [comment]
Do you need further clarification or can we close this issue?

**Comment by njsmith** [comment]
Maybe it helps to point out: there is no such thing as "anyio land". There's just Trio-land, Asyncio-land, Curio-land. Anyio is a library that provides functionality that happens to work in all of these lands. It doesn't provide any land of its own, and if for some reason you want to mix anyio+native trio code, or anyio+native asyncio code, then it will work fine (though of course your code won't be as portable as if you used anyio alone).

**Comment by agronholm** [comment]
I couldn't have said it better myself, thanks :smiley:

**Comment by vxgmichel** [comment]
@agronholm @njsmith Thank you both for clarifying, that helped a lot :)

> and if for some reason you want to mix anyio+native trio code, or anyio+native asyncio code, then it will work fine

Great, that's exactly the part I'm interested in. I started to have doubts about that when I realized that anyio has its own exceptions. For instance:
- `trio.TooSlowError` becomes `TimeoutError`
- `trio.MultiError` becomes `anyio.exceptions.ExceptionGroup`
- `trio.ClosedResourceError` becomes `anyio.exceptions.ClosedResourceError`
- `trio.ResourceBusyError` becomes `anyio.exceptions.ResourceBusyError`
- `trio.WouldBlock` becomes `anyio.exceptions.WouldBlock`

I assume that those exceptions have a special meaning in the trio world. For instance, what happens if a `MultiError` appears in an `ExceptionGroup`? Or the other way around? Will the rest of the trio ecosystem be able to deal with it properly?

More generally, isn't it a bit surprising for a trio user to see a `TimeoutError` bubble up from a third-party library that simply happens to be using anyio under the hood? This user would have to remember that for those particular library calls, the exception is different from the standard `trio.TooSlowError`.

**Comment by agronholm** [comment]
Hopefully one day we will have a unified set of these exceptions, but until then, I see no way around having to translate them. If a piece of trio based code uses an AnyIO library and expects to catch trio exceptions from it, I'd say it's broken. Likewise, an AnyIO library should ideally not use a backend specific library, or if it does, it should explicitly translate the exceptions to the generic AnyIO ones.

**Comment by vxgmichel** [comment]
> If a piece of trio based code uses an AnyIO library and expects to catch trio exceptions from it, I'd say it's broken.

The problem is that this piece of code might not know that it's using AnyIO since it's hidden in a library somewhere.

> Hopefully one day we will have a unified set of these exceptions, but until then, I see no way around having to translate them.

What about providing this kind of context manager:
```python
@contextmanager
def enter_anyio_context():
    try:
        yield
    except Exception as exc:
        if not is_anyio_exception(exc):
            raise
        if not is_outermost_anyio_context():
            raise
        raise to_backend_specific_exception(exc)
```

It would behave like this:
```python
async def coro():
    with anyio.enter_anyio_context():
        async with anyio.fail_after(1):
            await anyio.sleep(2)

async def main():
    try:
        await coro()
    except Exception as e:
        print(repr(e))

anyio.run(main)     # Prints `TimeoutError()`
trio.run(main)      # Prints `trio.TooSlowError()`
curio.run(main)     # Prints `curio.errors.TaskTimeout()`
asyncio.run(main()) # Prints `concurrent.futures._base.TimeoutError()`
```
Library developers could use this context decorate all the sensitive anyio sections in their code to easily provide backend compatibility.

Not that the opposite function `exit_anyio_context` might also be useful in some context, for instance when a user coroutine is passed to a library. Consider the following example:
```python
def run_with_timeout(coro, timeout):
    with anyio.enter_anyio_context():
        async with anyio.fail_after(timeout):
            with anyio.exit_anyio_context():
                await coro()
```
This way, `run_with_timeout` works with every backend without the caller having to know about anyio at all, unless they are using anyio themselves.

I hope this makes sense :)

**Comment by agronholm** [comment]
> The problem is that this piece of code might not know that it's using AnyIO since it's hidden in a library somewhere.

Dunno about you, but I encounter unexpected exceptions all the time, usually because library authors don't document what exceptions the functions raise. Usually such runaway exceptions are a sign of a bug in that library. I don't see any particular problem here.

Have you encountered such difficulties in practice or is this purely theoretical?

> I hope this makes sense :)

No, it doesn't. How is any code supposed to sanely handle any arbitrary exceptions being raised deep from within a library that said code knows nothing about?

**Comment by vxgmichel** [comment]
> Have you encountered such difficulties in practice or is this purely theoretical?

I admit this is theoretical, but the scenario of trio users ending up with an exception mixing `MutiError` and `ExceptionGroup` seems quite realistic to me. As a library developer, I'd rather have a separate trio implementation than risking exposing the users to those kind of issues.

>> I hope this makes sense :)

> No, it doesn't.

That sounds unnecessarily harsh. I don't feel motivated enough to keep discussing this issue, feel free to close it.

**Comment by agronholm** [comment]
> That sounds unnecessarily harsh. I don't feel motivated enough to keep discussing this issue, feel free to close it.

I'm sorry if I've offended you somehow but I don't know how else to convey the fact that I do not see the problems that you are seeing and in the absence of practical examples I don't know what else to say than what I already have.
