### ISSUE TITLE
Do we need separate ClosedResourceError and EndOfStream exceptions?

### ISSUE THREAD

**Issue by agronholm** [agronholm/anyio#96]
Right now, AnyIO does not make a difference between the peer closing a stream and another task closing it. Should AnyIO distinguish between the two, and for what purpose?

**Comment by smurfix** [comment]
Yes, that is helpful. If the peer closes a stream I might want to log an error, reconnect, or whatever. On the other hand, if I did it myself then presumably I am already handling an error, or closing down, and want to do none of these things.

**Comment by agronholm** [comment]
What about byte streams, like a TCP socket stream? I've noticed that sometimes I get an empty `bytes` object, sometimes `ConnectionResetError` is raised when the peer closes the connection.
Message streams, on the other hand, cannot really send an empty message to indicate the closing of the connection, so an exception is a must. My goal was to make it possible to use both `ByteStream` and `MessageStream[bytes]` for anything that communicates by exchanging bytestrings (`TLSWrapper` for instance). For that to work, the exceptions must be in line with each other.

**Comment by agronholm** [comment]
We have separate exception classes for these, so I'm closing this.
