### ISSUE TITLE
PyPI's Wheel for 1.2.2 contains extra files, breaks imports.

### ISSUE THREAD

**Issue by wizpig64** [agronholm/anyio#97]
The wheel release of anyio 1.2.2 on PyPI includes some extra files that aren't in the source `.tar.gz` or committed in the git repo.

The `_sockets.py` and `_utils.py` files don't harm anything, but there's an in-progress refactoring of `anyio/abc.py` into the package `anyio/abc/*.py` which is causing some import errors. When I manually deleted my `site-packages/anyio/abc/` folder, my tests started passing again.

Please release a 1.2.3 without this folder in the wheel.

Thanks :)

**Comment by agronholm** [comment]
Agh, this is exactly why I migrated into the src layout in v2!

**Comment by agronholm** [comment]
v1.2.3 upload to PyPI.
