### ISSUE TITLE
Possible to run an async task in context of synchronious function?

### ISSUE THREAD

**Issue by makkus** [agronholm/anyio#99]
I'm not sure whether I'm overlooking something obvious, but is it possible to run a single asynchronous task in the context of a non-asynchronous function (like it is with asyncio.create_task(xxx) )?

The following is code that works with asyncio, is there an equivalent for anyio?

``` python
async main_func():
    
    some stuff...

    def event_happended(source, event_type, event_details):

        print("event_type: {}".format(event_type))

        async def wrap():
            childs = await source.get_values()
            print(childs)

        asyncio.create_task(wrap())

    pub.subscribe(event_happended, "topic-name")
```

Context is a pubsub library that doesn't support co-routines, so I'm forced to use synchronious handler functions.

I can't use anyio.run, since that requires no event loop currently running, whereas in my case there's already one. Happy for any suggestions about how to organize my code differently too, if this is not possible with anyio directly...

**Comment by agronholm** [comment]
Have you read the documentation? https://anyio.readthedocs.io/en/latest/threads.html#calling-asynchronous-code-from-a-worker-thread

**Comment by makkus** [comment]
@agronholm yes, I have. I don't want to run this in a worker thread, but in the 'normal' event loop. Also, the documentation mentions this would only work if the worker thread was spawned with ``run_in_thread``, and I don't see how I can do that nicely with a callback assignment like in my example code. 

There's a good chance I just misunderstand how all this works, but it looks to me that the asyncio specific solution I mention in my original comment works much simpler and does not involve creating a worker thread for every call back I want to register?

**Comment by agronholm** [comment]
Ah okay, I think I understand now. You're running a synchronous function in the event loop thread and you want to create an asynchronous task from that synchronous function. Unfortunately this is not possible with the AnyIO API since thanks to Curio, task spawning requires an `await`. If you're simply writing an application and not an AnyIO library, you can work around this by using the native `create_task()` call.

**Comment by agronholm** [comment]
Also, what is this pubsub library you're talking about?

**Comment by makkus** [comment]
@agronholm thanks for that. I'm not writing a an AnyIO library directly, but I would like to not have to depend on async-framework specific code if easily possible. Won't bend over backwards just to avoid it either, though. So maybe I'll just write a small wrapper function then, to at least support asyncio and trio out of the box, and spawn a thread when using Cuio.

I'm using [pypubsub](https://pypubsub.readthedocs.io/en/v4.0.3/) (I've created [an issue](https://github.com/schollii/pypubsub/issues/46) asking for 'direct' co-routine support for their callbacks, but haven't heard back yet). I could imagine stumbling upon that problem in other circumstances where providing callback methods is involved though.

**Comment by agronholm** [comment]
It just seems strange to use a blocking pub/sub system in an async application. But without knowing further details I can't suggest anything better.

**Comment by makkus** [comment]
Yeah, I've shopped around and this one fit my use-case best, and it's fairly mature and stable. If you know of any good async ones that are not married to asyncio (and work well with anyio), I'm more than open to suggestions...
